### ISSUE TITLE
FBR Cyberlimb AGI and STR issue

### ISSUE THREAD

**Issue by Nitsuj83** [chummer5a/chummer5a#1009]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (5.182.0)
Environment: (Windows 7 and Windows 10)
Runtime: (4.5.1)

### Expected behaviour
(AGI and STR reflecting augmented cyberlimb AGI and STR via customized STR and AGI and Ehanced AGi and STR. So if I have Customized Agility & Strength with Enhanced Agility and Strength in all four limbs it should read augmented AGI and STR as 9)

### Actual behaviour
(Even with full custimized AGI +STR and enhanced AGI + STR the augmented values are only showing 3 instead of 9 )

### Steps to reproduce the behaviour
(Added all four limbs with customized AGI +STR and Enhanced AGI + STR)

### Link to affected character file
(
[FBR test.zip](https://github.com/chummer5a/chummer5a/files/362344/FBR.test.zip)
)

**Comment by chummer5a** [comment]
Right, so there's a few things going on here. The major one is that Chummer doesn't treat lower limbs as full limbs for the purposes of these calculations. Second is that we consider the torso and skull to be limbs for the purposes of averaging (You can choose to ignore either the skull or the torso in the options menu under Character and Printing). so you essentially have six limbs at 1/1/1/1/9/9, which averages out to 3.6 and then gets minned down to 3. As far as I'm aware that's per RAW, unless you can provide something to indicate that lower limbs quality for the averaging of the whole stat.

The easiest fix is probably going to be to alter the tooltip code for skills and attributes to show which cyberlimbs have the appropriate stat increases, rather than excluding the ones that don't have a limb slot. Small chance of weirdness there, but it should be fine.
