### ISSUE TITLE
Wired Reflexes + Reaction Enhancers

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1035]
### Environment
Chummer Version: 5.182.25 and 5.182.0
Environment: Windows 10
Runtime: NET 4.5.1

### Expected behaviour
If wireless is enabled, the bonus to Reaction from Wired Reflexes and Reaction Enhancers should be able to get above +4. (SR5 page 455) 

### Actual behaviour
The bonus does not go above +4.

### Steps to reproduce the behaviour
Make a Character with Wired Reflexes rating 3 and Reaction enhancers rating 3. (Or som other combo that is a combined rating more than 4)

### Thank you
Thank you again to all who dedicate their time to improving this Character generator.

**Comment by chummer5a** [comment]
We currently don't support enabling wireless bonuses. It's on the docket,
but due to the complexity (Fairly large replacement of the bonus code, many
many edge cases) and lack of resources it's not likely to be handled for
some time. If you're in career mode, the simplest method would be to create
a custom improvement that adds the appropriate amount of reaction.

**Comment by drakir75** [comment]
If not wireless enabled they should not be able to stack at all. They do stack, just not beyond +4. For example a Wired Reflexes rating 2 and a Reaction Enhancer rating 2 gives a + 4 bonus to Reaction. This should only work with wireless enabled. Either wireless is enabled default for this combo or Chummer should not add the bonuses up. (Maybe not count the Wired Reflexes, because it's not always activated. )

**Comment by chummer5a** [comment]
Ah, I see the problem. This was fixed in one of the more recent nightly builds, I spaced out a bit and thought it was fixed ages ago. Please try the new build and see if that helps.
