### ISSUE TITLE
Pixie with Astral Perception lacks the Assensing skill

### ISSUE THREAD

**Issue by karrot1** [chummer5a/chummer5a#1058]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)
### Environment

Chummer Version: 5.1.8.3
Environment: Windows
Runtime: (If you don't know this, it is probably .NET 4.5.1)
### Expected behaviour

Anything with Astral Perception should be able to put points in assensing.
### Actual behaviour

Pixies can not put points in assensing.
### Steps to reproduce the behaviour

Make a pixie character who lacks the magician quality, go to the skills tab, assensing isn't there.

**Comment by sphassan** [comment]
This seems to be due to the logic of unlocking skills being handled by category instead of specifics. (Correct me if I'm wrong, I'm learning the codebase right now.) An easy fix would be to give Pixies access to all Magical Active skills, but that'd be kind of dirty. A fix for this would be similar to (existing?) code that only unlocks Assensing for Adepts with the Astral Perception power.

**Comment by chummer5a** [comment]
There's no existing code for that in the master branch. I pushed an initial effort at it a while back in https://github.com/chummer5a/chummer5a/tree/SingleSkillFilter, but there were some issues with it. Works fine for pixies, but for things like Adepts that unlock it through a Foci that can be turned off and on, it drops the skill. Also doesn't handle multiple sources that grant the same skill.
