### ISSUE TITLE
Adding a Plugin to a Custom piece of gear crashes chummer.

### ISSUE THREAD

**Issue by DedElephas** [chummer5a/chummer5a#1110]
### Environment
Chummer Version: 5.183.0
Environment: Windows 7
Runtime: (probably .NET 4.5.1)

### Expected behaviour
Custom item that i am adding a plugin to, actually lets me add one

### Actual behaviour
It crashes when i do so

### Steps to reproduce the behaviour
-custom item "Booze flask"
- add plugin

**Comment by chummer5a** [comment]
Can't replicate the issue. What plugin are you trying to add?

**Comment by DedElephas** [comment]
I made a Custom item called "Booze Flask",
I right click and do 'add as plugin' with the intention of adding Laés to it,
Then it crashes.
(And adding Laés and then dragging it to the flask only rearranges the list)


Ps. Thanks for responding so actively to errors
 (Not sarcasm)


Sent from Samsung tablet


-------- Original message --------

**Comment by chummer5a** [comment]
Hrm, still can't replicate it. You can drag items onto other items if you use right-click, does that work?

**Comment by DedElephas** [comment]
Surprisingly yes, it does work like that.
Though normal right click "add as plug in" doesn't, but right click dragging is fine as well (didn't know you could do that).

Thanks
Sincerely yours,
Simon Somville



Sent from Samsung tablet


-------- Original message --------

**Comment by chummer5a** [comment]
One of those buried features that was added way back in old Chummer and isn't properly documented anywhere. I'll die happy the day I get a volunteer technical writer to go through everything and build me a support document.

**Comment by Iridios** [comment]
I'd be happy to take on the project of writing a support document, just don't die on us.  We need you healthy, happy, and coding. :)

**Comment by chummer5a** [comment]
![image](https://cloud.githubusercontent.com/assets/11448441/19175852/31d7f704-8c86-11e6-9897-4cd207417940.png)

**Comment by Lochabar** [comment]
Would this be a support document for the wonderful coders?
Or the wiki update from issue 715?

I've been keeping notes of items that could be included in the wiki.

**Comment by Iridios** [comment]
My initial plan is to write a document for users, especially new users.  Initially it will be a PDF document that can be downloaded.  Once that is mostly done I'll start looking into making an online version.  

As I understand it no one on this project has admin access to the old Chummerwiki.  I was planning on scraping the wiki so we can have the information and maybe start a new one.

I would be happy to have your notes for this project.  I am planning to go to both Reddit and the SR forum for ideas and information once I have a rough outline in place.

It's been a slow start because this weekend is my son's birthday and there has been a lot prep for that.

**Comment by joha4270** [comment]
@Iridios May i recommend markdown instead of pdf? 
Plays nicer with version control so it is easier for multiple people to provide updates and it can be keept in the repository. 
You get web for free, and i have seen several converters from markdown to pdf. Some of them automated, so making nighties+releases automatically contain a manual should be easy enough

Also, should we create an issue to discuss Manual (or documentation?) instead of hijacking this one?

**Comment by Iridios** [comment]
I agree with using another Issue to discuss.  I've used markdown before without really knowing what it was called.  I've never used it to build a document before because I haven't had need of something flexible.  Tech writing is not my primary job but I do prepare small documentation from time to time, thus using PDF primarily.

**Comment by Lochabar** [comment]
Reopen issue 715

**Comment by joha4270** [comment]
#751 is about some wiki links, I read @Iridios as intending to start with something closer to a manual? In that case i think we should start a new one

**Comment by DedElephas** [comment]
@joha4270 
High activity will attract more attention, thus more chance of a solution.
Also, I'm just posting a bug (that you can apparently work around) so no worries.

**Comment by chummer5a** [comment]
Getting back to the topic of the original issue, can you try and crash it again, hit Yes when it prompts you to send an error report, then click the link for 'What does this error report contain?'. I'd like to see the exception.txt file's contents.

**Comment by DedElephas** [comment]
[exception.txt](https://github.com/chummer5a/chummer5a/files/522177/exception.txt)
Here you go @chummer5a

**Comment by chummer5a** [comment]
Aha, that's the bunny! Okay, so the problem is that you've got quotation marks inside the name. Remove that and you'll be all good.

**Comment by DedElephas** [comment]
yup, works like a charm
