### ISSUE TITLE
Chummer will not open

### ISSUE THREAD

**Issue by TW3ET** [chummer5a/chummer5a#1132]
### Environment
Chummer Version: 5.184.x (All versions currently out)
Environment: Windows 10
Runtime: .NET 4.6.2

### Expected behaviour
Chummer should open when I run the executable.

### Actual behaviour
After first installing chummer and running the executable, a settings file is created that is empty but then nothing happens. Further attempts to run produce no obvious results.

### Steps to reproduce the behaviour
Install chummer and then attempt to run it. I've tried restarting the computer, deleting chummer and reinstalling, and trying different versions. Versions before 5.183 run, but crash when attempting to open a character sheet made with the later editions.

**Comment by TW3ET** [comment]
Tested .14 and .15 with the same results. Attempting to run chummer 5 from a clean install creates an empty settings file and then nothing else.

**Comment by chummer5a** [comment]
So you just launch the application and it crashes? It's most likely that's due to it not being able to load a file into the character roster from your MRU, but it shouldn't be causing you problems. Try opening your registry and navigating to HKEY_CURRENT_USER\Software\Chummer5 and deleting all the keys that start with mru.

**Comment by TW3ET** [comment]
Excellent, thank you. That did resolve the issue.
