### ISSUE TITLE
Errors in Weapons.xml file

### ISSUE THREAD

**Issue by Thelinil** [chummer5a/chummer5a#1191]
Environment
Chummer Version: 5.187.0
Environment: Windows 8.1
Runtime: .NET 4.5.1

There are some typos, errors, and missing accessories in the weapons.xml file
Ultamax HMG-2 should be Ultimax HMG-2
Ultamax MMG should be Ultimax MMG
Ares SIGMA 3 is missing Foregrip
P93 Praetor should have a Stock, not a Folding Stock (it has a rigid stock in the fluff block).

**Comment by chummer5a** [comment]
The naming convention for those guns is all over the place. There's an Ultimax machine pistol, but the machine guns are Ultamax in all the stat and fluff blocks. In the master index, it's Ultramax for the machine guns, but ultimax for the machine pistol. Until I see an errata document one way or the other, I'd rather leave it as the more consistent naming convention for now. 

Anyway, mostly fixed in 1dba3ec.
