### ISSUE TITLE
Buying Skills in Chargen with Karma

### ISSUE THREAD

**Issue by Maxis010** [chummer5a/chummer5a#1209]
### Environment
Chummer Version: 5.187.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Buying skills in Chargen follows the New Skill/Improve skill karma costs

### Actual behaviour
Buying a new skill has no cost
Improving a skill has cost - 1

### Steps to reproduce the behaviour
Add karma to any skill in chargen

**Comment by chummer5a** [comment]
Can't replicate it. What skills, specifically?

**Comment by drakir75** [comment]
Op might have misunderstood the way one buys knowledge skills and/or forgotten about the "Jack of all Trades" quality. Does not make skills free, but provides the discount.

**Comment by Maxis010** [comment]
Forgot a stage in Steps to reproduce
My group altered our Karma costs to 1x for Knowledge and Skills

Knowledge skills is now working as expected (Version 5.189.0)
Skills are still apparently bugged

Improving a skill to 6 with pure Karma is only costing 10 total
First skill point is completely free

**Comment by chummer5a** [comment]
Right, now I see what's going on. Dropping it down to 1 base breaks part of the math.

**Comment by Hood281** [comment]
I fixed this issue but having difficulty creating a pull request. The fix is to simply delete lines 369, 370, and 371 in Skill.core.cs
They look like:
			cost /= 2;
			cost *= CharacterObject.Options.KarmaImproveActiveSkill;

The problem is that the above 2 lines appear in RangeCost() and then again right afterwards
These lines cancel themselves out if KarmaImproveActiveSkill is 2, but if it's anything else it squares the difference (so for example if you set it to 1, it halves twice instead of once). Deleting those lines takes care of the issue.
