### ISSUE TITLE
DROID?

### ISSUE THREAD

**Issue by Mddd2009** [chummer5a/chummer5a#1234]
Actually more of a questions than an Issue, is there any chance you will be making chummer available on the Droid Play Store or available for droid.

**Comment by chummer5a** [comment]
As is, support for mobile devices isn't one of our intended goals for the project, largely because the Winforms UI Chummer is built with is functionally incompatible with Android and mobile-style form factors. One of our contributors is working on a redo of the UI using WPF, which will then relatively easily allow us to support non-desktop form factors and resolutions. No ETA on when that will be.

**Comment by chummer5a** [comment]
Outside the scope of the project as is.
