### ISSUE TITLE
Credstick functionality

### ISSUE THREAD

**Issue by Neocyberman** [chummer5a/chummer5a#130]
In char creation credsticks have a rating that as far as I can discern serves to represent money held.

However after character creation there is no field to 

From what I understand of the code this will take some additions to the XML reading code as well as GUI/career mode code. Its not necessarily a priority. Take your time.

**Comment by chummer5a** [comment]
Credsticks honestly need some kind of overhaul, as is they're roughly
useless. I was thinking about a banking/lifestyle tab that would allow you
to handle paying for all your monthly sundries, assign where your nuyen is
in your credsticks, etc.

I need to have a think about what all needs to be in it.

**Comment by Neocyberman** [comment]
By the by which .cs file handles career mode and career mode stats?

**Comment by chummer5a** [comment]
frmcareer.cs, but there's a few triggers throughout the code that check for
whether blnCreated is true to determine whether you're in career mode or
not.

**Comment by knightaries** [comment]
One way I see this could be (temporarily) fixed.
Add in the gear XML file Nuyen
Treat the Credstick like a spare clip (under gear) and have Nuyen as an automatic plugin where the character can add or subtract nuyen in the plugin
Remove rating option for the credticks.

Personally I'm not sure how much coding adjustment would be needed for this.

**Comment by joha4270** [comment]
While we are at it, can you also build a house and cook stew for an army?

What you are asking for is in no way simple. It might be simple to do if that was the only think required, but chummer made some design decisions a long time ago, making this quite hard.

One day we might get a matrix details tab with this info, but i very much doubt it will get fixed beforehand.

**Comment by knightaries** [comment]
Oh for crying out loud. It's been 20+ years since I've done any programming and I'm still trying to figure the coding out. I did see where you said that an overhaul was needed and gave an idea that I wasn't sure if it was doable/feasible hence the very last line being "Personally I'm not sure how much coding adjustment would be needed for this." because I understand that what appears to be simple isn't always the easiest thing in the programming world to do. But the only way to know what can or cannot be done is by giving idea's and seeing what can be done.

Personally if I knew how and had the proper languages/compilers I'd actually help as I do usually have available time but sadly I had learned COBOL and RPG for mainframes and not anything else.

On the other hand I can't build a house but I have had to help with repairs to a Warship as for the cooking stew... Only if you want the army to die. :-D

**Comment by joha4270** [comment]
Well, if you feel like learning, [visual studio](https://www.visualstudio.com/) Comunity is free, and a dream to use. (even if a little big)

Feel free to take a crack at it and i might even answer questions about how the internals i understand works.
