### ISSUE TITLE
Magical attributes disappearing?

### ISSUE THREAD

**Issue by dluxcru** [chummer5a/chummer5a#1320]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version:  1.88.3, persists when file is opened in 1.89.0
Environment: (Operating system here. If it persists over multiple OS's list them all)
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
A mystic adept should have skills accessible that are based in the magical active category. 

### Actual behaviour
Chummer does not list magical skills for this charecter. 

### Steps to reproduce the behaviour
Create a charecter like the one in the file?

### Link to affected character file
http://pastebin.com/6PtVNxhG

**Comment by chummer5a** [comment]
Hrm. Reapply Improvements in the Special menu will fix it, but I can't see any reason for it to have dropped off. When was the character created?

**Comment by dluxcru** [comment]
Uh - last night.

**Comment by chummer5a** [comment]
Oh, right! I see why it failed. Sorry, bunch of patches between 188.3 and the current nightly. I briefly forgot to add the magical skills to mystic adepts, but it was fixed in 188.50 or something. Anyway, if you notice it on an existing character just hit reapply improvements and it'll get sorted out.
