### ISSUE TITLE
Cyberware - Liminal Body Centaur

### ISSUE THREAD

**Issue by Dreyven** [chummer5a/chummer5a#1331]
Chummer 5.188.58.0
Windows 10

### Expected behaviour
Liminal Body Centaur works like the other Liminal Bodies and allows you to add different enhancements to it as a plugin directly **and** Liminal Body Centaur contains 4 free (obvious) Cyberlegs by default (counts for 4 boxes of physical track and 2 pairs of limbs for qualities) which can then be modded  seperately (important for customization/enhancement).

The Body itself should not need to be customized and not be shown in the average calculation of the stats (it's always shown as 3 currently, but seems not included in the calculation).

### Actual behaviour
Liminal Body Centaur currently just adds the body, which cannot be modified by adding things as a plugin. 

The 4 legs have to be added seperatly, which cannot be done during character creation without paying twice in cash (you can customize essence, if enabled) as you can't add free stuff during character creation and you can't give yourself extra cash to compensate either.

**Comment by chummer5a** [comment]
Cyberlimbs don't have bracketed capacity anyway; as far as I'm aware, the body is already supposed to be treated as having the legs, so it'd just be a matter of making the customisation/enhancement work properly with averaging.

**Comment by Dreyven** [comment]
Well, then there may be a bug because it currently is not treated as if it had the legs.

- doesn't count for qualities
- doesn't add physical condition track

Overall it might be easier if it'd be possible to add 4 legs to it as a plugin by default similiar to how guns come with accessories. This allows proper modification of the legs (only 1 pair of digigrade legs, 1 pair of weaker legs, a single "combat" leg etc.).

Stupid centaur legs, why do you have to be so cool but so complicated.

**Comment by chummer5a** [comment]
As far as RAW is concerned, they don't increase condition monitors, god only knows how it's supposed to qualify for Redliner or Cyber-Singularity Seeker.

I can whack in drone limbs, but that will do.... odd things, with the current code.

**Comment by Dreyven** [comment]
[Screenshot from the Chrome Flesh Errata thread on the shadowrun forum by a freelancer](http://imgur.com/a/U9Fby)

It's a really odd piece of ware they added there but that's probably the best response we will get.

**Comment by DelnarErsike** [comment]
Already working on it since yesterday. Plan is the following:

1. Split apart the system that allows subsystems to be added to cyberware (e.g. eyeware for cybereyes) from the system that adds subsystems with cyberware (e.g. cyberlegs with a liminal body), since right now, they're kind of mixed together.
2. Create a system where cyberware can occupy more than one of a given slot, specifically so that liminal body occupies two slots.
3. Create a system where cyberware stats can be derived from subsystems, e.g. for liminal body centaur, the liminal body's 2 legs' worth of stats would be derived from its four children cyberlegs.

I currently have points 1 and 3 done on my end, and I'm in the middle of solving number 2.
