### ISSUE TITLE
Updated Chummer, Crashes

### ISSUE THREAD

**Issue by TheDefective** [chummer5a/chummer5a#1354]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Newest cant remember and cant open chummer to see
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
Chummer starts

### Actual behaviour
If started without charecter sheet reads " could not load file or assembly HtmlRenderer.WinForms"
And with a character sheet its this 
![screenshot 5](https://cloud.githubusercontent.com/assets/8505716/22179177/e243a7c8-e019-11e6-8de8-dc570e2c874c.png)

### Steps to reproduce the behaviour
Update chummer probably

### Link to affected character file
All of them

**Comment by chummer5a** [comment]
The problem is that you don't seem to have one of our library DLLs. There's an ongoing issue with people not being able to download those files from the udpater properly that I haven't figured out yet. Downloading it manually from get.chummer.net and overwriting your folder with the contents of the archive should work.

**Comment by TheDefective** [comment]
thank you i will try this

**Comment by TheDefective** [comment]
This worked thank you very much
