### ISSUE TITLE
Empty tabs and missing stuff when opening old char file with 5.190.0

### ISSUE THREAD

**Issue by Marsial76** [chummer5a/chummer5a#1394]
### Environment
Chummer Version: 5.190.0
Environment: Win 7 Prof x86
Runtime:  .NET 4.6.1)

### Expected behaviour

Opening an existing char file

### Actual behaviour

I downloaded the latest Version 5.190.0 and had a char file which worked with 5.188.3.
After opening the char file with the new version, all the info at (aug) Attributes are zero.
Other info, condition monitor and spell defence screens also show zeros.
Skills and initiation tabs are completely empty. Some Adept powers and gear is missing.

Chummer also noticed a missing book (Unknown Book SFP1) at the beginning.
This also happened in versions before but didn't cause any problems.

Please note: I usually use german text translation

### Steps to reproduce the behaviour

---

### Link to affected character file

Zip file with screenshots and char file

https://www.dropbox.com/s/ubj17y9njaf43lc/Bugnotes.zip?dl=0

![skills](https://cloud.githubusercontent.com/assets/25509042/22556422/5cfba168-e967-11e6-82d2-046443a05fe1.jpg)

![common](https://cloud.githubusercontent.com/assets/25509042/22556413/57ae7136-e967-11e6-9918-aef8a1a74501.jpg)

![book](https://cloud.githubusercontent.com/assets/25509042/22556400/4ead3da6-e967-11e6-98ba-5d3b5f65a3e2.jpg)

**Comment by DelnarErsike** [comment]
Could you try opening the file with the latest nightly build?

The SFP1 dependence is because the Living Focus power was originally not updated to its proper sourcebook (Street Grimoire or Stolen Souls).

I looked at your .chum5 file and I don't see any of your attributes as augmented, even though saved data for e.g. the total value for REA is indeed the proper value (7). Are you sure this character worked properly with Chummer 5.188.3? It looks like there was a problem saving their attributes.

**Comment by Marsial76** [comment]
It seems to work with the latest nightly build. 
And yes, I think it worked with version 5.188.3.
At least I didn't face any problems.
