### ISSUE TITLE
Chummer crash immediately after start

### ISSUE THREAD

**Issue by mdstraughan** [chummer5a/chummer5a#1431]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.190.79
Environment: Windows 10
Runtime: Latest

### Expected behaviour
Chummer runs after start

### Actual behaviour
Chummer opens (appears in task manager), creates an empty setup file, and crashes with no error window

### Steps to reproduce the behaviour
Tried two fresh installs of chummer, same problem. Curiously, crashes the same way on my windows 10 laptop.

**Comment by mdstraughan** [comment]
Also found a similar problem here, https://github.com/chummer5a/chummer5a/issues/1132

There are no MRU entries in the registry. Only the following entry.
![chummerreg](https://cloud.githubusercontent.com/assets/11242279/22872225/893fc9d8-f15b-11e6-93e8-0c7f4ba40d5c.PNG)

**Comment by chummer5a** [comment]
Yeah, this one's a bit difference. I'm not sure of the root cause as yet. I know it's something in the nightlies, but I haven't managed to figure out just where yet. I assume we're silently trapping an error, but Chummer usually fails out into the crash handler from there. If you copy a fresh nightly build over the top of a stable build, does it work at all? I had a vague suspicion it was something to do with settings not being generated properly.

**Comment by mdstraughan** [comment]
Alright stable build works! I'll try copying a nightly over it and see if it works!

By the way, thanks for everything - I'm brand new to chummer and brand new to shadowrun. Excited to get started.

**Comment by mdstraughan** [comment]
Yup, copying a nightly build over a stable build works as well.
