### ISSUE TITLE
Error finding string for key - String_Initiative

### ISSUE THREAD

**Issue by forfthemad** [chummer5a/chummer5a#1476]
### Environment
Chummer Version: 5.191
Environment: Windows 10 Home

### Expected Behavior
Initiative, Matrix Initiative (AR, Cold, Hot), and Rigging Initiative appear on right-hand-side panel

### Actual Behavior
Values for Physical/Matrix/Rigger Initiative display as "Error finding string for key - String_Initiative"

### Link to affected character file
https://www.dropbox.com/s/p1tlfha3j8l2zkt/FungZhao%2CBiowareStreetSam%20-%20CareerBackup%20-%20Copy.chum5?dl=0

**Comment by chummer5a** [comment]
I can't replicate this; the issue will be linked to your application's language file rather than anything specific to the character; could you please try one of the latest nightlies and see if that changes anything? It shouldn't, but there's a small chance the updater failed to overwrite or something.

**Comment by forfthemad** [comment]
Thank you for taking the time to address the issue. It seems like deleting the application folder and re-downloading a new stable build of chummer did the trick. Apologies for any wasted time!
