### ISSUE TITLE
Printed Magic Attribute career mode

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1599]
### Environment
Chummer Version: 5.192.0 and 5.192.32
Environment: Windows 10
Runtime:  probably .NET 4.5.1

### Expected behaviour
I expect the character sheet to show the Magic attribute printed as
 
Magic: max Magic (Current Magic) or just current Magic (as on non-augmented characters).

### Actual behaviour
The first number printed is not max Magic but another number. Not sure how it is calculated but guessing it's something with starting priority Magic. (Which should be irrelevant).

I have a magician with essence 5.8 and printed Magic: 6(5) and an adept with essence 3.95 and printed Magic: 5(2). Expected are 5(5) and 3(2). None of them has initiated. I also have an initiated magician with essence 6 and printed Magic 6. This is fine but if it followed the same pattern as augmented characters should show as Magic: 7(6). 

### Steps to reproduce the behaviour
Create a character with a Magic attribute. Get some augmentation. Save in career mode. 

### Notes
To my knowledge Chummer does all calculations correct. (Like karma costs and whatever). But it's visually bugging me. Thanks for a fantastic free resource!

**Comment by chummer5a** [comment]
The bracketed number should be your Magic attribute after taking penalties into account, including Essence loss. Internally, this is called **TotalValue**. The unbracketed number should be your Magic attribute as it would be without any penalties, which we just call the **Value**. Once you're in career mode the Value is essentially meaningless as TotalValue is used for pretty much everything, but the current code doesn't distinguish between the two modes. Since Initiation just raises the maximum of your magic, it's not a bonus that would cause the bracketing to display the total value.

**Comment by drakir75** [comment]
Why show "the Value" at all in career mode? It is as you say meaningless
and at least for me visually disturbing. Can't be hard to just not print it.

**Comment by drakir75** [comment]
Oh, I can't read. The code does not distinguish between the modes. Then I
guess it's a bit harder to do something about it.
