### ISSUE TITLE
Full Body Armour not present

### ISSUE THREAD

**Issue by rhockett94** [chummer5a/chummer5a#1604]
### Environment
Chummer Version: 5.192.34
Environment: Win10 64bit

### Expected behaviour
I can buy full body armour as per usual

### Actual behaviour
It isn't listed in the armour list. Only the helmet.

### Steps to reproduce the behaviour
Create a new character and try to purchase full body armour.

#1600 was also not fixed in cee382c

**Comment by Sturmkind** [comment]
I believe the reason you can't see Full Body Armor is because Chummer now automatically checks for availability. And as FBA's availability of 15 is over the limit of 12 at Character Creation it isn't displayed.

Should be displayed again in Career Mode or if you change max availability in the Build Method window.

**Comment by rhockett94** [comment]
This seems a bit confusing- would it be possible to have some sort of check box that shows items you don't have availability for? Like how qualities has a checkbox for only showing ones you can take?

**Comment by chummer5a** [comment]
Messy and won't play nice with stuff that has rating-based availability, but it should be working for what you want in the latest builds.
