### ISSUE TITLE
Possible Enhancements 

### ISSUE THREAD

**Issue by BodieSullivan** [chummer5a/chummer5a#163]
I was hoping to open up some discussion about enhancement ideas. I have been jotting down ideas and features that would help me out when I am using Chummer both as a player and a GM. I would like to know if others are interested in any of these ideas or have any of their own that they would like to share.
#### This is not a request for these features, merely a brainstorm/discussion.

If any of these ideas gain any traction, perhaps we can break them off as separate issues and implement them in future releases.
## Ideas

**Improved Character Display that can be used when playing the character.**
This would be something between a printed character sheet and the regular app. Basically a view that brings together the most commonly used information for a player. Since each player has different things that they do commonly, there should be some way to add custom elements to it.
- [ ] Concise skill summary so you can see all your skills at once like the printed character sheet but still in the app.
- [ ] Condition Mon
- [ ] Most common Weapons
- [ ] special stuff spells powers etc.
- [ ] Select skills/items/powers/notes to be displayed in the "in game" view 

**Edge Management Section**
This would just be something to keep track of available Edge that can be used for the player. Currently, you can burn an edge or gain edge using karma, but there isn't a way to manage game to game how much edge a player has.
- [x] Spend and Gain edge points. Perhaps something like the condition monitor but for edge.

**Cyberdeck/commlink/pan Screen**
I have wanted to add this feature for a long time. However, this would be a pretty big endeavor. 
- [ ] See all the cyberdecks/commlinks/RCC that a character has. Perhaps each one as it's own tab.
- [x] Be able to switch the attributes on cyberdecks around.
- [ ] Manage programs/agents. Add/Remove
- [ ] Store different configurations for stats and programs.
- [ ] A quick list of hacking actions with the computed dice pools would be very helpful during gameplay.
- [ ] Manage PANs by being able to slave wireless devices. 
- [ ] Store different PAN configurations.

**Advanced Vehicle Page**
I play riggers a lot and they involve a lot of intense inventory management. I am not sure the best way to implement this but would like to hear any ideas folks have.
- [ ] Designed for Riggers
- [ ] Have quick stats for driving and vehicle actions
- [ ] Better gear management
- [ ] Manage RCC, autosofts, and drones.

**Make notes section in campaign mode a html textbox**
I would love to be able to change the font size and bold text at least, but I think a control like this could be useful in other places in Chummer.
- [ ] adding formatting to the notes section would be nice. HTML would allow all kinds of neat formatting possibilities 
- [ ] Images, links, collapsable elements, etc.
- [ ] Add additional pages of notes

**Drug/Addiction management**
This is kinda tricky because most of the effects and rolls involve time to have elapsed. 
- [ ] Take drugs, get bonuses. 
- [ ] Withdrawals are taken into account.
- [ ] Handle addictions.

**Create custom things easily**
This would be a huge endeavor but I think that it would add a lot of value to Chummer. It might be a good opportunity to do some refactoring too.
- [ ] Any device, vehicle, spell, quality, etc. Anything that is stored in the XML datafiles should have a UI to add things to the datafiles.
- [ ] Some way to share that list easily. 
- [ ] Be able to use an existing item as template.

**DM Mode - [ ] view all characters , have npc/enemies/grunts**
There is a very basic stubbed out version of this that has been commented out. There is a lot that could be done here.
- [ ] A way to keep track of npcs in combat, condition monitors, basic combat dice pools (Attack, Dodge, Damage Resistance)
- [ ] handle initiative passes 

**Images for drones and vehicles and guns. More verbose notes about weapons, vehicles**
I mentioned before, I play riggers a lot. More gear details are always fun for me.
- [ ] Add any user image. 
- [ ] Perhaps an HTML textarea could be utilized here too.

**Comment by chummer5a** [comment]
Most of this actually wouldn't be that tricky to implement. 

Edge Management is basically fifteen lines added to the existing form, so that's not a problem to spin off into the condition monitor box. 

A PAN page would be relatively simple, depending on how much you wanted to do with it; you'd simply enumerate all Devices (Guns, Commlinks, etc. etc. etc.) into a treeview. Add some right-click functionality to allow promoting devices to be a master, then use drag-drop functionality to create your PANs from there. 'Decks and RCCs would need some additional functionality for handling programs and stats, but that's not beyond the pale either. Would probably also handle #136 neatly, though that should also be added to a character sheet.

Vehicle page, basically the same boat (Hurr hurr). The major issue is deciding what actually needs to go into it than anything else. 

Notes as rich text or HTML is mostly just changing the type of box, providing internal editing tools is somewhat more annoying though.

Drugs and addiction. Could be linked to an improved calendar? Set a current date which the user is prompted to enter when saving, if last-edited < current, loop through dates and prompt for expenses and such? If you have addiction tests, rent's due, etc, prompt user for results of die-rolls and then create improvements for any conditions that occur.

Custom item generator is basically just text boxes that automatically generate keys, and writing to the custom_whatever file. That should be fairly simple.

An encounter manager would be neat, but I'd be happy with just being able to open a batch of characters and update things they get as a group like contacts, nuyen or karma.

Rich data for drones and gear: Probably ties back in to the vehicles page thing, but not particularly difficult to implement. Most of the relevant code already exists.

**Comment by BodieSullivan** [comment]
Here is another something to think about... I was looking around for a rich text editor and ran across Syncfusion controls that are free for open source projects. 
http://www.syncfusion.com/sales/speciallicensingprograms#open-source-project-license

I have never used them, but it might be worth exploring...They are free to individual developers too.  I have no idea if or how they would convert to mono, if that is something that needs to be considered.

**Comment by UrsZeidler** [comment]
Maybe I borrow some usecases :) for https://github.com/UrsZeidler/shr5rcp .

Keep up the good work.

**Comment by cjrt** [comment]
I don't know if this would limit things people actually use but only allow
image enhancements on image devices, and the same for audio. At least by
default. So you don't have to scroll through ammo and ears and medkits when
choosing what to attach to your contacts.

In addition, I currently use the add as plugin option to manage my pan. So
my contacts are added to my comlink to represent it being the master. A way
to do this properly would be great!

**Comment by chummer5a** [comment]
Hrm. I wouldn't want to remove the capability, but if we just add a checkbox of 'Filter for common items' that automatically filters down to, say, modifications and ammunition for a items with the Weapon category, that could go a long way to making it more usable.

**Comment by cjrt** [comment]
Yeah that would work well. I don't know if it should be default ticked or
not? Depends which case is used more.

**Comment by cjrt** [comment]
Apply data sprite's diagnostics abilities to a gun. So that I can keep track of it?
