### ISSUE TITLE
Feature Request:  Alternate Campaigns

### ISSUE THREAD

**Issue by Reshy** [chummer5a/chummer5a#1642]
Page 350 in the Core Rule Book has rules for Alternate Campaigns, which tweak the creation rules slightly.  Is it possible to have them incorporated into Chummer onto the left-side option bar where you choose betwene Life Modules/Karma/Priority/etc. for the High Society or Street Scum starts?  Also an option for Mercenary would be good too, which triples the starting resources you get (including form karma).

![image](https://cloud.githubusercontent.com/assets/2096384/26191147/88f8f27e-3b61-11e7-9d75-1260f7a84822.png)

**Comment by luizbgomide** [comment]
Does that actually works? There is a choice of Street Scum level, but it doesn't seem to work properly.

**Comment by chummer5a** [comment]
The ones that fiddle with the values are mostly fine, but there's an issue I'm looking into with . I'm really not interested in fiddling with the priority system to accommodate Street Scum, since you can just use Sum-to-Ten for that and the automatic-switching priority comboboxes are kind of fragile. I should be able to shenanigans it to force a certain point distribution in Sum-to-X though.

**Comment by luizbgomide** [comment]
That would be better in my opinion. Since as it is now (alternative priority choices), it doesn't really work for anything...
It is supposed to be BCDEE (3+2+1+0+0) or CCDDE (2+2+1+1+0). Both sum to 6. So that is kind easy to implement. The sum to 6 would have the alternate CDDDE, but I dont see that as a problem.

**Comment by luizbgomide** [comment]
For the Good Life it would be AABCC (4+4+3+2+2) or sum to 15. The other choices would be AAABEE or ABBBC  or BBBBB.

**Comment by chummer5a** [comment]
Implemented by https://github.com/chummer5a/chummer5a/commit/971bd20d7e9f66eba77716d15589717ec8339f0e
