### ISSUE TITLE
Incorrect ess/mag calculations

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#1708]
### Environment
Chummer Version: 5.193.80
Environment: W10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
max mag = essence - essence loss + initiate grade

### Actual behaviour
http://i.imgur.com/cFV1wu1.png 

the screen is from a character with essence 3, initiate grade 2 and (before loading into the new version) mag 5.

current essence is applied as a negative modifier, meaning that 3 essence lost obliterates magic completely

### Steps to reproduce the behaviour
Create a new character with a mag rating, add some ware, observe the formula being broken.

Load a burnout, observe the broken formula

### Link to affected character file
https://drive.google.com/open?id=0B71WLpuGA0X4X1lhUjhCV1cwSTg

**Comment by chummer5a** [comment]
There's something janky here:

      <metatypemin>2</metatypemin>
      <metatypemax>6</metatypemax>
      <metatypeaugmax>6</metatypeaugmax>
      <value>8</value>
      <base>3</base>
      <karma>0</karma>
      <augmodifier>0</augmodifier>
      <totalvalue>5</totalvalue>

metatypemin/max/aug are irrelevant here, Priority modes set the metatype minimum to be higher than the standard base, so that's fine.

The problem seems to be that your attribute wasn't saving the karma charges. Also that I'm a nonce and forgot about Essence loss when amending base to not include the metatype minimum. Attached file should be fixed.

[Wannabe.zip](https://github.com/chummer5a/chummer5a/files/1064641/Wannabe.zip)

**Comment by Rinnolk** [comment]
Thanks bunches!

**Comment by chummer5a** [comment]
Yeah, I need to dig into that a bit.

**Comment by Rinnolk** [comment]
Fixed with improvements for now
