### ISSUE TITLE
Loading old (v5.191.27) character file shows wrong stats, adept power points, mentor spirit benefits, and adepts way discount

### ISSUE THREAD

**Issue by cfresquet** [chummer5a/chummer5a#1739]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.193.0
Environment: Windows 10
Runtime:  .NET 4.5.1

### Expected behaviour
character should load showing existing stats after career karma has been spent raising them
character should have 5 power points
all free adept powers from mentor spirit should be credited
Artisan's way discounts should apply

### Actual behaviour
character is loading with the base stats from character creation
character is missing a power point
voice control adept power is not free
Artisan's way discounts are missing

### Steps to reproduce the behaviour
load linked character file

### Link to affected character file & screenshots
https://drive.google.com/open?id=0B16_Tk8Lw7gnSjVHT3JDTjVxRDA

**Comment by chummer5a** [comment]
Oh excellent, it's always good to see old characters, helps to find where I've broken continuity. Let's see:

* Current nightly builds are a bit unstable with regards to attributes, but I can see the problem with the total value that's breaking your power points, I should be able to have that fixed shortly.
* Voice control didn't seem to load properly, try clicking the down arrow on the power increment, that refreshed it properly for me. 
* I removed the ability to select arbitrary powers as being discounted, it's now based on a required field which wasn't loaded properly by the power, since it didn't exist at that time. Please remove and re-add the powers that should have adept way discounts; that will fix them.

**Comment by cfresquet** [comment]
So by deleting/re-adding powers and mentor spirit I was able to get it to reset to the correct adept power point values.

However, the first item -- incorrect stats -- is still happening.
