### ISSUE TITLE
X-axis of nuyen chart is order of adding expense, not date

### ISSUE THREAD

**Issue by cjrt** [chummer5a/chummer5a#174]
* Give yourself a huge ammount of nuyen, but set the date to be before the very first expense.
* Notice that the huge spike is at the end, because it is the latest expense to be added, not at the start, which was where the data was.

Also, probably for the same reason, the distance between each point is constant. Would perhaps be nice (for people who micromanage their time in the game) to have lots of rapid transactions be close together, but ones that happen further apart to also be further apart?

**Comment by joha4270** [comment]
Fixed in 5.167

And to make you happier,  stuff close in time are close together on the graph. I would like to make the time spans logarithmic sometime in the future, as something happening over a few hours are hard to see in the span of months, but that would take more time that i wan't to spend on a rather minor feature right now
