### ISSUE TITLE
Attribute Enhancements and Other Mods Not Implemented for Vehicles and Drones

### ISSUE THREAD

**Issue by upwardthinking** [chummer5a/chummer5a#1768]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.193.0
Environment: Windows 10
Runtime: NET 4.5.1

### Expected behaviour
Vehicles and Drones are able to modded to increase any attribute except body which can only be downgraded but this option is not presented within the chummer program. The rules for this are listed in Rigger 5 on p. 123. Also pilot programs are not listed in gear and the stats for those programs are listed in Rigger 5 as well on p. 127. The drone arm mod is also missing from the gear list and can be found on p. 125 of Rigger 5.

**Comment by chummer5a** [comment]
Can't reproduce it. 

Enable **Use Drone Modification Rules** on the Optional Rules tab of the Options menu. The modifications list will then show modifications with the (Drone) tag if you're modifying a drone, since vehicles don't have access to those mods. 

Pilot is treated as a modification the same as other modifications, so it's not a gear item. 
Drone arm is a modification.
