### ISSUE TITLE
Saved character loading incorrectly in latest build

### ISSUE THREAD

**Issue by cfresquet** [chummer5a/chummer5a#1802]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.193.0.0 (built from latest source)
Environment: Win 10
Runtime:  .NET 4.5.1

### Expected behaviour
Prototype Transhuman working
Raven mentor spirit gives free adept powers Traceless Walk and Voice Control

### Actual behaviour
Prototype Transhuman essence credit is not applied, resulting in a magic score of 4 instead of 5
Raven mentor spirit is only giving credit for Traceless Walk, Voice Control is not free.

### Steps to reproduce the behaviour
load the character

### Link to affected character file
https://drive.google.com/open?id=0B16_Tk8Lw7gna3Z0UDd1Y2JVVTg

**Comment by cfresquet** [comment]
I see that there is a checkbox "Prototype Transhuman" when adding new bioware. However, deleting the bioware she has and re-entering it using this checkbox doesn't change anything.

**Comment by GearheadLydia** [comment]
Note that there was a commit a few versions back (5.193.110 or thereabouts?) that modified how Prototype Transhuman works. The build notes specifically said that existing characters would have to be ported manually.

**Comment by chummer5a** [comment]
Odd, you shouldn't have been able to see the checkbox for that in career mode. It's only supposed to be available in create. Anyway, the easy fix is to save the file in the newest version and open it up in notepad, then alter the appropriate entries of the PrototypeTranshuman flag on each bit of bioware to be True instead of False. 
[Echo - Career.zip](https://github.com/chummer5a/chummer5a/files/1150263/Echo.-.Career.zip)

**Comment by chummer5a** [comment]
As for Raven, it should be working in current builds. Try using the Swap Quality button on the Mentor Spirit quality to reselect it.
