### ISSUE TITLE
Slow, unstable behavior likely related to MAG changes, Essence calculations, and Biocompatibility

### ISSUE THREAD

**Issue by GearheadLydia** [chummer5a/chummer5a#1803]
### Environment
Chummer Version: 5.193.149; problem is as old as 5.193.120
Environment: Windows 7 SP1 64-bit
Runtime: .NET 4.5.1 (presumed)

### Expected behaviour
Going to the Skills page, and then altering the MAG attribute, should behave relatively smoothly and crisply like on 5.190.

### Actual behaviour
Going to the Skills page, and then going back to the Common page and increasing MAG by one point, results in the program freezing for approximately 10-15 seconds, and additionally crashing if disturbed.

### Steps to reproduce the behaviour
Loaded a particular character created in 5.190.0 in 5.193.149; went to the Skills page; returned to the Common page; increased MAG by one point.

Problem persists even if I save the character in 5.193.149. I suspect Essence cost recalculation is the problem: the problem persists under most conditions, but disappeared when the character was re-saved in 5.190.0 with all Bioware removed. Also worth noting: the character in question has Biocompatibility.

EDIT: Deleting the Biocompatibility quality also causes the lag, as does adding it back in afterward.

### Link to affected character file
[Essence MAG Calculation Issue.zip](https://github.com/chummer5a/chummer5a/files/1150172/Essence.MAG.Calculation.Issue.zip)

**Comment by Xenryusho** [comment]
Can you confirm whether or not you get the same lag when changing other attributes such as BOD? I'm getting it for pretty much anything that forces a form change on the common page including nuyen or even attempting to raise something higher than the allowed maximum (reaction for instance where it stops me from doing it altogether). 

Looks to me like there's a massive inefficiency in ForceAttributePropertyChangedNotificationAll (upwards of 20k+ ms) when called from clsImprovement.RemoveImprovements (because there is essence lost, I removed biocompatibility and was still able to get this problem, so likely biocompatibilities only involvement is that it forces the form to update). 

It's trying to update every skill on the skill page which goes through a ton of calls everytime a improvement is an attribute improvement (in this case magic loss and then a second time for resonance loss).

**Comment by GearheadLydia** [comment]
Confirmed on my end: There is a slight lag when increasing BOD, and a major lag (on the order of what I had noticed earlier) when decreasing it.

**Comment by chummer5a** [comment]
Oof, yep. That's going to need some attention.

**Comment by chummer5a** [comment]
Should be a smidgeon better now, it's slow to update all the fields but isn't choking performance while it does it. It'll need a proper performance analysis and rebuild to be better, but it's functional again.

**Comment by Xenryusho** [comment]
Can confirm drastically reduced lag (from elements like nuyen having virtually none to roughly 4.5k on changing attributes like body).
