### ISSUE TITLE
Print option "Shadowrun 5(Grouped Skills by Rating)" not working

### ISSUE THREAD

**Issue by cfresquet** [chummer5a/chummer5a#1835]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: latest build from source
Environment: Win10
Runtime:  .NET 4.5.1

### Expected behaviour
print option should work as it did previously to categorize skills

### Actual behaviour
Prints a list of all skills, with many skills repeated several times.

### Steps to reproduce the behaviour
load character, print, select character sheet

### Link to affected character file
https://drive.google.com/open?id=0B16_Tk8Lw7gneWhKYlFINnpIeHc

**Comment by chummer5a** [comment]
The character seems to have the skills listed multiple times, that'd be the problem.

**Comment by Lochabar** [comment]
Just tried the character using 5.193.191 and I do not see any duplicated skills

![skills by rating](https://user-images.githubusercontent.com/17562417/28796626-e2780d4e-7603-11e7-8fb2-1ca908012490.png)

**Comment by Surukai** [comment]
The bug is still there though, the skills no longer "Group" by category. Previously Grouped Skills put "Physical active skills" in one list, Technical Active skills in the next, Social in the third and so on, not all skills in just alphabetical order.

**Comment by cfresquet** [comment]
Grouped skills used to look like this:


![grouped](https://user-images.githubusercontent.com/13633603/29185457-234104ea-7dbe-11e7-8f09-9fe1aed520c0.jpg)

**Comment by Lochabar** [comment]
There has been a change to XML file - "skillcategory" (as opposed to "skillcategory_english") is blank in the latest releases. The skills by rating sheet uses "skillcategory" for grouping.

Release 193.0
![193 0](https://user-images.githubusercontent.com/17562417/29222764-7a937d42-7e89-11e7-8cf6-278d00599671.png)

Nightly 193.199
![193 199](https://user-images.githubusercontent.com/17562417/29222774-87f64e24-7e89-11e7-90b4-9b5983103790.png)

Is the intention that "skillcategory_english" should be used (and so the xsl sheets need changing)?
Or should "skillcategory" actually be populated?

**Comment by chummer5a** [comment]
SkillCategory should be the DisplayName of the category, which should fail back to the actual Name. SkillCategory_English is the actual Name of the category, which will always exist.

**Comment by Lochabar** [comment]
This is the entry for Alchemy
![alchemy](https://user-images.githubusercontent.com/17562417/29242067-9ba9b826-7f4b-11e7-9dd3-9693c6c1f813.png)

You are saying that because "skillcategory" is blank it falls back to the _name_, i.e. "Alchemy". Therefore "Alchemy" would be listed under a skill group entry of "Alchemy Skills" not "Magical Active Skills". Did you actually mean it should fall back to "skillcategory_english"?

I checked a German file and "skillcategory" looks like it present and translated.
Will this always be situation for non-English files?
If so then "skillcategory" may be blank only in English files?

This suggests the code populates "skillcategory" only when it not the same as "skillcategory_english"?

This complicates the sorting, and will only be applicable for English files.
How difficult would it be to always populate "skillcategory" ?
Not just when it differs from "skillcategory_english".

**Comment by chummer5a** [comment]
Should behave properly now in the latest commit, next build is scheduled for 0000 UTC.
