### ISSUE TITLE
Effects of drugs

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1858]
### Environment
Chummer Version: 5.193.0
Environment: Windows 10
Runtime: probably .NET 4.5.1)

### Expected behaviour
Not a bug, more of an enhancement wish.
A simple way "take drugs" and to get the effects of drugs.

### Actual behaviour
Only way is removing drug and either remember the effect or go change manually in improvements. (Not that good for temporary effects)

### Thanks
Thanks for your work on this Very useful Character generator that keeps getting better and better.

**Comment by chummer5a** [comment]
It's scheduled to be done along with the custom drugs from Chrome Flesh, but I don't have an ETA for when that'll be ready. Theoretically doesn't need a huge amount of work, just need to decide how to best present the data without things getting lost or left on forever.

**Comment by FableWright** [comment]
Is this something you've done some development on? I'm extremely new to community development on git, and have no familiarity with this project's backend (at the moment I don't know how to get Visual Studio to recognize any of your custom types), but I have some ideas on how drug effects could be implemented, if it's not conflicting with existing work.

[In short, there's a good amount of space on Common tab under 'Metatype: {X} \nSource: {X} next to attributes in Career Mode; your 'Street Gear -> Weapons' tab already shows a backend to grab items by type; and the [+]/[ - ] from Edge to could show up next to the drugs to apply/remove the boosts. 

Because the drugs are presented next to the attribute boosts, it's easy to turn them off; and the color of the red/green draws attention to add as a reminder to turn them off when required.]

**Comment by chummer5a** [comment]
I haven't touched it at all yet personally, don't think anyone else is doing anything with it. My vague plan was to have consumables add an object somewhere in the UI that you would then toggle off and on; each toggled activation would consume one of the gear items, similar to how it works with ammo.

**Comment by mwberlindeu** [comment]
Similar issue: https://github.com/chummer5a/chummer5a/issues/3276

I am willing to code such an enhancement (but I will need some time...).

**Comment by chummer5a** [comment]
Completed in heisenberg branch, scheduled for integration into main branch.
