### ISSUE TITLE
Sections of skills window cut off

### ISSUE THREAD

**Issue by AgentA1cr** [chummer5a/chummer5a#1900]
### Environment
Chummer Version: 5.195
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

My friends are experiencing the same issue. (If it's important, I have the program installed on a flash drive.)

### Expected behaviour
Display skill window properly.

### Actual behaviour
![chummer glitch](https://user-images.githubusercontent.com/18541327/30191933-2e90dd1a-9412-11e7-95ff-180972ed5757.PNG)
Sections of the skills window are cut off and cannot be resized or adjusted.

### Steps to reproduce the behaviour
Create character, Access skills page

**Comment by chummer5a** [comment]
Unfortunately Chummer doesn't play very well with altered DPI settings, so your increased text size causes it to get cut off.

**Comment by Taschenmogul** [comment]
I got the same issue and I'd like to add:
The last build that worked for me was 175, though I haven't tried all of them out.
I tried 180 and 181, which just crash when opening the "skills" tab, 183, which still shows the skills without cutting them off but shows skill groups as being unselectable, and finally build 184, where the cutting off of text appears. So I guess this behaviour is due to a change somewhere during the transition from build 183 to 184.

**Comment by chummer5a** [comment]
I'm having trouble replicating this in my dev environment; what are the specific resolution/scaling settings you're using? I suspect this is a Windows 7-specific error, do you have access to a windows 10 device to test it on with the same configuration?

**Comment by atma288** [comment]
win 7; landscape resolution: 1920x1080; portrait monitor 1080*1920; scaling: 'maintain display scaling'

**Comment by atma288** [comment]
attempted to adjust resolution to various settings, no change; attempted to change scaling, no change. 

opened on win10 without modifying defaults of any kind, displays as expected. seems that there is a win7 compatibility issue.

**Comment by ThisIsLouie** [comment]
I've had this issue using Windows 10. 

I typically use a 125-150% DPI scaling in my Display settings due to poor eye sight (that's in addition to personal corrective lenses). Setting the DPI to 100% re-frames the Skills Tab properly, but then I'm back to the too tiny text syndrome. 

As was mentioned by another user in a different thread, changing the settings under the compatibility tab in the application's properties dose not resolve this issue, at least in my windows 10. Even if it did scale the DPI back down to 100%, the text would be a challenge to read. 

I was wondering if there was a way to place the Skill Groups into it's own window frame that could then be resized and scrolled?

My Windows specs are:
Windows 10 Home Edition
Version 1709
OS Build 16299.192

**Comment by chummer5a** [comment]
Can't replicate these issues in the current builds for Windows 10, though Windows 7 is likely still an issue. Can you confirm whether it's still an issue on your end?

**Comment by ReallyDarkMatter** [comment]
I had a Problem that Looks nearly the same.
Right after the loading of a char it Looks like this


![skills right after loading](https://user-images.githubusercontent.com/12108972/42136802-47e4e074-7d62-11e8-958a-020db7f498c9.JPG)

Then i move the divider on the Right side of the skills tab to the left

![skills after moving the divider](https://user-images.githubusercontent.com/12108972/42136821-7ca51752-7d62-11e8-89c4-12216a413358.JPG)

And everything is readable again

**Comment by ThisIsLouie** [comment]
I'll try that fix. Thank you for the response.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
