### ISSUE TITLE
Feature Request: Discounted Technomancer Echoes, Echoes without Initiation

### ISSUE THREAD

**Issue by Megapulse** [chummer5a/chummer5a#1920]
- [ ]  Technomancers can buy echoes at 15 karma an echo not exceeding their max resonance
- [ ]  Technomancers wanting to buy programs as an example of an echo only costs 5 karma instead of the normal 15

**Comment by chummer5a** [comment]
The technomancer houserule would need code support to decouple echoes from your initiate grade and provide the karma discount for program echoes.

**Comment by Megapulse** [comment]
so what your saying is it cant be done on my end :P

**Comment by Megapulse** [comment]
how was the initiative improvement fixed? I still cant seem to add +d6's to initiative

**Comment by chummer5a** [comment]
Not included in the latest nightly, I committed it after the nightly build was scheduled. If you save [this file](https://raw.githubusercontent.com/chummer5a/chummer5a/faa0ff34ee1a9ff61a3ae9ceef355a5e713f6949/Chummer/data/improvements.xml) to your Data folder, it should start showing Initiative Dice instead of Initiative Passes.

**Comment by DelnarErsike** [comment]
Both of these features can now be implemented using the `addecho` and `selectecho` bonus nodes. Create a custom quality (or amend or override an existing one), set appropriate karma costs, set up the correct bonus nodes, and you're good.
