### ISSUE TITLE
Skills + Attribute Enhancement

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1928]
### Environment
Chummer Version: 5.195.0
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Wanted behaviour
To be able to choose the attribute associated with a skill. Oftentimes it's a different attribute that's most often used for a skill for a certain PC. 

Examples: 
Computer (matrix search and perception) uses only Intuition for everyone except deckers/technomancers.
Arcana is used for initiation (for some, the most common use). Then it uses Intuition.
Pilot and Gunnery changes attributes when in VR. (Some riggers (and others) are "always" jumped in.
Magicians that mostly uses certain skills in the astral uses astral attributes.

Then there are GM-specific changes like using Strength for Intimidation and/or Close combat.

### Actual behaviour
Frustrating to always have to recalculate your most common dicepool for some skills.

### Thanks
Thanks for a fantastic character generator!

**Comment by chummer5a** [comment]
Already implemented, just click on the attribute and you'll get a dropdown with the attributes. It currently doesn't regenerate the tooltip since that's bound up against the skill itself instead of the control, but that's fixable.

**Comment by holgerschlegel** [comment]
Would be nice to be able to show/print a skill multiple times with different attributes. Some form of "virtual skill" because its still only one skill with one rating.

For example, the skill acrobatics is by default associated with AGI but uses STR for climbing.
And both variants are used for the same character.
One problem here is that there is also a specialization for climbing. Which, of course, only applies to the skill variant based on STR.

Not sure if this is possible at all, but would be nice anyway ...

**Comment by drakir75** [comment]
I'm not seeing the "already implemented". Still can't change attribute. (or I am not understanding.) Holgerschlegel has a good idea. That would be nice to have as an option.

**Comment by chummer5a** [comment]
This works now, but has an issue with it not refreshing the dicepool when the attribute is changed.
