### ISSUE TITLE
Essence, biocompat and adapsin.

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#1941]
### Environment
Chummer Version: 5.195.31
Environment: w10
Runtime:  it is probably .NET 4.5.1

### Expected behaviour
Correct essence calculations. 

### Actual behaviour
Not quite correct essence calculations.

### Steps to reproduce the behaviour
Add biocompat, observe essence costs, add adapsin, observe essence costs. Combine both for cyberware and check the math. 

Now, the crunch.

Biocompatibility 'stacks' with ware grades and ends up pretty much a .1 subtraction from the grade multiplier.
http://i.imgur.com/wI7lFJ5.png
http://forums.shadowruntabletop.com/index.php?topic=21061.90
http://i.imgur.com/z7GtoXh.png

Seems correctly applied as far as I can tell. Used arm ends up being 1.15 ess with biocompat, alpha arm with biocompat becomes 0.7 ess.

Now cue adapsin. 
https://i.imgur.com/QvEARkf.png

Doesn't explicitly interact with ware grades beyond not conflicting with them ("in addition to..." rather than "combines with" or something similar)

Instead it simply "...reduces the Essence cost of implanting cyberware... by ten percent (round down)" 

Round down is moot since it doesn't specify what it's supposed to be rounded down to. 

The essence savings are a flat 10% though, which works out to 
      (base cost*grade multiplier) - 10% for no biocomp
or
      (base cost*(grade multiplier-0.1)) - 10% for biocomp

thus an alpha arm with adapsin biocompatibility should be (1*(0.8-0.1))-10%=0.63. (0.6 in current chummer)

A used arm with adapsin and biocomp shoud be (1*(1.25-0.1))-10%=1.035 (1.025 in current chummer)

Chummer considers adapsin another instance of biocompatibility, which doesn't seem to be the case raw?

If this formula doesn't reflect your interpretation of raw, can we get it as a house rule? Please? :v

*Bonus content*

If we don't simplify biocompat to a flat .1 improvement to the grade multiplier, it gets tricky with used grade.
Going strictly by raw, the multiplier will be 1.25-10%, rounded down to 1/10th, coming out to a 1.1 multiplier.

Used arm with adapsin and biocomp will then be (1*1.1)-10%, or .99 ess.

Whether it's worth going this precise and close to raw I can't say. Not really worth complicating (?) the formula for me personally, but is ultimately the proper math according to raw.

**Comment by DelnarErsike** [comment]
The next nightly version (after I am writing this) will not change Adapsin, but it will add bonuses that will let you amend it to behave in the way you'd want it to.

After the next nightly version is out, download the file below and unzip it somewhere where you'd want to keep your house rules. I'd recommend the customdata folder within the main Chummer5 directory. Then, go into Options > Optional Rules, add the folder that you unzipped as a custom data directory, enable it, press OK, and let Chummer restart. Adapsin should behave the way you want it to while that custom data directory is enabled. If you're using another set of house rules that also modifies Adapsin, be sure to have your load order set up so that your houserule is loaded last so that its changes will always be applied.

[Rinnolk Adapsin Houserule.zip](https://github.com/chummer5a/chummer5a/files/1360588/Rinnolk.Adapsin.Houserule.zip)

**Comment by Rinnolk** [comment]
Yeah, that works as a solution. Thanks!

Just trying to equalize HL and chummer sams, as well as accomodate a ruling on the things on Shadownet.

**Comment by chummer5a** [comment]
Did we change something with Essence calculation of 'ware? Unless I'm mistaken, that Adapsin bonus will apply to all cyberware retroactively, which was why we used the modified grades to implement it.

**Comment by DelnarErsike** [comment]
Essence costs are stored within the piece of cyberware after selection, so that Adapsin bonus shouldn't apply retroactively (if it does, it'd be a bug that would need fixing).

Via the Adapsin grades, the current version of Chummer5 has Adapsin apply multiplicatively to grade *before* the additively-stacking essence modifiers are taken into account. That file makes it so that Adapsin is applied multiplicatively *after* the additively-stacking essence modifiers are factored in.

**Comment by chummer5a** [comment]
Hrm, nope. We still use the base _strESS and build up from there in CalculatedESS(), including redoing the improvements. 

If we could just get clarification that -10% == -0.1 Grade ESS Multiplier this would all be much simpler.

**Comment by Rinnolk** [comment]
A chrome flesh errata would be real nice. But alas. 
This is how the raw is interpreted on Shadownet, and also how HL calcs essence. 

Works excellently. Except when doing "reapply improvements" on existing characters with adapsin. Even if some ware is removed to create an essence hole, the after fix ware doesn't fill the hole first, resulting in further loss of essence. 

Haven't found a workaround to that. But the only character affected for me was a 6 karma sam, so wasn't a big deal to rebuild.

**Comment by DelnarErsike** [comment]
Next nightly version will include an updated version of the houserule in its CustomData folder. This version makes sure Adapsin is never applied retroactively, meaning only cyberware added after the house rule is applied and after Adapsin is applied will have its essence modified.

Since I can't really include "legacy sweeps" for house rules, you'll want to use the old file for characters you've already made who have Adapsin, and the new one for all new characters.

**Comment by Rinnolk** [comment]
Guess I'll hold off going out of gen for a bit then :v 

Unless I misunderstood and it's not going to be a problem with an at-gen adapsin?

**Comment by DelnarErsike** [comment]
Definitely will be a problem with at-gen adapsin. If you aren't using the rule from the next nightly version (5.195.36), then the instant you take any cyberware while you have Adapsin enabled, it won't properly save the nonretroactive cyberware essence multiplier alongside the piece of cyberware (because that's the point of Adapsin not being retroactive).

**Comment by Rinnolk** [comment]
Ah.... thanks for the heads up. 

... I think I won't have to re-add all ware? :v Small issue either way >_>

**Comment by chummer5a** [comment]
Should be working correctly in current builds,
