### ISSUE TITLE
 Issue: - Tryna open my buddies build and crashed

### ISSUE THREAD

**Issue by Asynd** [chummer5a/chummer5a#1950]
### Environment
Crash ID: a866be47-0e59-48ae-8365-68c48619af2f
Chummer Version: 5.195.0
Environment: Windows 7 Professional
Runtime: 4.0.30319.42000

### Expected behaviour
lemme see the character

### Actual behaviour
aint see shit

### Steps to reproduce the behaviour
open up the character sheet
[chummer_crash_131520312782264000.txt](https://github.com/chummer5a/chummer5a/files/1368726/chummer_crash_131520312782264000.txt)

**Comment by DelnarErsike** [comment]
You've got to be more specific if you want us to fix shit.

When exactly did the crash occur? Does the character open properly in the latest stable version (not the nightly one)? Could you give us the character file?

**Comment by Asynd** [comment]
Nigga i just downloaded the bitch and tried to open the shit and get the crash report nigger but that bitch crashed too

**Comment by DelnarErsike** [comment]
SMH, download the stable version (5.194) and not the nightly one (5.195), and see if it crashes there, too. Nightlies are called "nightly" for a reason, the code in that version changes every night.

**Comment by khokkanen** [comment]
Trying to open this character with the latest few versions of Chummer crash it, producing an error (crash data here: https://www.dropbox.com/s/3i73rywmqdr8jpq/chummer_crash_131522933431088860.zip?dl=0).

I'll check the latest working Nightly.
[Blade Tank.zip](https://github.com/chummer5a/chummer5a/files/1379687/Blade.Tank.zip)

**Comment by DelnarErsike** [comment]
The issue is that you don't have the data filed enabled that adds Radar Sensor as an actual sensor function (instead of it being restricted to cyberware). Some older versions of Chummer had Radar Sensor as a sensor function, but this was patched in a later version, so you will have to copy the "custom_radarsensorfunction_gear.xml" file from [Chummer5 folder]/Custom Content/ into [Chummer5 folder]/data/, or get the file enabled via custom data directory.

I'm applying a patch-over fix for the next Nightly that actually prevents a crash if you haven't got the proper files loaded, but please make sure you do in the future, even if Chummer5 won't end up crashing.
