### ISSUE TITLE
Quality: Ex Con

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#202]
Should probably have a handler to hide augmentations with Restricted or Forbidden codes. Other than that, relatively uninteresting as far as Chummer code goes.

**Comment by joha4270** [comment]
Hardcoded on/off switch working on local branch, will search for the sane way of checking for ex con tomorrow.

Doesn't give automaticaly give criminal sin yet but if there is an easy, sane way to implement i will
Parole officer information will just be a note unless there is a strong wish for it behaving otherwise

**Comment by chummer5a** [comment]
I've been meaning to post something about how to do that in the code, if only to sort it all out in my head. It's basically all stored in clsCharacter. If you look for SchoolofHardKnocks throughout the project you should see basically all of the code you need to add.

**Comment by joha4270** [comment]
Exams are happening so my progress haven't been big but i have run into a few questions.

Right now when you add Ex-Con to qualities it removes everything with an R or an F in the rating, then, afterwards it dosen't display those in select ware dialogs. 

Now the questions.
Instead of hiding/removing is it better to just prevent the character from being marked as created?

What to do when the quality are added during play? Restrict new ware? Remove old ware (with/out) refunds? Nothing? 


As for progress i have a bug with updating the display that is identified and reproducible but not fixed. Adding the quality works otherwise. No QA for when loading/saving sheets or career mode.

**Comment by chummer5a** [comment]
Generally speaking during chargen it's best to leave validation for the final step of character creation. The player may decide to remove the quality later, or may be ignoring chargen rules. Once we're in career mode we can adhere more closely to the rules, so at that point we'd remove all old 'ware automatically (Note: This also needs to add the Essence Hole cyberware, I haven't sorted out a nice method of handling that yet). Strictly speaking there's nothing stopping an ex-con from getting NEW cyberware that violates his conditions, so restricting the gear shouldn't be necessary.

**Comment by joha4270** [comment]
Great, i just think i have to throw out most of my progress :D
Atleast i learned a lot about chummer internals (still nowhere near proficient tho ;) 

Only question is, is it wise to remove ware when added during career? That can be a lot of nuyen worth of stuff. Dialog box maybe?

**Comment by chummer5a** [comment]
Honestly I spent most of my first month working on Chummer just panicking
and tugging on threads to see what they did. Once you wrap your head around
it it's fine, just gotta learn where everything is. Adding an 'are you
sure' prompt shouldn't be particularly difficult, I suppose.  if
(character.career && quality.name =Ex-Con){Messagebox}, if message box
returns no, return to the menu.

**Comment by joha4270** [comment]
I can attest that the message box should not be hard to implement, as i had
to write a few lines of code to hide it in my current implementation :D
Okay, mine is in ware deletion code but msgbox is nonetheless not the
hardest piece of programming i have come across



2015-05-15 10:44 GMT+02:00 Chummer 5 Is Alive <notifications@github.com>:

> Honestly I spent most of my first month working on Chummer just panicking
> and tugging on threads to see what they did. Once you wrap your head around
> it it's fine, just gotta learn where everything is. Adding an 'are you
> sure' prompt shouldn't be particularly difficult, I suppose. if
> (character.career && quality.name =Ex-Con){Messagebox}, if message box
> returns no, return to the menu.
>

**Comment by joha4270** [comment]
Works for chargen 
pull request #213

**Comment by joha4270** [comment]
Merged into main branch in #213, does nothing in Career mode as lack of undo is potentinaly nasty
