### ISSUE TITLE
Category Name not showing in skills section of appropriate character sheets

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2021]
### Environment
Chummer Version: 5.195.61 (and earlier)
Environment: Windows 7 home edition
Runtime: (probably .NET 4.5.1)

### Expected behaviour
The character sheets "Shadowrun 5 (Grouped skills by name)" and "Shadowrun 5 (Rating > 0)" show skills listed in alphabetical order within Category Name.
 
### Actual behaviour
The skills are listed in alphabetical order within Category Name but the Category Name is not shown. And so the skills are seemingly out of order.
![skills list without category names](https://user-images.githubusercontent.com/17562417/32391343-a930c9ae-c09f-11e7-9503-c51cce9f09a2.png)

#### Variable "PrintSkillCategoryNames"
The most recent changes to the character sheets (for #1986) for the skills list introduced a new global variable  "PrintSkillCategoryNames" controling the printing of the Skill Category name in the skills section of the character sheet.

This variable is set to "False" in each of the five "Shadowrun 5 ..." .xsl files (the actual character sheets) for each supported language. The variable is never to "true()". This means that the "Shadowrun 5 (Grouped Skills by Name).xsl" and "Shadowrun 5 (Rating greater 0).xsl" print the skills list without any headings, printing the skills seemingly out of order.

I made the following changes:
1) Defined "PrintSkillCategoryNames" (a local version) in "Shadowrun 5 set.xslt", setting it  to false().
2) Changed the setting of the global version of "PrintSkillCategoryNames" to true() in "Shadowrun 5 (Grouped Skills by Name).xsl" and "Shadowrun 5 (Rating greater 0).xsl" - ALL languages.
3) Removed the setting of "PrintSkillCategoryNames" from the other three "Shadowrun 5 ..." .xsl files - ALL languages.

#### File "xt.Skills.xslt"
1) The template "skillgroups" from "xt.SkillGroups.xslt" is used by all the "Shadowrun 5..." character sheets. I moved it into "xt.Skills.xslt".
2) In "xt.skills.xslt" I added a template "categoryname" to print the Skill Category name as needed.
3) Removed the printing of Skill Category name from "xs.SkillsGroupedAssorted", "xs.SkillsGroupedByName" and "xs.SkillsGroupedByRating" (the code was present twice in each member)
4) In "xs.SkillsGroupedAssorted" and "xs.SkillsGroupedByName" I added a call to the "categoryname" template. (This call is not needed  in "xs.SkillsGroupedAssorted".) In addition I removed the include of "xt.SkillGroups.xslt" from these members.

#### File "xt.SkillGroups.xslt"
This should be deleted.

#### Variable "lang.SkillGroups"
Variable lang.SkillGroups is only set in the default version of "xz.language.xslt". I have added it to the de/fr/jp/zh versions.

### Attachments
This zip file contains just the files that have been changed.
[sheets.zip](https://github.com/chummer5a/chummer5a/files/1442289/sheets.zip)

Remember: delete "xt.SkillGroups.xslt"

**Comment by DelnarErsike** [comment]
I closed the issue because it's fixed in my latest commit, but because I didn't use your changes, I thought I'd comment.

It was fully intentional to have the printing of skill categories be toggleable with a variable, and keeping skill groups in their separate template makes things a bit easier for modularity. What wasn't intentional was that skills would still get sorted by skill category even if skill categories weren't being displayed, and fixing that would end up fixing the "skills are displayed in an arbitrary order" problem without removing the functionality of toggleable skill category displays.

Thanks for the heads-up about the SkillGroups variable, and about the skill category printing variable misbehaving, those I did address directly in the latest commit.

In the future, if you feel like contributing to Chummer5, it's much easier for us to integrate changes if you submit them as a pull request than if you upload an archive of files. For one, a pull request allows us to quickly and immediately make side-by-side comparisons between old and new content, which helps us better judge the changes.

**Comment by Lochabar** [comment]
The reason I removed the setting of "PrintSkillCategoryNames" from "Shadowrun 5" and "Shadowrun 5 (Core).xsl" is that these process the skills list in skill name order. If you set "PrintSkillCategoryNames" to true() in either of these the skills are printed in the wrong categories.
![shadowrun 5 skills list](https://user-images.githubusercontent.com/17562417/32409260-6ac18aaa-c176-11e7-8f83-d6f712c8f7e4.png)

You can see, amongst others, that:
Etiquette is listed in Technically Active instead of Social Active
Negotiation is listed Vehicle Active instead of Social Active

I still feel that the setting of "PrintSkillCategoryNames" should be removed from "Shadowrun 5" and "Shadowrun 5 (Core)". And the default for the others should be to set it to true().

**Comment by Lochabar** [comment]
In addition the original 5 "Shadowrun 5 ..." character sheets are present in each of the foreign language folders de/fr/jp/zh. Any changes to the English (default) versions of character sheets need to be copied forward to the other language versions [another reason I suggest pulling "PrintSkillCategoryNames" from "Shadowrun 5" and "Shadowrun 5 (Core)" - less changes to copy forward].

The new versions of character sheets should also be added to the foreign language folders.
