### ISSUE TITLE
Feature: PACKs

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#203]
Functionality's all in there, just need to go through and add in all the data. Slow work, but reasonably easy. 

http://www.chummergen.com/chummer/wiki/Data-File-Overview-sr5.ashx provides an overview of the naming conventions required.

**Comment by BlackGaze** [comment]
Hi, I'm a big fan of Chummer and would like to help. Sadly i have no knolwdge abaut programming. So if there is something simple enough for me learn, i'd be happy to help.

**Comment by joha4270** [comment]
That should be possible. As this post details, chummer have so called PACKs kits that is a collection of gear, spells. attributes, qualities and cyberware that each facilitates a runner to do one thing.

One such package might be "getting your feets wet" that contains an Ares Predator V, 100 rounds of ammo, a comlink, and a rating 4 sin. 

It might be everything you need to be a baddass mage or it might be a wholly other thing. Run Faster have some and otherwise the old chummer4 had a lot of them if you need the inspiration.

Each of those are defined in packs.xml and you can find documentation on how that format looks here http://www.chummergen.com/chummer/wiki/packs-xml-sr5.ashx 

For how xml looks in general, go find somewhere on the internet. It is dead simple but there is no reason for me to detail what is already explained 100000 other places. 

Now lets talk a little about how github works. See up in the right upper corner where it says "fork"? Click that button. That will make a copy of chummer5a under your account that you have full edit privileges to. (How to edit: look at git if you want the powerful way or if you want the easy way, look up sourcetree). 
Once you have created something amazing and chummer now have some fantastic gear kits (that you tested of course :D) you can now create a pull request for this repo. Doing that, you asks 
![image](https://cloud.githubusercontent.com/assets/4454884/7669696/d4318542-fc81-11e4-9021-77073ef87770.png) to integrate your changes into chummer. 

Good luck and feel free to ask questions, either here or to email me (and i'm sure the other guy doesn't mind either)

**Comment by chummer5a** [comment]
Aside from that, Chummer also has a feature built in that enables the automatic creation of custom PACKs in the application itself. If you make a character, add the relevant gear for a PACK, then open the Special menu and select Create PACKs kit, you'll be prompted to enter the name of the kit, and select the types of gear that should be added. I've done everything up to the Heavy Security kit so far:

http://pastebin.com/NDzkyVGn

**Comment by joha4270** [comment]
So close it might as well be closed
