### ISSUE TITLE
Slide mounts and "unallocated" accessories

### ISSUE THREAD

**Issue by oxford-fumble** [chummer5a/chummer5a#2040]
### Environment
Chummer Version: 5.195
Environment: Win 7
Runtime: .NET 4.6.1

### Problem Definition

Currently, one can add one or several slide mounts to a weapon, but cannot add any "unallocated" weapon accessories that can then be swapped between slide-mounted weapons.
It is also impossible to nest an accessory under a slide mount, which makes the slide mount modification useless.

For example, if I select slide mounts for top and side for my Ares Alpha AND my HK227, I am not able to buy a lamp torch, improved laser rangefinder and / or magnification scope independently, so I can 
swap them between the Alpha and HK227.

Also, I cannot allocate the magnification scope to a slide mount, as Chummer considers the mount is already "taken".

### Feature request

It would be great to be able to cater to the 2 following scenario:
- [ ] Accessories should be purchasable independently of a weapon. May be necessary to revive the distinction between mods and accessories to accommodate this, as modifications can't be moved between weapons.
- [ ] Non-integral accessories should be detachable from a weapon. 
- [ ] Slide Mounts should allow other attachments to be attached onto them. 

Thanks for looking.

**Comment by chummer5a** [comment]
When interacting with the tree-view for a weapon, we should be able to differentiate between a weapon and (non-)mountable accessory location. If the currently selected node can't have something mounted on it, the accessory should flow up to the parent weapon, prompting for a mount point as necessary. For example, right-click dragging a sight over a silencer accessory node should attach the sight to the weapon rather than the silencer, provided the weapon has a slot free for the sight. I expect that this will take some logical additions to the treeviewhelper class, likely by parsing the id of the selected object and the id of the object being hovered over to determine whether it should be permitted to drop it. 

Nice-to-have would be some form of visual indicator if the item can't be dropped on that node like a red X icon or somesuch.

We'll also need a container for the unmounted accessories for save/load purposes, though this can likely just be added to the character node.

**Comment by chummer5a** [comment]
Duplicates #3469
