### ISSUE TITLE
Error window opening character in create mode

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2058]
### Environment
Chummer Version: Nightly-v5.195.71
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Open character without error

### Actual behaviour
Open character created in 5.195.55 and get the following error window
![error window](https://user-images.githubusercontent.com/17562417/32926055-f6b3003c-cb3c-11e7-96c8-0249671c0418.png)

Note: this character is the same one that was showing multiple physical limits in issue #2013. 

The character is in create mode and so there are no improvements to be reloaded.

There are no changes to the character after it has been reopened - closing it does not tell me there are changes to be saved. I have saved the file but still get the error upon reloading.

### Steps to reproduce the behaviour
Open the character file.

### Link to affected character file
[Scarab.zip](https://github.com/chummer5a/chummer5a/files/1480860/Scarab.zip)

**Comment by chummer5a** [comment]
An earlier patch replaced the hard-coded Technomancer living persona with a gear item that's generated from improvements. Since the character has the Technomancer quality but didn't have the gear item, we throw up that message. Reapply Improvements in the Special menu will clear it, but our preference is to ensure that you can save a backup of the character before you take possibly-destructive changes with the Reapply Improvements button.
