### ISSUE TITLE
Enhancement: Move "Hide Qualities prohibited by Missions" to Quality selection window

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2084]
The checkbox "Hide Qualities prohibited by Missions" is currently tucked away on a tab in the Options panel. 
![hide missions](https://user-images.githubusercontent.com/17562417/33081849-318a9820-ced3-11e7-9c57-7239e84ae715.png)

Requiring a successful Memory Test to realize why you don't see all Qualities on the Quality selection window.
![select a quality](https://user-images.githubusercontent.com/17562417/33081904-4e664aa2-ced3-11e7-9fb7-1cd1525b3967.png)

As this window already has filter options, could the functionality of the "Hide Qualities prohibited by Missions" be moved to this panel as "Show Only Mission Legal Qualities" ?

**Comment by DelnarErsike** [comment]
Keep in mind that the current plan for that option is to migrate it into using the Custom Data Directory system, especially because Missions rules also change a few items instead of just banning them.

**Comment by Lochabar** [comment]
Don't know anything about the Custom Data Directory system.

But if it is a way to different sets of data don't you have to decide somewhere which custom data to use? In which case you have to go to options and select it?

Would this allow the selection of Missions Legal Qualities to be filtered from the Qualities pane?
Or would it still be necessary to go to Options and select/unselect Missions depending on if you want to create a Mission Legal character or a character than can select from all Qualities?

**Comment by DelnarErsike** [comment]
Custom data directories can be added, removed, rearranged, and toggled under the Optional Rules tab in the current nightly. There is already a set of custom rules that is made for Shadowrun Missions 1.4 FAQ packaged with the program's downlaod. When it is toggled (after a restart), all data present in Chummer5 will comply with the rules of Missions 1.4 FAQ.

Since missions changes content instead of just hiding it, creating a missions-legal character would tend to necessitate custom data. For example, Prototype Transhuman costs 10 karma by RAW but 20 karma by Missions, and there's no way to make a character comply by that change without altering the data that Chummer5 uses.

**Comment by Lochabar** [comment]
Does chummer always have to be restarted when you toggle a set custom rules?
I will have to succeed in a Memory Test to remember toggle rulesets when opening a non-Missions character and then back for Missions character.

**Comment by chummer5a** [comment]
Depends on the rule but strictly speaking, mostly no. The restart prompt mostly comes down to the fact that language changes don't update dynamically, most option changes require a close of the character at most and generally not even that.

What you could do to mitigate this is make a secondary Settings file for your Missions characters by copying the default.xml file in /settings to give it another name, then open up Options and name it. It's a bit awkward to set up, but once you've done that, any characters that were saved with the Missions options xml file active will automatically load that file.
