### ISSUE TITLE
Enhancement: Warning when opening a character that is not valid under optional rules

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2089]
### Environment
Chummer Version: 5.195.77
Environment: Windows 7 home edition
Runtime: (probably .NET 4.7.1)

### Expected behaviour
When I have the "SR Missions 1.4 Rules" of the "Custom Data Directories" selected and open a non-Mission character that has Mission restricted attributes I get a warning.

### Actual behaviour
A non-Missions character has the Santeria tradition
![tradition 1](https://user-images.githubusercontent.com/17562417/33185798-f5527a2a-d07c-11e7-84f4-d4047f133a0b.png)

If I open the character with the Missions 1.4 Rules selected the tradition is set to blank.
![tradition 2](https://user-images.githubusercontent.com/17562417/33185816-1a450a78-d07d-11e7-8802-b1db596707c7.png)

If I were to save this character then it is likely anything dependent on the tradition may be invalidated.

Is it possible to present a warning when opening a character that is not valid under the currently selected ruleset that the character is not valid?

### Steps to reproduce the behaviour
With the "SR Missions 1.4 Rules" selected, open a character that has non-Mission legal attributes and review those attributes.

**Comment by StarWeaver** [comment]
Better: 

1. Save all the optional settings in the character file
2. Warn when loading character file with different settings, with a 'change current options to match character' button.
3. Warn harder if two characters with different settings are loaded at the same time.

(I'm guessing a lot of the things like karma kosts and house rules options are global and transplanting them to be able to be different in different characters loaded at the same time would be a painful massive overhaul, which is why i'm recommending just warnings.)

**Comment by DelnarErsike** [comment]
Could you review this issue to see how it works with the current set of Nighlties? The entire setup for custom datasets and settings was changed, after all.

**Comment by Lochabar** [comment]
With individual character options the character now opens correctly.
