### ISSUE TITLE
Not needed files in the releases ?

### ISSUE THREAD

**Issue by Tom-0169** [chummer5a/chummer5a#209]
__"root folder"__
* Chummer5.pdb

__in "data"__
* *.zip
* *.xsd

__in "lang"__
* de.xml.bak
* en-us2.xml
* fr.xml.bak
* jp.xml.bak
* language.Designer.cs
* language.xsc
* language.xsd
* language.xss

Are they still needed?
Just optimizing my PortabelApps Build...

**Comment by joha4270** [comment]
Chummer5.pdb are not needed, but is required for detailed crash reports

I will take a look at the source and look at the other mentioned files

**Comment by joha4270** [comment]
Looking a little on the source i have some guesses on this. Be aware that they are no more than informed guesses

*.zip
As far as i can see they are used by Omae, that atleast uses some zipped data, but it might just be upload/download. Try enable the log, delete the files and upload and download a few chars to omae. If you don't see any obvious errors you can probably delete them. Otherwise i think i can provide a build with Omae disabled in that case.

.xsd
Xml schema information. I'm afraid they are needed, even if i don't understand how

*.bak
Backup files of some kind, possibly created by source control. A text search finds no references to ".bak" anywhere in the project, i think those are safe to delete

language.Designer.cs
I think that one is copied to output directory due a faulty setting. Think you can delete it.

language.xs[cds]
i think you need those

en-us2.xml
Alternate us language file. seems to be missing a required data file. Can be left out (so can the translated language files too it seems, chummer will just not give the option of changing language)

**Comment by chummer5a** [comment]
@joha4270 covered it all pretty well. 

The XSDs tell chummer and the things that hang off it like character sheets how to interpret the data in Chummer. Absolutely required. I could embed that stuff into the application, but it's mostly there for transparency's sake. Easier for people to make custom character sheets if they can see the way values are expected to be used.

The .baks are from some source control issues. Ignore them, I keep forgetting to pull them out. 

The language.x[ss/sd/sc] files are necessary, but I'll clean up language.xsd so that the hanger-on files aren't required.

I'm not sure why en-us2.xml is a thing. Chummer used to keep crashing if I deleted it, so I sort of threw my hands up and ignored it.

**Comment by Tom-0169** [comment]
Okay, thanks for clearing this up.
Did run Chummer without these files (en-us2.xml not removed) & had no problems so far.
Omae did pose no problems on startup & download of character sheets, custom data, contacts, critter or enemys. Did not test login or register.
