### ISSUE TITLE
Full list of Selected sourcebooks changes after toggling Custom Data Directories

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2091]
### Environment
Chummer Version: 5.195.77
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
The list of selected sourcebooks is unchanged after switching back from the "SR Missions 1.4 Rules" of the "Custom Data Directories".
![sourcebooks 1](https://user-images.githubusercontent.com/17562417/33187347-0c17a062-d089-11e7-823b-954642874504.png)

### Actual behaviour
After selecting the Missions FAQ custom directory, with its reduced list of permitted 
sourcebooks, then deselecting the custom directory, previously selected entries in 
the sourcebook list are now unselected.
![sourcebooks 2](https://user-images.githubusercontent.com/17562417/33187358-1c09fb82-d089-11e7-8038-51c6bd86e811.png)

### Steps to reproduce the behaviour
Check one or more sourcebooks not permitted under Missions. Save and allow restart.
Check "SR Missions 1.4 Rules" of the "Custom Data Directories". Save and restart.
Uncheck "SR Missions 1.4 Rules" of the "Custom Data Directories". Save and restart.
Review the list of sourcebooks, the previously checked books are now unchecked.

**Comment by chummer5a** [comment]
Hrm. We'd have to change the logic in some way so that instead of hiding books, we just prevent their activation. It's a lot of hoops to jump though; you're still likely better off setting up a custom settings file for your Missions characters and just toggling between them as necessary for new characters; once you've set it up once, the settings file will persist until you open the options menu again with that character open, from memory.

**Comment by Lochabar** [comment]
I created a customs settings file with all books selected and the Missions rule set switched off and saved the  setting. When I restarted Chummer, it opened the default set with the setting changes. I cannot get Chummer to open a custom options file and keep it open - it keeps asking if I want to save the settings. Any suggestions?
