### ISSUE TITLE
Remove decimals from Nuyen

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2094]
### Environment
Chummer Version: 5.195.77
Environment: Windows 7 home edition
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Nuyen amounts do not have decimals.

### Actual behaviour
Every Nuyen value displayed shows two decimal places when Nuyen does not have decimals.

In issue #2080 you reference buying one standard tag and the currency category in gear.

You cannot buy one standard tag; you buy 10 for 1¥ not 0.10¥ each.

And I believe currency has been implemented wrongly: RF 174 states "All rates expressed in relationship to one nuyen", no fractional amount suggested. You buy 0.8 Saeder-Krupp Corporate Scrip for 1¥ not 1.25¥ for 1 scrip. The fractional amount is in the exchange currency not in nuyen. 

The decimal places make nuyen prices look higher than they actually are until you recognize that there are now decimals being displayed. Nowhere in any of the source books are there nuyen prices with decimals. Can we please go back to this in chummer.

**Comment by prismatic-mind** [comment]
No decimal is probably a gameplay design, economic rules in shadowrun should allow decimals :)
That's not a problem.

**Comment by Lochabar** [comment]
I've been told in the past "As a general rule we don't change gear names around". Why wouldn't this apply to things like the nuyen prices - the books use only integer values, to the point of 5 or 10 for 1¥, so no decimal printing needed.

**Comment by DelnarErsike** [comment]
The reason I marked this as errata/clarification required is that even if you assume that you can only ever buy items in quantities that make sure you can only ever get integer prices, there are multiple parts of RAW that can often result in decimal costs, even without considering Currencies (which are a separate issue, I'm sure if your local money lender wouldn't scoff at you trying to exchange 10 EUR for USD, even though their exchange rate as expressed in relation to 1 EUR would mean 10 EUR produces a decimal number of USD). Examples include: getting Used quality of a 'ware whose cost is not divisible by 4 (e.g. Auto-Injector Expansion) creates a decimal cost, having a number of roommates such that the total payer count is not divisible by 2 or 5 creates decimal costs, and pawning any item whose original cost is not divisible by 4 (e.g. 10 rounds of Flechette Ammunition) creates a decimal cost. There are no explicit rules that mandate decimal costs always be rounded in some fashion the instant they would be created, so decimal costs must at least be kept track of internally.

As for the amount of decimal places displayed, we assumed that two decimal points is what most people are used to for costs in the real world, so we set displays to two places, This is amplified once by the fact that 1¥ in Shadowrun represents a value between $1 and £1 of today's money, which have large enough values to call for decimal tracking (as opposed to JPY, where ¥1 has a small enough value that there is no need for hard currencies of decimal places), and twice by the fact that Shadowrun's ¥ is a purely digital currency, meaning there are only benefits and no downsides to decimal tracking. For a practical example of the latter, see today's Bitcoin, which is extremely often subdivided into satoshi; 1 sat = 10^-8 BTC, i.e. 1 sat < 0.0001 USD as of today, and yet it's still something fully tracked and supported by BTC's blockchain because there are only upsides to doing so.

Going back to Chummer5, we actually track to decimal-type precision, which can mean up to 28-29 decimal places' worth of tracking depending on the number, but we wanted to cut displays off specifically because of worries of nuyen amounts being harder to read when all 28 decimal places are displayed.

**Comment by Lochabar** [comment]
How about a selectable option to Hide Nuyen Decimals?
When checked the screens and character sheets do not show any decimals. (Maybe round in favor of the fixer to keep him happy!)
