### ISSUE TITLE
Proteus Lamprey still not listed.

### ISSUE THREAD

**Issue by Monzill82** [chummer5a/chummer5a#2145]
### Environment
Chummer Version: 5.195.0 (Updated from 5.193, not a fresh install)
Environment: WIN 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Proteus Lamprey listed (According to previous bug report by same account, the issue was the item was in the code, but the book listing was  wrong, and was going to be fixed in the next update)

### Actual behaviour
Proteus Lamprey still not listed

### Steps to reproduce the behaviour
Install chummer 5.193, use in program updater to update to 5.195

### Link to affected character file
None listed. Potentially fresh install required?

**Comment by DelnarErsike** [comment]
The Proteus Lamprey entry has been fixed in the nightly build, but it has not made its way into a stable release. You may either use the nightly build, wait until 5.196 comes out as a stable release, or look at what was done to change it in the nightly build and replicate it on your own in your own installation of Chummer5a.
