### ISSUE TITLE
Make the Rebuild function in translator doesn't add missing pages

### ISSUE THREAD

**Issue by luizbgomide** [chummer5a/chummer5a#2199]
The Rebuild function in Translator just adds new strings, but if the contents was changed (like page numbers were added) it doesn't fill this information. If it did add the page numbers (even if just for the untranslated items), it would be easier to update languages and the contents would be more correct.

### Environment
Chummer Version: 5.196.11

**Comment by DelnarErsike** [comment]
The "rebuild" function is not meant to keep track of and automatically catch strings that were changed since the last time the translation filed was updated. All it is meant to do is add in any missing strings and remove unused ones, specifically to make the Translator tool actually usable.

Normally, the Translator creates all the string entries when a new translation file is created, but it does not automatically update string entries. It also cannot edit strings that do not have entries. Before the Rebuild function, a user wishing to update an older file would have to either manually add in those entries using a Text Editor (making the Translator tool pointless) or create a new translation file and manually copy-paste the already-translated strings over to the new file using a Text Editor (making the Translator pointless). This is what Rebuild is meant to remedy: it's meant to fix issues that made using the Translator tool pointless, not actually add new features that the Translator did not previously have.

Automatic tracking of changed strings would, IMO, also be a gigantic pain to implement compared to its usefulness. There would need to be automatic string version tracking involved that is independent from nightly version tracking (since not every new nightly updates strings), an extra repository for exactly what strings are changed with each string version that definitely will get way too big after a few changes, settings and automation for how exactly to treat changed strings (especially if someone opens up a file, makes a few edits, then closes the file without actually correcting the changed strings), etc. etc. Feel free to work on the codebase yourself if you desperately want this sort of functionality, but please forgive me if I don't want to put in all this work for a feature that is basically already covered by people reporting mistranslations to localization authors.

**Comment by DelnarErsike** [comment]
I think I misread your original comment and the issue instead was related to the Translator tool not actually displaying `altpage` node contents properly. This has now been fixed.
