### ISSUE TITLE
Questions about Custom Data Directories

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2218]
I've been looking at the Custom Data Directory processing and I have some questions
1) Is there a write-up about how to format the rulesets?
2) Is it possible to rename a specific item of gear?
3) Should changes be made using the name of a item of gear or its GUID? (I see both are used, but I know the Chummer team have been moving away from matching on names to using the GUID.)

**Comment by DelnarErsike** [comment]
I assume you're talking about the `amend` system, which is separate from the custom data directory system, even if the `amend` system was made to make custom data directory maintenance easier. You can still use `custom` and `overwrite` files in custom data directories, just like how you can still use `amend` files inside of the regular data directory.

No write-up currently exists for the `amend` system, though you should be able to use the folders inside of `customdata` as references.

The `amend` system requires you to have some method of identifying your target node(s). By default, it will identify by `id` if it's provided, then by `name` if no `id` is provided, and will do so via exact match (i.e. it will find the node that has the exact same `id` as the one specified in the amend). You can specify additional (or different) identifier nodes by adding the attribute `isidnode = yes` to any children of the particular amend, and the system will treat nodes marked in that way as if they were `id` nodes. You can also specify any custom XPath filter as additional (or different) identifiers, see the "no headware in cyberlimbs" ruleset for an example. In the case of the latter two, it is possible for multiple nodes to end up matching the identification pattern, in which case the system will process every single target as its own, separate thing.

Once the system finds matches, it will perform amending on all nodes, even the one(s) used for identification. By default, it will replace inner contents if the specified node exists and has no children, it will add the amending node if it doesn't already exist, and it will perform the whole algorithm recursively if the specified node exists and has children (you can change the latter two and/or specify removing nodes with the appropriate attributes). You can leverage that last behavior to get real intricate with amends in combination with custom XPath filter identifiers, see the "no headware in cyberlimbs" ruleset for such an example.

Since `id` nodes can be used for identification, you can rename specific items by providing both an id node and a name node: the system will identify the target node to amend based on the id node, then it will overwrite the old contents of the `name` node with the new ones.

**Comment by oxford-fumble** [comment]
(Disclaimer: I'm not part of the Chummer team, just doing some customisation of my own)
There is a fair bit of info on the Chummer wiki on the file structure (wich I understand to relate to Chummer4, but the file structure is very similar as far as I can tell - certainly, I've been able to use it for my own purposes).

I'm sure you've already had a look at the [custom file section](http://www.chummergen.com/chummer/wiki/Custom%20Data%20Files.ashx) on the wiki, but the section on file structure is easy to miss, and very helpful (I've missed it myself, quite a few times!). Here's the [link](http://www.chummergen.com/chummer/wiki/Data-File-Overview.ashx) in case it's useful.

Renaming gear is easily achieved with override_[gear/armor/weapons].
It's really useful to create your custom files outside of the Chummer files (ie. NOT in the custom data or data folder, or even the Chummer folder), so that you can update Chummer easily without deleting your custom files. Then in the interface, you can "Add Directory" from the "Optional Rules" tab in Options.

(Good Luck!)

**Comment by Lochabar** [comment]
Then I think I have a problem with how I am using the amend system. Playing around I tried to rename a couple of items in Clothing.

These are the entries from the armor.xml data file
![decent diamond](https://user-images.githubusercontent.com/17562417/34442345-67deb7a4-ecb9-11e7-8d54-31eb268e151c.png)
![good watch](https://user-images.githubusercontent.com/17562417/34442346-680004ea-ecb9-11e7-99f4-4075f2c6100f.png)

And the Chummer Add Armor
![decent diamond ring](https://user-images.githubusercontent.com/17562417/34442368-8a11175e-ecb9-11e7-9863-9f56dd7244c0.png)

I created this amend_clothing ruleset in my Custom Data Directory, copying from the armor.xml data file
![amend_clothing](https://user-images.githubusercontent.com/17562417/34442445-25ccb130-ecba-11e7-9522-dfca2150298c.png)

But when I restart Chummer with the ruleset active the Clothing item names are unchanged
![select armor with rule](https://user-images.githubusercontent.com/17562417/34442496-75701fec-ecba-11e7-946a-ac98b4da6509.png)

**Comment by oxford-fumble** [comment]
Try to use override_armor instead.
I don't know how amend works - and as Chummer said, they weren't really meant for customisation by users, but for their own benefit.

The documentation on the wiki is really enough to get going with overrides.

**Comment by chummer5a** [comment]
Nah, amend is better for this purpose since it only changes the specific thing. Largely irrelevant, but it's handy. Anyway, this indicates there may be an issue with the amend system so it's something to look into.

**Comment by DelnarErsike** [comment]
The naming is incorrect. If you're affecting items in the `armor.xml` file, then your file needs to have a name that ends with `armor`. E.g. you can call your file `amend_clothing_armor.xml` or `amend_armor.xml`, but not `amend_clothing.xml`.

**Comment by Lochabar** [comment]
I was looking at the other rulesets and they have very varied name but I didn't realize they still had the xml file name as the last node. I renamed my file and got it to work. Thank you.
