### ISSUE TITLE
Translator does not show page numbers anymore

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2221]
### Environment
Chummer Version: 5.196.23
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Show page numbers.

### Actual behaviour
The column "Page" is empty even if the corresponding values exist in the chosen data translation file (de-de_data.xml in my case).
I did not try to change and save anything true that Translator.exe because I don't want to risk loosing all page number informations.

### Steps to reproduce the behaviour
Start Translator.exe.
Choose a language and click Edit.
Select any data file and a category. For example "armor.xml" and "armors".

### Link to affected character file
(Enter text here)

**Comment by DelnarErsike** [comment]
Does the issue persist after a rebuild? If not, then it's because the original "page" entries weren't properly handled by the translator. It originally added them is `page` nodes, which are meant for the original, English page references, not as `altpage` nodes, which are meant for alternate page references for non-English sourcebooks. This was fixed a few builds ago, and I made it so that when you rebuild the translation file and it fetches data to put into a new `altpage` node for an item, it will prioritize existing `page` nodes in the translate file before content from the data files.

**Comment by holgerschlegel** [comment]
If I "Rebuild" the translation files for German, page numbers are shown again.
In the file the page numbers are now under the <altpage> tag.

Are all page numbers automatically transfered from the old <page> tag to the new <altpage> tag during that Rebuild? I don't want to check/add all page numbers again.

**Comment by holgerschlegel** [comment]
Another thing I just noticed:
The rebuild removed most of the translated="True" attributes from the translation file.
I set that attribut on entries were the translation is exactly the same than the english text to prevent it from being highlighted as "to be translated" in the Translator GUI.

Now I have to manually re-add hundreds such atributes to mark such entries are already translated ...
