### ISSUE TITLE
Enhancement Request: Ability to add Echoes independently from Submersion for 15 karma

### ISSUE THREAD

**Issue by oxford-fumble** [chummer5a/chummer5a#2227]
### Environment
Chummer Version: 5.196.26
Environment: Win 10
Runtime: 4.7.1

### Desired behaviour
- On the submersion tab
- ability to add an echo even though no submersion grade for 15 karma
- ability to add more than one echo per submersion grade, for a 15 karma per additional echo

### Notes
- There is an option for "Additional Metamagics / Echoes" in the Karma Costs tab of the Options menu
- This is likely to be a legacy from Chummer4, when this was an option in the official rules
- It would be great to be able to split echoes from metamagics (ie. give the option for echoes, but NOT for metamagics)
- Currently, one can add more than one echo per submersion grade, with no additional cost in karma

Thanks.

**Comment by DelnarErsike** [comment]
As far as I'm aware, this is already possible using the improvement system. The `selectecho` and `addecho` nodes do just what you describe, they add an echo to the character as long as they're eligible for it (addecho directly adds a specific echo, selectecho allows the user to choose an echo, possibly from a pre-specified list). The only things missing are the data entries to allow GMs to add those in as custom improvements instead of relying on creating custom data entries, but otherwise they should work just fine.

**Comment by chummer5a** [comment]
I think old chummer had the ability to directly add echoes through the UI without requiring a separate improvement for it?

**Comment by oxford-fumble** [comment]
Following on your (Delnar's) comments, I can see it works fine in Career mode - adding a second echo to a submersion grade costs 15 karma, as it should.

Would it be possible to have the option for Create as well?
In Create, I can select a second echo fine, but it doesn't cost me any karma (yay, free echo!). 
(Screenshot attached - the second echo of grade 2 was free, and no error came up when I selected as Created and saved)
<img width="1182" alt="screen shot 2018-01-01 at 22 02 28" src="https://user-images.githubusercontent.com/4921171/34471382-e1b91654-ef3f-11e7-85ce-a8f390ecd351.png">
