### ISSUE TITLE
Translator Does Not Allow Translation of Mentor Spirit Advantages and Disadvantages

### ISSUE THREAD

**Issue by DelnarErsike** [chummer5a/chummer5a#2237]
The Translator project allows the user to translate item names, item pages, and alternate book codes for books. However, it currently does not support creating translations for mentor spirit advantages and disadvantages, even if it includes the appropriate fields in rebuilds and new translations.

**Comment by chummer5a** [comment]
Ideally I'd like to see the translator pick up some kind of translation key from the XML file itself so that it can dynamically adjust to whatever needs translating. Major problem with this would be the datagridview wouldn't play nice with arbitrary columns if you've merged the categories for a given book. 

I suppose we could alter the generation method to enumerate through everything first, find the total number of unique string categories that are added and just do an item.add(argxxx...zzz) that way.
