### ISSUE TITLE
chummer search cyber/bioware and spells too long if you use more than corebook

### ISSUE THREAD

**Issue by ARgits** [chummer5a/chummer5a#2257]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.196.32
Environment: windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

When I use all books and search (through Search field) some cyber/bioware or spells, it takes some time and when you add some of these, you need to wait 5-30 sec (for example, seaching and adding gear works instantly)

**Comment by DelnarErsike** [comment]
Performance problems in general tend to be tricky to debug, mainly because we don't really have access to the breadth of hardware required to be able to properly debug performance problems.

Three questions, if I may:

1. Is this slowdown recent (maybe onset by the Meltdown mitigation patch disabled CPU features that were previously key to Chummer not running as poorly), or has SelectCyberware always had performance issues for you?
2. Is the slowdown affected in any way if you uncheck the "Hide Cyberware Over the Availability Limit" checkbox and/or if you browse in Career mode and not Create mode?
3. If you have more than one machine, is the slowdown experienced on all of them, or only some? If it's the latter, what commonalities are there between the affected machines that are different from the unaffected ones?

**Comment by ARgits** [comment]
1. it started slowdown, if i can remember, after 5.196 release, maybe a little early.
2. it's slowdown always, even if i turned off all books, except CRB, just not so strong.
3. don't have another machine to check, but I tryed to put chummer on my SSD system disk (early i always put it on HDD), but this doesn't change anything at all

**Comment by ARgits** [comment]
Checked on 5.196.40: now cyber/bioware and spell lists works fine, but slowdown appeared in quality list (when click "Add quality", trying to search and add quality to character)

**Comment by chummer5a** [comment]
What are the specs of the device you're running it on?

**Comment by ARgits** [comment]
it's msi ge60 0NC:
1.Intel core i5 3230m
2. Nvidia 650m
3. 12gb ddr3
4. SSD: samsung evo 850 (250gb)
5. HDD: WDC WD5000LPVX-22V0TT0 (500 gb)
i actually checked this problem, and now (5.197.6) this no slowdown at all, but still don't know, what cause this problem earlier.
