### ISSUE TITLE
Translator doesn't add all XML sources when creating/rebuilding

### ISSUE THREAD

**Issue by luizbgomide** [chummer5a/chummer5a#2260]
### Environment
Chummer Version: 5.196.33
Environment: Windows 10

### Expected behaviour
All translatable strings should be copied to the target translation xml.

### Actual behaviour
The following XML are not added:
lifemodules.xml
paragons.xml
vessels.xml

And a section in vehicles.xml: <weaponmounts><mods>

Also the specializations (<spec>) from the skills are not accessible in the Translator interface, but they are properly copied to the new language file.

### Steps to reproduce the behaviour
Just create or rebuild a translation.

**Comment by DelnarErsike** [comment]
Life modules don't actually have a translation engine in place to begin with, so it's meaningless to try to process `lifemodules.xml` in the Translator. Creating such an engine would be part of the life modules rework.

Specialization translations are a different beast, and like Metavariant translations, the issue is tied to #2237.

I'll be adding support for `paragons.xml` and `vessels.xml` processing, as well as being able to process weapon mount mods in `vehicles.xml`.

**Comment by luizbgomide** [comment]
The `paragons.xml` still doesn't have its content on the rebuilt translation files.
