### ISSUE TITLE
The "In Debt" negative quality has disappeared from the list of qualities.

### ISSUE THREAD

**Issue by ivancraddock** [chummer5a/chummer5a#2297]
### Environment
Chummer Version: 5.196.44
Environment: Windows 10

### Expected behaviour
The "In Debt" quality should be visible selectable from the list of qualities.

### Actual behaviour
The "In Debt" quality is not anywhere in the quality list.

### Steps to reproduce the behaviour
Create a new character, and look for the "In Debt" quality in the list.

**Comment by chummer5a** [comment]
Does it show up if you untick the filter for qualities you can’t take? From memory it’s set to have a sin requirement or some such.

Sent from my Windows 10 phone

From: Ivan Craddock
Sent: Sunday, 14 January 2018 7:06 PM
To: chummer5a/chummer5a
Cc: Subscribed
Subject: [chummer5a/chummer5a] The "In Debt" negative quality has disappearedfrom the list of qualities. (#2297)

Environment
Chummer Version: 5.196.44
Environment: Windows 10
Expected behaviour
The "In Debt" quality should be visible selectable from the list of qualities.
Actual behaviour
The "In Debt" quality is not anywhere in the quality list.
Steps to reproduce the behaviour
Create a new character, and look for the "In Debt" quality in the list.

**Comment by chummer5a** [comment]
Are you using the rules for ShadowNet or Shadowrun Missions? Both of those LCs ban that quality.

**Comment by ivancraddock** [comment]
Thanks, that solved it!
