### ISSUE TITLE
PI-Tac Incorrect Pricing

### ISSUE THREAD

**Issue by litlikefire** [chummer5a/chummer5a#230]
9/23/2014 Errata lists PI-Tacs as follows
Level I: 
Avail 12R, cost 115,000¥
Level II:
 Avail 18R, cost 325,000¥
Level III: 
Avail 18F, cost 855,000¥

**Comment by joha4270** [comment]
Upon closer inspection, Chummer matches the prices in my copy of run faster.

**Comment by litlikefire** [comment]
PI-Tacs are in R&G, not RF.

R&G Errata (http://cdn.shadowruntabletop.com/wp-content/uploads/2014/09/E-CAT27002E_RG-Errata.pdf) lists the changes on page 2.

**Comment by joha4270** [comment]
Since you have now so kindly provided Errata and added a body to your original, we can now reopen this issue.

Now in the future, you can provide that kind of information before you hit that "Submit new issue"
You are having a problem with a piece of free software, developed by me and the other guy in our free time, the least you can do is tell us how something is wrong instead of just telling us that it is wrong. 

Yes i'm a little bit pissed.

Issue will be fixed in 5.167

**Comment by litlikefire** [comment]
Blank original submit was a slip of the fingers, and corrected in under a minute. I apologize for not sourcing where my local errata file was publicly hosted in the first comment. Thank you for your quick and professional responses.

**Comment by joha4270** [comment]
Email alerts, alerts on the mailbox :P
I hear a little 'pling' every time somebody creates or responds to an issue.

Now i think an apology on my end is in order too. But that was the second
issue in a few days where i open it and see "Generic problem" to an empty
body.
I get a bit stressed.

2015-06-11 21:04 GMT+02:00 litlikefire <notifications@github.com>:

**Comment by litlikefire** [comment]
No sweat! Thanks for all your work on this, it does mean a lot

**Comment by joha4270** [comment]
And comments like this makes it all worth it.
