### ISSUE TITLE
Use translation engines to perform configuration file conversion

### ISSUE THREAD

**Issue by Dedalios** [chummer5a/chummer5a#2332]
### Environment
Chummer Version:  chummer5a/chummer5a
Environment: w10
Runtime: ( probably .NET 4.5.1)

### Expected behaviour
Just Idea  Why not use the translation engine to automate the translation process

### Actual behaviour
 I do not program on the language of the project

### Steps to reproduce the behaviour
 I am looking to propose ideas. But I'm not sure if I put this message in the good place

**Comment by chummer5a** [comment]
I'm generally not a fan of machine translations; if someone wanted to take a raw translator file and use that to do translations or whatever then that's on them, but I'd rather we fall back to known-good English than use pidgin translations.

**Comment by luizbgomide** [comment]
I don't really see the point in that. If the translation already exists is a matter of inputing the correct strings, it is a tedious work, and prone to a few errors, but for sure would be a better match than a machine translation.
If the translation doesn't exist, then you would have just loose strings without any real context (because the book and references are still needed to play). Not to mention the mangled result that for sure will happen. I don't see that as playable.
If you are talking just about the interface, this is the smallest possible problem, and the program is quite intuitive (considering the complexity of Shadowrun) and after a few uses it becomes quite mechanic in nature.
Not sure how that is an enhancement, unless I'm missing something.

**Comment by luizbgomide** [comment]
I don't really see the point in that. If the translation already exists is a matter of inputing the correct strings, it is a tedious work, and prone to a few errors, but for sure would be a better match than a machine translation.
If the translation doesn't exist, then you would have just loose strings without any real context (because the book and references are still needed to play). Not to mention the mangled result that for sure will happen. I don't see that as playable.
If you are talking just about the interface, this is the smallest possible problem, and the program is quite intuitive (considering the complexity of Shadowrun) and after a few uses it becomes quite mechanic in nature.
Not sure how that is an enhancement, unless I'm missing something.

**Comment by Dedalios** [comment]
In view of the volume of channels to translate any language, I think , adding to the translation tool the call to the automated solution could be a simple help. It is up to the  translator to do the necessary to make the modifications more suitable on a case by case basis. To have a help of this type of tool not that this one is the process of translation by default.

**Comment by Dedalios** [comment]
other question where a found chummer5a compilated not source code ? http://chummer5a.github.io/chummer5a/ 
(Prob with Dropbox  https://www.dropbox.com/sh/p5yimzsgljq3nnn/AAAa2q6l970NAkUUtZ4CvOgpa?dl=0)  error 404
 http://www.chummergen.com/ dowload old projet  Shadowrun 4th Edition

**Comment by chummer5a** [comment]
Sourcecode is available from https://github.com/chummer5a/chummer5a/archive/master.zip

**Comment by Dedalios** [comment]
Sorry for my english ,i don't search a source code , i can use github for create fork or obtenain source code, No i search exec program. i have'nt microsoft visual studio for create exe program

**Comment by chummer5a** [comment]
https://github.com/chummer5a/chummer5a/releases

**Comment by Dedalios** [comment]
Language with code fr not be loaded for Chummer.Nightly and Chummer5.197.1

**Comment by Dedalios** [comment]
I found Chummer5 exe version 0.0.5.139 with found this problem

**Comment by chummer5a** [comment]
Can't reproduce. Show me a screenshot of the problem?

**Comment by Dedalios** [comment]
Strange with other machine i Can't reproduce. but regarding the first machine, windows did not recognize the software as valid

**Comment by Dedalios** [comment]
When you open chummer wiki , it's possible we cant'  propose the choice of area translate wiki page

**Comment by Dedalios** [comment]
I want translate but i how to use the program translate
