### ISSUE TITLE
Knowledge Skills calculated improperly on current chummer5a version

### ISSUE THREAD

**Issue by MandozerTheGreat** [chummer5a/chummer5a#235]
Using build 166. Knowledge skills seem to be defaulted to LOG/INTx3 instead of x2 with no option to disable.

**Comment by joha4270** [comment]
Actually, it is possible to change, it is just not where you would expect. Under the house rule tab, there is the option to enable "Free knowledge points equal to (INT+LOG) x [3]"
Changing this number will affect priority selection too. To be able to change it you have to enable the house rule, but you don't have to leave it enabled.

A (real) quick search did not find the root cause so unless the other guy finds it, it is doubtful i will be fixed by 167. In that case expect a more permanent fix in 168 or 169.

**Comment by MandozerTheGreat** [comment]
That did the trick. Thank you.

**Comment by joha4270** [comment]
Your welcome.

2015-06-15 17:49 GMT+02:00 MandozerTheGreat <notifications@github.com>:

**Comment by joha4270** [comment]
Please don't close this issue as there are still a bug that needs to be identified even if a temporary workaround exists.

**Comment by MandozerTheGreat** [comment]
My apologies, my first time on github and wasn't familiar with how things work around here. Just wanted to get word of the issue out there.

**Comment by joha4270** [comment]
No worries.

**Comment by chummer5a** [comment]
Can close the bug, I left a debug value in settings a while back that
defaulted it to x3. It was fixed around 1.63 or so, but some users may have
retained the incorrect value. Enabling and disabling the house rule will
clear it up.

**Comment by MandozerTheGreat** [comment]
Got it good to go. Cheers.
