### ISSUE TITLE
German language error after update to 197.1

### ISSUE THREAD

**Issue by Noraser** [chummer5a/chummer5a#2369]
after update to 197.1 had the problem that error messages "language with code de could not be loaded" poped up constantly. Pops imidiatly up after closing the Error.
Changed the de language fiels back to original name, then it imidiatly worked.

Fix:
rename de-de.xml to de.xml
rename de-de_data.xml to de_data.xml
### Environment
Chummer Version: 197.1
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
program starts without error

### Actual behaviour
end up in Error loop

### Steps to reproduce the behaviour
update to 197.1 (tested on 2 diferent systems)

### Link to affected character file
(Enter text here)

**Comment by DelnarErsike** [comment]
**DO NOT** change those filenames. They were deliberately altered to abide by the international standards that allow Chummer5 to load their default culture formatting information. Information in `sheets.xml` as well as information related to the character sheets themselves also now rely on this new format.

Normally, Chummer5 should have been able to catch that you have your language set to reference a file of the old format and change it to match the new one accordingly. However, for some reason, this did not happen with your install. This is the true bug here. What can you tell us about exactly when the error popped up, and/or if you could reselect the appropriate localization in Chummer5's options?

**Comment by Noraser** [comment]
Chummer5 is not starting, so I can't setup anything. Also the error is poping ab ongoing, means if I close the error message then it's imidietly coming back, with no end. (if I change the language fieles with the error open and then close the error, it boots rigth away - no need to start it again)

Also I had this error at my friends Laptop and my main PC, at my Laptop the Error was not there,  it runs fine with the upgrade... So this is not a general Issue to german settings, (Chammer shout have been setup very simular at my Laptop and my home PC -can't garantee 100%)

**Comment by Youneko17** [comment]
Some user in Chinese Shadowrun Community have also met with this problem. We figured out a way to fix this problem in window environment, by change a regedit file.
Note that since I have no idea of German Windows OS, it's based on Chinese version, which is similar to English version. The details are as follows:
1 win+r and type regedit, enter
2 find HKEY_CURRENT_USER→Software→Chummer5
3 find "language" under Chummer5 and open it
4 change the original "de" to "de-de" or make other appropriate change that suits the language you use
Hope this may help : )

**Comment by DelnarErsike** [comment]
I think I caught on to the issue, it's related to a mix-up in the legacy shimmer that would convert from the old style to the new one. Fixed in commit 2bd13e6f220e7d0fd20ce1eaa30acf1dd51fe57d, should be in the next nightly. If you no longer encounter the issue with the next nightly, please close this issue.
