### ISSUE TITLE
 "Animal Familiar / Sprawl Tamer / Shock Mage" Increased amount of Spells chosen at character generation

### ISSUE THREAD

**Issue by MiraNoir** [chummer5a/chummer5a#2408]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? (Tried Stable 5.197.1 / 5.197.13 / 5.197.15)
Environment: (Operating system here. If it persists over multiple OS's list them all) Win10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
When adding "Animal Familiar / Sprawl Tamer / Shock Mage" amount of Spells taken at character generation is correctly reflected

### Actual behaviour
When adding "Animal Familiar / Sprawl Tamer / Shock Mage" the amount of spells chosen is increased. (10/10 spells with 6 Spell and 2 Preparations)

### Steps to reproduce the behaviour
Remove "Animal Familiar / Sprawl Tamer / Shock Mage" reduces amount of spells and re-adding them increases amount of spells chosen.

### Link to affected character file
(Enter text here)
[Kerrigan.zip](https://github.com/chummer5a/chummer5a/files/1670984/Kerrigan.zip)

**Comment by MiraNoir** [comment]
Proper character file

[KerriganTest.zip](https://github.com/chummer5a/chummer5a/files/1670986/KerriganTest.zip)

**Comment by DelnarErsike** [comment]
This is part of the mechanic where you can use spell points gained from priorities to buy Mastery qualities in place of karma. Chummer5 will automatically calculate whether it's favorable to do so (based on how much karma a spell would cost), and if it is, it will use spell points instead of karma to pay for it. You'll notice that while your spell points get used up when you take those qualities, your karma does not decrease.
