### ISSUE TITLE
Essence Loss should not apply to new sources of MAG/RES

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#2463]
### Environment
Chummer Version: 5.197.26

### Expected behaviour
If a character takes a quality that would give them a MAG or RES value during career mode while already having an Essence penalty, that value will begin at 1, or whatever value is dictated by the quality.

### Actual behaviour
The character either burns out immediately, losing access to the special attribute, or begins with 0 in the attribute.

### Steps to reproduce the behaviour
Move a mundane character with some amount of Essence Loss into career mode and give them the Adept quality or Infected: Ghoul qualities.

### Linked issues

#1006

Possible errata required with regards to Infected: 
http://forums.shadowruntabletop.com/index.php?topic=19013.msg495283#msg495283

**Comment by DelnarErsike** [comment]
Issue with new sources of MAG/RES getting burned has been fixed in commit b940408e65f3ea15b8db8f63c352701c0b04b594. Special cases for infected essence loss have sort of been accounted for as well due to the way Character::EssenceAtSpecialStart works (it will not decrease when metatype maximum Essence decreases). May need further testing to make sure something doesn't mess up in edge cases.

**Comment by chummer5a** [comment]
![image](https://user-images.githubusercontent.com/11448441/36140502-9664809e-10f5-11e8-8007-5d0d8ea9c94d.png)
Still seems to be doing it; mundane point-buy character with Wired Reflexes 2; give them a mag-enabling quality and it'll start them with zero.

**Comment by DelnarErsike** [comment]
Bah, forgot about chargen Essence Loss. Give it a spin with the latest commit.

**Comment by chummer5a** [comment]
Bingo, champ
