### ISSUE TITLE
Issues with life modules

### ISSUE THREAD

**Issue by plmarlowe** [chummer5a/chummer5a#2470]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.197.1
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
When choosing life modules both attributes and skills will be updated.  In addition program will not allow life paths to be taken if it would duplicate a quality.

### Actual behaviour
When choosing life modules the program is not adding ranks to skills.

### Steps to reproduce the behaviour
Have tried deleting the program from my PC and doing a clean download of the most current build and the problem continues to persist.

### Link to affected character file
(Enter text here)

**Comment by SeanPGorman** [comment]
There is a major issue with Life Modules right now. There is a project to re-write the implementation that is underway - mainly or solely by @OLStefan I believe.

I'm sure there is a way that you could navigate the system to make a character but it isn't easy. I make characters by hand and then enter them without applying the rules.

**Comment by Turley0815** [comment]
Environment
Chummer Version: 5.205.0, German Version
Environment: Windows 10
Runtime: I don't know this :> But
> reg query "HKLM\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Full"
gave me
>   Version    REG_SZ    4.7.03056

Expected behaviour
New character, added "Mystic Adept", then try to Add "Amazonian - Metropole Rio de Janeiro". Programm should add this nationality, but adds "General UCAS" instead.

Actual behaviour
When choosing life modules the program is not adding ranks to skills.

Steps to reproduce the behaviour
Have tried deleting the program from my PC and doing a clean download of the most current build and the problem continues to persist.

Link to affected character file
New character, select Life Modules, select Elf, add Amazonian, error happens.

Thanks for your time ^.^

**Comment by chummer5a** [comment]
unable to replicate the issue with attributes and skills not loading. SIN management is part of #2024
