### ISSUE TITLE
Made Man quality weirdness

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#2492]
### Environment
Chummer Version: 5.197.33
Environment: Windows 8.1
Runtime: 4.0.30319.42000

### Expected behaviour
Made Man quality giving (adding?) a free group contact to your syndicate (i.e. Prime Data Haven Membership does this successfully)

### Actual behaviour
Made Man quality needs an existing group contact to apply to. This group contact has to be paid with CharGen Karma

### Steps to reproduce the behaviour
Create a character, try to add Made Man quality (doesn't work without existing Group Contact)
Add a group contact and add Made Man (costs 5 Karma for quality and 3+Connection Karma for contact)

**Comment by DelnarErsike** [comment]
Addendum to the fix: Because Made Man is applied to a group contact that does not have its connection rating specified, it cannot be handled the way Prime Data Haven Membership can, so it will still need to be selected from an existing group contact. Everything else should be fixed in the latest commit.
