### ISSUE TITLE
Dual Natured Defender

### ISSUE THREAD

**Issue by rpk0714** [chummer5a/chummer5a#2499]
### Environment
Chummer Version: 5.198.0
Environment: Win7 x64
Runtime: .NET 4.5.1

### Expected behaviour
"Dual Natured Defender" should not fill a spell slot.

### Actual behaviour
After "Dual Natured Defender" is added, one spell slot is filled as well by the quality.

### Steps to reproduce the behaviour
Add positive quality "Infected: Vampire (Human)".
Add positive quality "Dual Natured Defender" for 5 Karma.

### Link to affected character file
[Dual_Natured_Defender_BUG_5.198.0.zip](https://github.com/chummer5a/chummer5a/files/1729078/Dual_Natured_Defender_BUG_5.198.0.zip)

**Comment by DelnarErsike** [comment]
Working as intended. If using priority-based character generation, Magic Mastery qualities can be purchased with spell points instead of karma: you will notice that while a spell point is spent, your karma does not actually decrease from taking Dual-Natured Defender. Chummer5a will automatically spend spell points instead of karma on mastery qualities if it is not disadvantageous to do so (i.e. if spell points are not worth more than the 5 karma at which they can be exchanged on mastery qualities and/or if the particular quality has a karma cost not divisible by 5).
