### ISSUE TITLE
Allow purchasing multiple items at once

### ISSUE THREAD

**Issue by chickenoxo** [chummer5a/chummer5a#2566]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.198.25
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Currently, if I want to add all of the hacking programs to my gear I have to add each one individually about 15 times and then move them 15 times to its own location. If you could ctrl click them you could easily select batches of differnt gear and move them easily.

### Actual behaviour
NA

### Steps to reproduce the behavior
NA

### Link to affected character file
NA

**Comment by chummer5a** [comment]
Ctrl-click multiple-selection probably not practical due to rating spinners and such; change the add & more button to 'add to cart' or whatever to call it. purchased object is sent to an array, form stays open, select the next item, add to cart, etc. Method that called the form iterates through purchased items, calling Purchase method for gear.
