### ISSUE TITLE
Karma to nuyen error for Sum-To-10 builds

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2634]
### Environment
Chummer Version: 5.199.0
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Fixed bug.

### Actual behaviour
For characters build with sum-to-10, the karma spend for Nuyen is always set to 10 karma after opening the file. Saving the character with another value (e.g. 0), still sets the value to 10 on the next load of the character file.

### Steps to reproduce the behaviour
Create a new character with sum-to-10.
Set karma to be converted into Nuyen to zero (or anything other than 10).
Save and reopen the character.

**Comment by Zitchas** [comment]
I just tested this, and it appears that Chummer is reading

`` <nuyenmaxbp>10</nuyenmaxbp>
instead of  
`` <nuyenbp>7</nuyenbp>

I just went into a character I already had made and changed the value of nuyenmaxbp up to 16, and when I opened the character in Chummer, it promptly read 16 as the amount I had spent on nuyen.
