### ISSUE TITLE
Restrictive Gear cannot be taken multiple times

### ISSUE THREAD

**Issue by Seeron** [chummer5a/chummer5a#2723]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.199.0
Environment: Win10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Restrictive Gear should be taken multiple times or have quality ranks.

### Actual behaviour
Restrictive Gear can only be picked once and you cannot set the rank of the quality

### Steps to reproduce the behaviour
Create a new character and add Restrictive Gear as a PQ

**Comment by chummer5a** [comment]
You can only have one level of it in create mode.

Sent from my Windows 10 phone

From: Seeron
Sent: Saturday, 5 May 2018 9:42 PM
To: chummer5a/chummer5a
Cc: Subscribed
Subject: [chummer5a/chummer5a] Restrictive Gear cannot be taken multiple times(#2723)

(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)
Environment
Chummer Version: 5.199.0
Environment: Win10
Runtime: (If you don't know this, it is probably .NET 4.5.1)
Expected behaviour
Restrictive Gear should be taken multiple times or have quality ranks.
Actual behaviour
Restrictive Gear can only be picked once and you cannot set the rank of the quality
Steps to reproduce the behaviour
Create a new character and add Restrictive Gear as a PQ
