### ISSUE TITLE
Martial Arts :: Specialisation :: addskillspecializationoption seems non-functional

### ISSUE THREAD

**Issue by Nedorus** [chummer5a/chummer5a#2760]
### Environment
Chummer Version: 5.200.2.0
Environment: win7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
When choosing a martial art, this martial art should show as a possible specialisation for one (or several) of the skills "unarmed combat", "pistols", "blades", "gymnastics", "clubs" or "projectile weapons".

### Actual behaviour
The selection of a martial art has no influence on the selectable specialisations list shown. This is true even for martial arts which have a bonus-addskillspecializationoption in the martialarts.xml like 52 Blocks or Parkour.

Not all martial arts have this bonus-addskillspecializationoption however. (e.g. Chakram Fighting, Ninjutsu)

### Steps to reproduce the behaviour
1. create new character
2. add a martial art with addskillspecializationoption (e.g. Parkour)
3. raise skill that should have the added specialisation (e.g. gymnastics)
4. check listing of possible specialisations

#### Note:
The [martial art] entry for unarmed combat seems to be hard coded.

#### Note 2:
There is a workaround: if you manually type the name of the martial art into the specialisation field, it will show up on the character sheet. Therefore this may not be highest priority (^_~)

### Link to affected character file
n.a.

**Comment by chummer5a** [comment]
The addskillspecializationoption bonus was built for a specific reading of how martial arts work, namely that they count as a specialisation in and of themselves, rather than being a separate specialisation you can buy. As is, it would be awkward to implement it in a way that would work properly for localisation since there's no unified translation schema that would be reasonably performant. 

Still, someone might think of a better way to implement it than I have.
