### ISSUE TITLE
Run and Gun Errata

### ISSUE THREAD

**Issue by McRipolo** [chummer5a/chummer5a#278]
Please add the entire Run and Gun Errata, you have already been adapted a few points, but some are missing.

Link to the Errata:
http://cdn.shadowruntabletop.com/wp-content/uploads/2014/09/E-CAT27002E_RG-Errata.pdf?b979cc

Missing Points:
P. 20, COUGAR FINEBLADE STAT CHANGES
P. 20, EXOTIC MELEE WEAPONS ADDITION
P. 25, HARPOON/JAVELIN RANGE
P. 25, URBAN TRIBE TOMAHAWK SKILL AND RANGE (Cavalier Arms Urban Tribe Tomahawk is completely missing)
P. 26, BLOWGUN RANGE
P. 34, PPSK-4 COLLAPSIBLE MACHINE PISTOL CONCEALABILITY CLARIFICATION
P. 40, BARRET MODEL 122 STANDARD UPGRADES ADDITION
P. 52, FOREGRIP MOUNT CLARIFICATION
P. 55, FLAME THROWER AMMO, AV ROUNDS, GYROJET ROUNDS, GAUSS ROUNDS MISSING FROM AMMO PRICES
P. 190, MISSING EXPLOSIVE STATS

I have only listed the changes for functions Chummer5 concern.
Maybe the errata should be checked again, as I may have overlooked something.

Thanks for all the work on Chummer.

**Comment by chummer5a** [comment]
Accuracy for the Blades altered.
Chakram added.
Harpoon ranges already set.
The Tomahawk is only listed on the Gear tab, due to the weird way in which
they interact with the Ammunition pool.
PPSK-4 has had a Collapsed Frame accessory added to it that confers the -6
Concealability. Accessory mods can also no longer be installed on the gun.
Blowgun range changed.
Sound suppressor added to the Barret.
Foregrip mount is currently irrelevant, pending a rebuild of how the
mounting system works.
Ammo added.
