### ISSUE TITLE
Unable to add multiple varieties of Gas Grenades as sub-item on vehicle

### ISSUE THREAD

**Issue by Brunius** [chummer5a/chummer5a#2784]
### Environment
Chummer Version: 5.200.2.0
Environment: Windows 10 Pro
Runtime: .NET Framework 4.7.1

### Expected behaviour
Gear added to Vehicles / Drone can be separated out and does not automatically group up

### Actual behaviour
Gear added to Vehicles / Drones does group up

### Steps to reproduce the behaviour
Create a Vehicle / Drone
Right Click > Gear > Add Gear > Grenade: Gas
Right Click > Gear > Add Gear > Grenade: Gas

I have tested this with Grenade: Gas and Minigrenade: Gas. Frankly I don't see an issue with other types grouping up, but if you're trying to make a drone that can switch between Pepper Punch grenades and Neurostun IX grenades, this becomes an issue.

**Comment by chummer5a** [comment]
This probably won't get any traction until I get around to working on the Ammo class. As is, if you add the pepper punch or whatever to the first grenade, the second grenade won't stack with the first. Or at least it's not supposed to.

**Comment by Brunius** [comment]
I've just tried that again.
When adding to a vehicle, adding one, adding the plugin, then adding another, results in a stack of two gas grenades.
When adding to a character/location, adding one, the plugin, another, results in two stacks of one

**Comment by chummer5a** [comment]
So the core of this issue is that improvement events aren't triggered for vehicles, only for things that are directly connected to your character. This prevents cyberware installed on your drone from affecting your character's stats, but means that selection prompts don't fire properly. Same issue as #3887. The workaround is to purchase the items on your character and use the Transfer To Vehicle button to move them into the vehicle.
