### ISSUE TITLE
Cerebral Booster increases Logic, but the increased value does not alter the knowledge skills points calculation

### ISSUE THREAD

**Issue by Intellektfresser** [chummer5a/chummer5a#2789]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.2
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
A cerebral booster level 2 properly increases the logic attribute by 2 points -> The knowledge skillpoints are calculated with the increased logic attribute.

### Actual behaviour
A cerebral booster level 2 properly increased the logic attribute, but the knowledge skill points are still calculated with the basic value. I don't know if that is an issue with Chummer 5 or me interpreting the rules wrong.

### Steps to reproduce the behaviour
removing and adding the cerebral booster does not alter the behaviour

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
There’s an optional rule to have your knowledge skill points be affected by your ‘total’ value instead of natural values, iirc.

From: Intellektfresser
Sent: Friday, 8 June 2018 7:14 PM
To: chummer5a/chummer5a
Cc: Subscribed
Subject: [chummer5a/chummer5a] Cerebral Booster increases Logic, but theincreased value does not alter the knowledge skills points calculation(#2789)

(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)
Environment
Chummer Version: 5.200.2
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)
Expected behaviour
A cerebral Booster level 2 properly increases the logic attribute by 2 points -> The knowledge skillpoints are calculated with the increased logic attribute.
Actual behaviour
A cerebral Booster level 2 properly increased the logic attribute, but the knowledge skill points are still calculated with the basic value. I don't know if that is an issue with Chummer 5 or me interpreting the rules wrong.
Steps to reproduce the behaviour
removing and adding the cerebral booster does not alter the behaviour
Link to affected character file
(Enter text here)

**Comment by Intellektfresser** [comment]
I found it, so thank you for your quick response. I thought it was basic that the altered Attributes where used for that unless stadet otherwise like bone lacing, etc.

**Comment by chummer5a** [comment]
> SR5 95: Attributes boosted by cyberware or bioware do not affect the calculation for things such as points or Knowledge skills or Contacts.
