### ISSUE TITLE
Bug involving Dedicated Spellcaster, Practiced Alchemist, Mentor Spirit, and Durable Preparations

### ISSUE THREAD

**Issue by darays** [chummer5a/chummer5a#2819]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: v5.200.57
Environment: Windows 10
Runtime: .net 4.5.1

### Expected behaviour
1.  Dedicated Spellslinger adds additional spell slots equivalent to Spellcasting ranks.  Spells should not cost karma when added with this quality.
2.  Mentor Spirit w/ Spirit Mask added without karma loss
3.  Durable Preparations added with no issues.
4.  Practiced Alchemist added with no issues.

### Actual behaviour
1.  Additional spell slots added as expected, also adds two to the current spell count while no spells are in list.
2.  Mentor spirit with spirit mask deducts 5 karma from current karma.
3.  Durable Preparations adds 1 to current spell count.
4.  Practiced Alchemist adds 1 to current spell count.
5.  The added spells do count against the character when adding spells after feats, and also when the feats are added after spells.

### Steps to reproduce the behaviour
Create character.  Character needs to have a Magic rating, Spellcasting skill with at least 1 rank, and Alchemy at least 6 ranks.  Then add the above listed qualities, order does not matter, though skill rank requirements apply.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
I'm not sure I see the problem. 
* Durable Preparations and Practiced Alchemist are Mastery qualities, so they're purchasable with spell points. Since karma is more flexible in its use than spell points are, Chummer will preferentially use spell points before karma for those qualities. 
* Mentor spirit costs 5 karma, I'm not aware of anything that should make mentor spirits free, aside from some Adept Ways. 
* Dedicated Spellslinger works by providing you with additional free spell points.
