### ISSUE TITLE
Can't buy off uneducated from a shifter

### ISSUE THREAD

**Issue by ArtOfCombat** [chummer5a/chummer5a#2876]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.201.0
Environment: Windows 10 Home
Runtime: .NET 4.5.1

### Expected behaviour
Upon deleting the uneducated quality on a shifter's creation, it SHOULD simply spend 8 karma and remove the quality.

### Actual behaviour
Upon deleting the uneducated quality on a shifter's creation, it spends 8 karma and the quality is not removed.

### Steps to reproduce the behaviour
Create a shifter (I used vulpine). Go to their core page, select the uneducated quality, and attempt to delete.

### Link to affected character file
N/A

**Comment by chummer5a** [comment]
More or less working as intended, it just doesn't refresh the treeview properly. Since create mode doesn't have the same expense system as career mode, we needed a way to keep track of the fact that you'd bought off the Uneducated quality. What should be happening is that the quality is converted to a positive quality that doesn't contribute to your limit.
