### ISSUE TITLE
Community made content hidden because of source

### ISSUE THREAD

**Issue by Maxis010** [chummer5a/chummer5a#2897]
### Environment
Chummer Version: 5.201
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Custom weapon is loaded into Chummer and available to add/use

### Actual behaviour
Weapon is not available

### Steps to reproduce the behaviour
Load custom file as normal
custom_weapons.xml: https://pastebin.com/92Uh9HSV
Start chummer
Attempt to add weapon to character

Weapon is valid but even if added to the standard weapons.xml as is it will not show
The issue is with the source, if it doesn't match up to one of the loaded rule books, even if it is custom content then it is not available in chummer

Confirmed this by changing source to RG, weapon shows up and can be added so long as the Run & Gun source book is loaded (Tested as a customdata entry)

**Comment by chummer5a** [comment]
There a reason you can't make a custom book to go along with it?

**Comment by Maxis010** [comment]
I have, seems like a needless extra step for both content creators and their users since it adds a restart to the whole process

**Comment by chummer5a** [comment]
I don't really see that as a usability concern. Ideally, a living community or whatever will provide the users with a custom settings.xml file to use that's prepopulated with the allowed books, optional rules and house rules, which would include your particular custom book. If that's not sufficient, you could just map it to the SR5 book, but I'd personally prefer to see it mapped against a book so that the source label actually works. I could probably build in functionality to make it open a web link instead of a PDF reference.
