### ISSUE TITLE
Cannot add licenses to SINner Offical SINs

### ISSUE THREAD

**Issue by lifebound** [chummer5a/chummer5a#2927]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.202.0.0
Environment: Windows 10
Runtime: 4.6.2

### Expected behaviour
When taking a SINner negative quality, you are prompted for a value for a SIN. My presumption would be that this would replicate as an 'official SIN (*type here*)' in your gear, where licenses can be added to it as required by gameplay or story.

### Actual behaviour
Taking a SINner negative quality does not insert any gear into inventory.

### Steps to reproduce the behaviour
Create a character, up to quality selection.
Take a SINner quality (National, Criminal, Corporate, or Corporate Limited)
You will be prompted for a SIN value. Provide it.
Go over to gear, note that no offical SIN has been inserted.

**Comment by chummer5a** [comment]
There aren't any rules for legitimate licenses, fake licenses are presumed not to work with real SINs, so there's not really anything to transfer.

**Comment by Lochabar** [comment]
Page 363 or the core rule book reads "Acquiring a license (legally) is, again, dependent on the laws of the country. For the most part, acquiring a license involves making an application, paying some sort of fee, **a SIN check**, and possibly passing one or more certification, testing, or training programs."

And page 419 says "Licenses and permits can be obtained through legal channels, as long as you’re a solid citizen with a legal SIN"

It's the SIN check that is the problem - even a rating 6 fake SIN could be spotted in a legality check, so why take the risk of blowing a very expensive fake.

So getting most legal licenses for a legal SIN should be a lot less than buying a fake. Why get a rating 6 fake hunter's license for 1,200¥ when the real thing might cost 20¥ - and no risk of being found with a fake license. Of course the key phrase is "legal SIN" - most Shadowrunners don't have/use that luxury.

**Comment by Zitchas** [comment]
I suspect that might be the problem with implementing it in Chummer: There's no cost listed (and issuing bodies will *definitely* want payment for it), and could only be attached to a legal SIN. Which is also something that does not show up in the inventory. The fact that it likely varies in price with the jurisdiction would also be problematic.

**Comment by chummer5a** [comment]
More or less, yeah. I can absolutely convert the SIN quality to add a gear object that can have real licenses attached to it, but absent of any RAW I'd prefer to let sleeping dogs lie.

**Comment by Zitchas** [comment]
Much as I'd like to have a legal SIN option with legal licenses to simplify things, I agree. 

The legal SIN itself would be a free "item" since it is part of the quality - simple enough and I don't think there needs to be any additional RAW for that to be included. But that'd just beg for licenses and there's really no RAW for them. (then there is also the fact that the prevailing (public) opinion is that if one has a shadowrunner cursed with a real SIN, the top priority is burning it... Although I know a lot of Shadowrunners that start off with some degree of SINner.)

In the mean time, I'll just keep using fake SINs and labeling them "REAL - UCAS" or "REAL - Ares" as appropriate. That seems to work, and Chummer already has a means of giving them for free (and at whatever price I decide as GM for the licenses). 

Not quite as straight forward, but it works.

**Comment by OLStefan** [comment]
How about adding the legal SIN as gear when adding the quality and then just use Custom Items and call them "Legal Firearms License" .

That way we would only add the legal Sin you definitely have, but don't really touch the legal License issue while users still having the possibility to do so for their home game,

**Comment by OLStefan** [comment]
To add to this:

The german Core rulebook at least sets a precedence for adding fake licences to non-fake SINs. In the description on fake licences it says (translated): "Each licence must be assgined to a (forged) SIN of the player's choice."

**Comment by DelnarErsike** [comment]
I'm closing this issue because this feature is already sort-of present in Chummer5a. Fake Licenses can be added to items in the Custom category, so if you add a 0 cost Custom Item and call it "Real SIN" or something, you'll be able to add Fake Licenses to it. You can also add Fake Licenses to real SINs from Shadowrun 2050 because they can be added to Shadowrun 2050's Standard Credstick item (which is what carries Real SINs).
