### ISSUE TITLE
Beast's Way

### ISSUE THREAD

**Issue by Verecoth** [chummer5a/chummer5a#294]
The Beast's Way quality says that it costs 20 karma, but when taken it only takes away 15 karma.

**Comment by Verecoth** [comment]
Figured out that this applies to more than one Way, and happens when one has already taken Mentor Spirit.

**Comment by chummer5a** [comment]
Intended behaviour; adepts following the Spiritual Way and Beast's Way gain the benefits of a Mentor Spirit for free. There's an argument to be had about whether you need to have Mentor Spirit in order to take either of those Ways, but it seems to be correct. That said it will probably break terribly in career mode.
