### ISSUE TITLE
Fuchi Cyber-N and Cyber-Ex cyberdecks don't work as expected

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#2953]
### Environment
Chummer Version: 5.202.something

### Expected behaviour
The Fuchi Cyber-Ex and Cyber-N allow for preconfigured stats at time of purchase, but are otherwise locked. These values should ideally be editable during create mode, but locked after purchase during career. 

### Actual behaviour
Adding mods to either device causes a crash due to capacity/category shenanigans.

**Comment by Zitchas** [comment]
I think it'd probably be better to have the values editable during the process of purchasing it, rather than tying it to creation mode. There may well be people buying it during their careers, after al.

**Comment by chummer5a** [comment]
Yeah, so I need the ability to provide a layer of interpolation between when the item is selected and we create the final expense entry. Not hard per se, just not something that was designed into the existing purchasing mechanism.

**Comment by Zitchas** [comment]
I suppose that's the downside of new material, right? There's only so many ways to re-arrange the numbers, so they have to start adding in funky edge cases that don't quite follow the rules.

**Comment by DelnarErsike** [comment]
The custom cyberdecks now generally work as intended, but there still are a few hang-ups.

1. Since RAW does not specify that the cyberdecks must have a minimum rating of 1 in all of their attributes, each attribute needs to be added manually as plugins. I made sure the attribute names start with brackets, so they should always appear at the top of the list when adding plugins.
2. I have not added a check to make sure each custom attribute is only added once, and I haven't thought about how I'd go about adding this check (though human eyes should pick it out right away).
3. The custom cyberdecks work weirdly with electronics modifications. Right now, I've set the relevant electronics modifications to filters that work assuming that the cyberdeck will have a minimum of 1 in every attribute, but this naturally has issues.
4. TreeNodes for gear aren't data bound and it's a pain to databind them. What this means is that if someone adds a Matrix attribute to a custom cyberdeck at a specific rating, then lowers the rating of the custom cyberdeck to where the previously added Matrix attribute's rating would also need to be lowered, the TreeNode for the Matrix attribute won't update itself to show the new rating it gets to remain compliant with the whole "attributes-cannot-be-higher-than-cyberdeck-rating" thing.

**Comment by Ramesch** [comment]
Since the vehicle 'EMC Kommodore' (SHB3) also has a modular structure, which has to be defined at the time of purchase: perhaps it is possible to program the addition to the configuration of Cyberdecks during the purchase so that it can also be used for vehicles?
