### ISSUE TITLE
Slide Mount is not functional

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#2954]
### Environment
Chummer Version: 5.202
Environment: Win 10
Runtime: .NET 4.5.1

### Expected behaviour
Slide Mount weapon mods are supposed to allow you to add other accessories on top, which can then be easily removed.

### Actual behaviour
Slide Mount does nothing other than blocking the accessory slot. No accessary can be installed on top of the Slide Mount slot.

**Comment by chummer5hasanerror** [comment]
the slide mount takes up a slot
when a slot is filled, you cant put another attachment in that location, which is RAW.
Slide mounts are a modification to make installing/removing a second accessory easier/less time consuming.

To display additional accessories for a gun when X slot is filled:
go to weapon weapons tab
Select Slide Mount on (Desired Gun)
uncheck the 'installed' box 
behold, you can now add in additional accessories for that slot. 

Because a weapon can only have one one accessory in one _slot_ the program should not allow you to have multiple 'installed' boxes checked for multiple accessories of the same slot, 
-meaning you will have to uncheck 'installed' on each slot-sharing accessory in order to purchase additional accessories for that location

**Comment by aga9** [comment]
This is where common sense should come in.

A **slide mount** (IRL) is not in itself a functional accessory. It is a type of mounting. When you install a slide mount on top of a gun, it allows you to install another slide-mount-compatible accessory on top of it. A slide mount installed on top of a gun would do nothing to speed up the mounting/dismounting of an under-barrel accessory.

A careful reading of the rules (RG p.52) supports this:

> Slide mount (accessory): By installing this on the top, underneath, or side slots, you can make it much easier to install and remove items **in these locations**. Items may be taken on or off using a Simple Action.
(emphasis added)

The wording suggests that slide mounts modify the mount/dismount item of accessories at the same location they're installed on.

**Comment by chummer5a** [comment]
A fix for this is in development. It's going to allow detaching and attaching accessories and for accessories to have other accessories mounted to them.

**Comment by chummer5a** [comment]
Duplicates #2954

**Comment by chummer5a** [comment]
Duplicates #2040
