### ISSUE TITLE
Implement sensor housing limits

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#2957]
### Environment
Chummer Version: 5.202
Environment: Win 10
Runtime: .NET 4.5.1

### Expected behaviour
CRB p.446, "Sensor Housing" table shows the max sensor limit of each housing type.

When adding sensors to a housing, this limit should be enforced.

### Actual behaviour
This limit is not enforced and it's possible to add rating 8 sensors to any housing.

**Comment by Haplo164** [comment]
I'd like to throw in an availability adjustment as well, sensor arrays start at availability 7 but a vehicle that has avail 0 will flag as 7 when switching to career mode even though the vehicle is under that. Sorry but we just started a campaign with a avail limit of 4 and we cant bring in vehicles because of the sensors.
