### ISSUE TITLE
Cannot add Commlink Accessories to Rigger Command Console

### ISSUE THREAD

**Issue by Nedorus** [chummer5a/chummer5a#2970]
I'm not sure this is actually a bug, but I believe so.

### Environment
Chummer Version: (What version of chummer are you running?
5.202.26

Environment: (Operating system here. If it persists over multiple OS's list them all)
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
It should be possible to add Commlink Accessories to Rigger Command Consoles.
RCC are described as:

> It can act like a commlink and has all the features of a commlink in addition to the cool drone stuff. 

Therefor it should be possible to add the commlink accessories.

### Actual behaviour
commlink accessories cannot be added to RCCs

### Steps to reproduce the behaviour
1. create new character
2. add a Maersk RCC
3. tray to add commlink accessories

NOTE:
This can easily be fixed by changing the <geardetails> section for each commlink accessory:
    <geardetails>
        <OR>
            <category>Cyberdecks</category>
            <category>Cyberterminals</category>
            <category>Custom</category>
			**<category>Rigger Command Consoles</category>**
        </OR>
    </geardetails>

### Link to affected character file
(Enter text here)

**Comment by DelnarErsike** [comment]
Working as intended. All purchasable items in the Commlink Accessories category are either already included in RCC's (e.g. Hot-Sim Module) or explicitly can only be used by commlinks and/or cyberdecks (e.g. note that in Multiprogram Operating System's description, it says the device must be connected to a commlink or a cyberdeck in order to work).
