### ISSUE TITLE
Rigger Command Consoles don't have access to comlink accessories

### ISSUE THREAD

**Issue by Zitchas** [chummer5a/chummer5a#3038]
**Describe the bug**
Unlike commlinks and cyberdecks, right-clicking on RCC's and selecting "add as plugin" doesn't have the "Commlink Accessories" category.

**Expected behavior**
That I should be able to add commlink accessories to RCCs. (For instance, the Multiprogram Operating System should probably work with RCCs. There's a few others that would probably be eligible too.)

**Comment by chummer5a** [comment]
MOS says commlinks and cyberdecks specifically. RAW, RCCs don't have commlink functionality.

**Comment by DonCuan** [comment]
>A rigger command console […] can act like a commlink and has **all the features of a commlink** in addition to the cool drone stuff. (SR5, p. 266)

So yeah, everything that's possible with a commlink should be possible with an RCC. (In my case, I want to add a dongle to it)

**Comment by Nedorus** [comment]
This is actually a duplicate of an issue I raised a while ago: [#2970](https://github.com/chummer5a/chummer5a/issues/2970)

@DonCuan @Zitchas If you go there you will find my solution. I made some changes to the gear using a **amend_gear.xml**
I attached it to one of my answers to that issue as a zip file.

Just throw that file into a directory **Chummer\customdata\mychanges** (or something like that) and activate "mychanges" in the **options->optional rules** section and you should be fine.

Even though I fully agree that RCC should have all the options for commlinks (you quote the correct section of the rules) I think we shouldn't necessarily make this platform a rules discussion forum. That's why I didn't contradict @DelnarErsike  at the time he closed my issue.

@DelnarErsike and @chummer5a Maybe you can reconsider and/or make this (at least) available as an optional rule with the standard distribution?
