### ISSUE TITLE
Character sheet limit conditions translations

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#3046]
**Describe the bug**
On non-English character sheets the Limit conditions are not translated.

**To Reproduce**
1. Open a character with conditional limits, e.g. SWAT armor that has a Social Limit modifier
2. Click on Print
3. Switch to German or French
4. Scroll down to Limits section
5. Conditional limits not translated

**Expected behavior**
Conditional limits are translated.

**Screenshots**
German example
![limits de](https://user-images.githubusercontent.com/17562417/45987779-ff604180-c038-11e8-943c-542795a348cd.png)

French example
![limits fr](https://user-images.githubusercontent.com/17562417/45987859-62ea6f00-c039-11e8-90df-fb269a2f86ae.png)

Gear (armor) entry
![gear entry](https://user-images.githubusercontent.com/17562417/45987872-6f6ec780-c039-11e8-9739-faf62896f0dc.png)

**Desktop (please complete the following information):**
 - OS: Windows (any)
 - Version: (any)

**Additional context**
I looked for examples similar to the <bonus><limitmodifier><condition> structure in de-de_data.xml and didn't find any that could provide an example of how to format a translation. So perhaps the reason the Limit modifier strings have not been translated is no-one knows how to format them.

**Comment by chummer5a** [comment]
It's more that the translation system doesn't have any link to most of the bonus types. The LimitModifier class is just four strings and an int.

Proper fix would be to lash it up to the translation system and use tags, but the combination of attributes means we'd have to have ~75 different keys for the existing node names which wouldn't be super extensible. May not be much option for any other way of doing it due to grammarly shenanigans. Personal preference would be to just use guids as the keys.
