### ISSUE TITLE
Change Croatian to Serbo-Croatian or at least add it 

### ISSUE THREAD

**Issue by Marismoto** [chummer5a/chummer5a#3069]
Hello folks!

id like to have the language Serbo-Croatian added to the list of the knowledge skills mainly because Croatian, Serbian and Bosnian are rather dialects than Languages.

**Comment by cnschu** [comment]
As marismoto is native to the region, i would trust him in this matter.
The Skills in this list are suggestions only, why also not implement them as dialects?

**Comment by chummer5a** [comment]
It's not a question of trust, it's just a development decision that we only implement suggestions for skills that have been added via NPC statblocks, Life Modules or otherwise prepopulated lists. Same reason we haven't added Dutch or Afrikaans or whatever. That said, no real reason it can't be added.
