### ISSUE TITLE
Unable to add ammunition to weapon

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#3110]
**Describe the bug**
Purchased ammunition can not be added to weapon

**To Reproduce**
1. Buy 100 round Standard ammo
2. Select Machinepistol as type
3. Switch to weapons and select Ingram X
4. Try to add ammo to Ingram X
5, Only see Slot Empty" as choice and no ammo

**Expected behavior**
Be able to add ammo to weapon

**Screenshots**
![image](https://user-images.githubusercontent.com/12108972/46825619-64839900-cd94-11e8-95c4-606b34bb3b48.png)

**Character File**
 Can upload if needed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.202.63

**Comment by ChaoticElements** [comment]
I have seen this same issue - options for firing, reloading etc. are all greyed out - even if character sheet was created on older version, with ammunition in the magazine.
Version: 5.202.64
![image](https://user-images.githubusercontent.com/20726466/46906359-243e2b00-cefa-11e8-954b-b92239003562.png)

I have noted that this issue is not present in the previous stable build, on 5.202.0
As below:
![image](https://user-images.githubusercontent.com/20726466/46906386-931b8400-cefa-11e8-8921-0643898dd80b.png)
