### ISSUE TITLE
Limit modifiers not removed with gear

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3115]
**Describe the bug**
Sometimes when a gear or quality is removed, the limit modifier it gave remains with the character.

This is usually invisible within Chummer5, but can be seen when exporting to PDF.

This has occurred to me many times. The below is just one way to reproduce it:

**To Reproduce**
[limit bug.zip](https://github.com/chummer5a/chummer5a/files/2475907/limit.bug.zip)

1. Open the attached .chum file.
2. Export this file to PDF — just to confirm that Audio Enhancement is giving a limit modifier of +3.
3. Return to Chummer, go to Gears.
4. Find Headphones, remove the Audio Enhancement add-on.
5. Export to PDF again — the Audio Enhancement limit modifier remains although the item is removed.

**Character File**
see attached

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 5.202

**Comment by DelnarErsike** [comment]
The issue was technically fixed in the latest commit, so going forward, you shouldn't encounter this bug. However, existing characters with these issues will need their existing, orphaned limit modifiers removed manually, which can be done thanks to another bug being present for orphaned limit modifiers like these (the bug where improvement-added limit modifiers could be removed and/or edited independent from their improvement, which means you can manually delete the affected limit modifiers through the UI).
