### ISSUE TITLE
Life Modules: Military School unable to be added

### ISSUE THREAD

**Issue by jjaparsons** [chummer5a/chummer5a#3118]
**Describe the bug**
When making a character using Life modules, the Teen years module of "Military School" is unable tio be added

**To Reproduce**
character creation - life modules selected
Nationality [Any]
Formative Years [Any]
Teen Years [Military School]

**Expected behavior**
Adding the appropriate skills, attributes, etc

**Desktop (please complete the following information):**
 - OS: Windows 10, Build 1803
 - Version [e.g. 5.202.68]

**Additional context**
When Debug logging is used, this is the entry that goes after the improvements are set to be added, and before they are removed

"First chance exception: Chummer.Classes.AbortedException: Exception of type 'Chummer.Classes.AbortedException' was thrown.
   at Chummer.Classes.AddImprovementCollection.addqualities(XmlNode bonusNode) in C:\projects\chummer\Chummer\Classes\AddImprovementCollection.cs:line 5304"

**Comment by OLStefan** [comment]
This is already part of #2000. The issue is that the qualities given in that Life module were renamed at some point and no one updated the module.

**Comment by jjaparsons** [comment]
The quality in question is the 5-point version of Rank.

There seems to be some discrepancy, as this value (5-points) is noted both in this module and in the description of "Tours of Duty", 

"If you have at least Rank 5 when you start a Tour of Duty module, you are an NCO; if you have at least Rank 20, then you are an officer (see explanation of Ranks on p. 86)."

But in the "New Quality" description, seems to indicate that ANY Military or Law-Enforcement rank carries the higher cost of 20/25/30.

Seeing as how the table on page 86 of Run Faster is broken down into 3 double-sets of ranks (two for military, two for law enforcement, two for corporate), each keeping the same split of 3 lower/3 upper (NOCs vs Officers, Beat Cops vs Detectives, Workers vs Management), perhaps the intent was for the lower cost (5/10/15) to be for the lower-tier ranks, and the higher cost (20/25/30) to be for the higher ranks, which would also carry the wider-range of Social-limit benefit?  the Military School and Military Academy are the only modules in Run Faster that automatically assign the Rank Quality (and it is listed the same in both entries as "Military Rank (#)"; Chummer properly assigns the 20-point value when selecting Military Academy).  instead of separating the Rank quality into "Military or Law Enforcement" and "Non Military or Law Enforcement", as it currently is, couldn't it be set as a single quality of variable rating, 5/10/15/20/25/30 ?

**Comment by jwax33** [comment]
I'm investigating this issue using the datafiles included with Chummer 5.204.0.  

I see where the Military School Life Module attempts to assign the Quality "Rank" to the character.  (Per the sourcebook, this should actually be "Military Rank (5)" which also doesn't exist.  The lowest Military Rank is 20.)  This causes the Life Module to fail and not be applied because the Quality "Rank" does not exist.  Removing this line from the xml file causes the rest of the Life Module to work.

However, the Military Academy Life Module does not attempt to assign Quality "Rank" OR "Military Rank (20)" as jjaparsons indicates it does above.  I'm not sure if there's been a change in the data files since his post or not.  Per the sourcebook it should apply "Military Rank (20)."

Fixing Miltary Academy would appear to be simple: add the quality "Military Rank (20)" to it.  Military School remains problematic.  There is no 5 point Military Rank.  There is a non-military Rank (5), however.  Should that be assigned?  The phrase "Military Rank (5)" seems to strongly indicate the rank is supposed to be Military, though.  Did they intend the 5 points from School to boost the 20 from Academy to net 25 after graduating Academy?  That would place the character in the second slot of Military Rank at 25.
