### ISSUE TITLE
Unable to delete or edit Essence Hole

### ISSUE THREAD

**Issue by Trebloc1213** [chummer5a/chummer5a#3146]
The Cyberware selection of "Essent Hole" is unable to be deleted or edited.  It should probably be displayed under the Cyberware expandable menu, but appears outside of that.  The initial setting for Essence Hole appears to work without issue.

Windows 10

Chummer 5.202.76.0

**Comment by DelnarErsike** [comment]
Why would you want to manually delete the Essence Hole? Essence Holes are permanent unless you either fill them up with 'ware (in which case they should disappear automatically) or get the Geneware treatment that recovers it, which should be represented by adding an Essence Antihole due to the mechanics of that Geneware treatment...

**Comment by Trebloc1213** [comment]
Ok, I did not know that Chummer handled it automatically.

However, as to why you would want to delete/edit it, it would be because of either entering an incorrect value or selected it accidentally.  Also, it appeared to also get the Biocompatability ten percentage reduction, which makes it harder to guess how much of a hole you want to create.
________________________________
