### ISSUE TITLE
Date & Time in ISO 8601

### ISSUE THREAD

**Issue by Greybane** [chummer5a/chummer5a#3198]
**Is your feature request related to a problem? Please describe.**
As a European, the date and time often confuses me for a moment until I realize It's following American standards. 

**Describe the solution you'd like**
Follow the ISO 8601 standard of YYYY-MM-DD.

**Describe alternatives you've considered**
Allow us to change the Calendar settings to various regional standards.

**Comment by DelnarErsike** [comment]
This is sort of implemented in the latest commit. Now, calendar dates will always show up in the format of the language to which Chummer5a is localized. By default, this will be the US format due to the default language being en-US, but if you were to create an en-GB language for example (using e.g. the Translator tool) and use it, the format on the calendar dates will change accordingly.
