### ISSUE TITLE
Two missions legal books are not shown in the Sourcebook list

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#3200]
**Describe the bug**
Sourcebooks Aetherology and Coyotes are included in the list of permitted books in SRM Chicago FAQ ver 1.4 (and SRM Combined FAQ v1) but they are not listed in books.xml and therefore are not shown in the Sourcebooks List.

**To Reproduce**
1. Go to 'Global Options'
2. Sourcebooks are not shown.

**Expected behavior**
Aetherology (and maybe Coyotes) is included in the list.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version: 5.203.94 [and prior]

**Additional context**
Aetherology does have game stats present, primarily free spirits and spirit powers
Whilst Coyotes has some new data, specifically Border Crossing costs, I'm not sure there is sufficient system data to include this in Chummer5a.

**Comment by Ramesch** [comment]
As far as I can see - in the German version - only costs for smugglers are included in ‚Coyotes'. Since it is as similar as a hotel night, which you don't note as equipment on your character sheet, you could simply deduct these expenses from your money. Or do I get it wrong?

Regarding the ghosts / demons in Aeterology, I will try to include them.

**Comment by Ramesch** [comment]
Have you tested in the meantime whether the spirits and spirit powers of Aetherology work as they should or do you expect them to?

If so, I think your request could be closed, because the costs for services from the book Coyotes currently can not be entered as equipment or cost of living.

Either this would require a new expense function with a considerable amount of presets (this would be a new request) or you would simply deduct these - sometimes highly individual - negotiated costs from your credstick, such as bribes.
