### ISSUE TITLE
Optional rule: Point-based stat and skill upgrades

### ISSUE THREAD

**Issue by DelinquentPanda** [chummer5a/chummer5a#3201]
My friends and I play with a large number of house rules that make chummer more or less unusable. Because we love chummer and want to keep using it would it be possible to implement an option to enable flat karma costs?

**Comment by chummer5a** [comment]
Ehhh. Anything's possible, it's just a question of where I allocate time. That doesn't feel like a particularly balanced option at first glance, but it's not exceptionally difficult to implement per se. Define the scope of what you'd want to have flattened? Skills and attributes obviously, but initiation, martial arts, foci? How would something like Jack of All Trades interact with it?

**Comment by DelinquentPanda** [comment]
Attributes and Skills would be the big two as there is ways of working with the options to effectively flatten them through whats already available. As for something like jack of all trades the immediate answer that would come to my mind is adding another box (possibly one for each) where you can enter how much the karma cost is adjusted by the given quality (I'll admit I'm not aware how many qualities there are like that, if there is a number I can see how that would get bloaty). qualities that work on a percentage (like doubling or halving) would still likely work fine.

**Comment by xavizeta** [comment]
High, aforementioned friend here. Basically what we're looking for is a way to set our own Skills, Knowledge Skills, and Attribute costs so that they're flat. This is because we've found that the Scaling Costs which were introduced to reduce min/maxing and encourage generalisation did the exact opposite, where people were using the already introduced "flat costs" in Priority and Sum To Ten creation (since Strength 5 and Body 2 cost just as much in these modes) to min/max as hard as they could, and then they'd fill in the gaps post-gen. This isn't a problem with Chummer, but Chummer currently won't support the "fix" (namely, flat costs), and we'd really love to be able using it, since it's amazingly handy for keeping track of things and presenting them in an understandable way.
Thank you.

**Comment by chummer5a** [comment]
I really don't see how it's a fix though; the only thing flat costs will logically do is encourage people to max out their core skills and hence under-value qualities. Show me a design doc of what character creation and advancement looks like for you guys and I'll see what it'd take to implement.
