### ISSUE TITLE
Missing Cyberprogram from Kill Code

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#3259]
**Describe the bug**
The book Kill Code (KC) added one new cyber program to Shadowrun.
As I do not own the English books, I do not know its English name. Based on the table of content in the Shadowiki page for that book, I assume its English name is "Cry Wolf". It can be found at the end of the section that contains the new cyberdecks.

In the German book it is named "Prügelknabe" and can be found on page 62. I did not find any information regarding price and availability so I assume it is the same as for all other hacking programs.

**Desktop:**
 - OS: Windows 10
 - Version: 5.203.121

**Comment by Ramesch** [comment]
The program is called "Cry Wolf" (English, KC p. 63) or "Prügelknabe" (German, KC p. 62), but because of the addition to Chummer5a there is no information in the English and German rules.

At first the rulebook says: "The complexity of the coding and nature of the program gives it a major limitation: It only works once". You would have to delete it after using it (or give it to a person you don't like ;)).

Category, price and availability cannot be found in the English and German rules either.

In addition, the rulebook says: "And don't get caught with this loaded on your deck. There is no amount of fake licensing that will get you clear of the trouble this program brings". Since even hacking programs only have an availability of 6R (in German "6E"), even the "R" here would not fit according to my understanding.

In my opinion, the program could be used either as a "Hacking program" or as a program of the category "Forbidden Program" - the latter is not given by the rules.

Do you or anyone else have any suggestion on how to add the program according to the rules?

**Comment by holgerschlegel** [comment]
Upps, I did not noticed the "can be used only once" part.
In that case, there is no real need to add it to Chummer5a.

And, btw., there is a hacking program with an availability of 12F (German name is "Exterminator"). So the category "Hacking program" would be ok.
