### ISSUE TITLE
Troll Reduction is Bioware. Metatype Reduction is Cyberware and does not distinguish between orcs or Trolls

### ISSUE THREAD

**Issue by Kromgar** [chummer5a/chummer5a#326]
Pg 108 is Troll Reduction increases Charisma cap per rating. Orcs can only take Troll Reduction 1. Trolls can take rating 2.

Pg 73 is Metatype Reduction which can be taken by orcs and trolls and increases charisma cap by 1.

Instead you guys made Metatype Reduction: Orcs and metatype Reduction: Trolls which would fit better as Troll Reduction: Orcs and Trolls or Troll Reduction 2: Trolls

RAW youcan have both Metatype Reduction and Troll Reduction.

Metatype Reduction only lists it can't be combined with metatype Poseur

**Comment by chummer5a** [comment]
They're split into two different sets of qualities because they do different things based on your metatype and I'm not going to write a handler for something that banal.
Metatype reduction for orks grants the human-looking quality.
Metatype reduction for trolls grants +1 maximum CHA.
Orks can't take Troll Reduction Rating 2.
