### ISSUE TITLE
Drain Resistance tests

### ISSUE THREAD

**Issue by liquidmorpheme** [chummer5a/chummer5a#3266]
Apologies if this has been mentioned (couldn't find Drain in search). Chummer currently has all drain as resisted with BOD + WILL, rather than what is correct for the tradition.

**Comment by Teksura** [comment]
It sounds like you are looking at an Adept. Per Core Rulebook, page 308, all Adept powers are resisted by Body + Willpower. This is regardless of tradition, unlike Magicians. If you are indeed doing this on an Adept, what you see is expected behavior.

Please try and reproduce this using a character who is not an Adept (I suggest making a magician and seeing what happens.)

**Comment by chummer5a** [comment]
I'd guess that's correct, yes. Adepts are given a tradition for compatibility with a bunch of things from Street Grimoire, particularly things like aspected background counts. RAW says they need 'em, but it's also explicit that all physical adept powers are resisted with BOD+WIL.
