### ISSUE TITLE
Death Dealer limitations

### ISSUE THREAD

**Issue by Sevasta** [chummer5a/chummer5a#3310]
**Describe the bug**
Death Dealer, by RAW, should apply its bonus to *all* skills that the Critical Strike power is active on. As it is, you select one option when buying the quality and are then unable to even 'buy' the qualtiy again for other relevant skills

Source: Forbidden Arcana pg 36 

"Adepts with this quality add
an additional +1 DV to any attacks made with active
skills affected by the Critical Strike power, but they
may only purchase the first level of this quality"

**Additional context**
I'm of course unsure if this is even possible to implement, but not even the workaround of buying the quality for 1 category then awarding it for 'free' for others works, as the quality is only able to be bought once in chummer as an adept.

**Comment by chummer5a** [comment]
Simplest workaround would be to use the weaponcategorydv improvement type in the Improvements tab to proxy it. I'll have to finagle something for making it behave properly.

**Comment by Sevasta** [comment]
That was my first thought as well, but that improvement doesn't seem to proc/appear/work. Though that's it's own issue.

**Comment by drewikari** [comment]
When taking the quality at creation it also uses 3 spells slots.  If you are supposed to have ten spells it uses three and leaves you with only 7 spell choices before it hits your karma

**Comment by chummer5a** [comment]
It's a mastery quality. Spending spell points instead of karma is more efficient, so we do that for you.

**Comment by chummer5a** [comment]
No, it is not double charging you. The Karma Summary tab is showing the total value of your qualities; if you actually check your consumed karma in the bottom left, you'll see that adding the quality doesn't decrement your karma when you take it.

It's more efficient because that 15 karma you didn't spend on the quality can now be spent on other things that require karma like skills, contacts or bound spirits or even more spells. It won't let you take more qualities than otherwise, but there's still no reason not to do it.
