### ISSUE TITLE
Martial Arts Data

### ISSUE THREAD

**Issue by chummer5hasanerror** [chummer5a/chummer5a#3318]
Can we get something similar to how Mentor Spirits displays data (Specifically the +X to dicepool Y part)
for martial arts techniques?  
Example:
Ti Khao: +1 Unarmed DV when in Clinch
Two Headed Snake: Reduce Negative Pool Modifier for Called Shot (Feint) by 1

Yes, this is just Data Entry.  
Yes, we can do this with notes already.  
Yes, this is necessary, since 99% of players never read the books.  
Yes, this is allowed, because it does not include any of the IP Fluff that is copywritten, its purely mechanical.

**Comment by chummer5a** [comment]
I'm not super interested in the argument that it needs to be in Chummer because people don't read. Chummer is a character creation and play aid, not a replacement for the books. I'm more likely to expand the note collection system to support techniques than I am to do the copypasta work. If you'd like, you can use amend files to add notes to all the techniques that includes the relevant details.
