### ISSUE TITLE
Hammerli Gemini not able to be loaded

### ISSUE THREAD

**Issue by drewikari** [chummer5a/chummer5a#3334]
Issue #3312 is still happening.  Tried loading the gemini with gel rounds.  It crashes when hitting the reload button everytime

**Comment by Ramesch** [comment]
I can reproduce this crash with Chummer5a V5.203.0, but the 3 days ago added fix of chummer5a works for me with Chummer5a V5.203.149 (nightly version) as expected: no crash when (re)loading the Hammerli Gemini.

Have you tested it with the latest nightly version or with the latest stable version? Since the latter was created on November 4th, the bug fix cannot be included in the version yet (only in a future stable version).

**Comment by chummer5a** [comment]
Oh, should have noted in the changelog that you'll need to remove and re-add the weapon for the fix to take effect.

**Comment by drewikari** [comment]
Running version 5.203.150

Once I removed it and added it back it worked
