### ISSUE TITLE
Can I steal your basic data?

### ISSUE THREAD

**Issue by MrGlaurung** [chummer5a/chummer5a#3388]
Greetings.

My name is Anders and I work on a NPC generator where you can modify which ever stat you want to create the NPC of your dreams (or nightmares). I would love the basic data that you have in XML files but I have a bit of trouble understanding the files fully, especially reference between files (for instance weapons and ranges).

Is it possible to get the xml files translated to sqlite by you so I could use them in my application? It would be most appreciated if you could help me.

If you can't/don't have time/don't want to help, where did you get them? Did you type them in by hand or did you get them from a source that might help me?

The NPC generator (which is very very far from finished) is here on GitHub:
https://github.com/MrGlaurung/ShadowrunRoller
and I'm working a lot to get it finished.

My idea is that the final version should allow you to roll any number of NPCs that you can keep in an NPC team and view the NPCs in the program. You should be able to save each individual NPC and the teams so you can access them. You should also be able to write in the info about your PCs and keep up to date info in the program. Finally you should also get a combat round overview where you can choose who from the NPC group and who from the PC group is engaged in combat and you should be able to check off their actions and reactions.

I really hope you have time and energy to help me, it would make my own code so insanely much easier to finish.

Thanks for reading my request and keep up the awesome work with Chummer!!! It's the best character program I have seen :D

// Anders
Gothenburg

**Comment by chummer5a** [comment]
Uhhh, the data's GPL so anyone's free to use it for whatever but I'm not interested in porting it to a format I don't have a use for. I'd be happy to help out with code support if it was a feature you were adding into Chummer, but as is I'd suggest it's probably simpler for you to build a shim to import the Chummer data into whatever format you want, since you could then keep up with our changes. https://github.com/lazierthanthou/sqlite-manager has methods to import and export XML data into your database, you could probably pillage the code to handle that from there.

**Comment by MrGlaurung** [comment]
Thank you kindly for your helpful answer!

I hope my NPC Generator will baffle you in the future so you can have some benefit from my work too.

Have a great day!
