### ISSUE TITLE
Game Master and Group Options [2] - Share Option in Group (Player)

### ISSUE THREAD

**Issue by Nedorus** [chummer5a/chummer5a#3403]
I'll put this in a user story format. I'll put up other to match / extend this one
**Describe the solution you'd like**
As a Player I would like the option to easily load the allowed books, house rules, custom data files and Karma costs set by my GM so I can make sure that my character complies with the rules in the campaign set by my GM when I update / change it.

**Additional context**
This story matches #3402 which is the Gamemaster side of the story

**Comment by chummer5a** [comment]
This kind of already exists. If you copy an options file and paste it into the Options folder, you'll be able to set the name for your second options file, and any characters you make will then prompt for the option file that should be used. it doesn't currently work with the customdata directories since those are stored globally, but that's fixable.

**Comment by Nedorus** [comment]
Well I'd like to synch this so my players don't have to "install" anything when I make changes...
