### ISSUE TITLE
Dedicated Spellslinger Quality, wrong spells count

### ISSUE THREAD

**Issue by GibbousWaximus** [chummer5a/chummer5a#3408]
**Describe the bug**
After adding the dedicated spellslinger quality, the X of XX spells counter in the karma summary is off by +2.

**To Reproduce**
Create a new character
Choose magic A.
Choose spellcasting for one of the magic skills to start at rating 5
Spells shows 0 of 10
Add quality, dedicated spellslinger
Spells shows 2 of 15. Should show 0 of 15.
Add 1 spell, spells show 3 of 15. Should show 1 of 15.

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Version [e.g. 5.204.0.0]

<img width="824" alt="screenshot 2019-02-03 10 23 31" src="https://user-images.githubusercontent.com/918200/52179291-e19ca900-279d-11e9-9f5a-668d3502d39d.png">

**Comment by chummer5a** [comment]
Mastery quality.

**Comment by chummer5a** [comment]
To expand, mastery qualities are preferentially purchased with spell points over karma since karma can be used for more things than spell points can. If you look in the bottom left, you'll see that your actual karma hasn't been consumed yet, while the karma summary tab shows the limit for how many more qualities you can take.
