### ISSUE TITLE
Create Own Life Modul - Feature

### ISSUE THREAD

**Issue by Shiwo** [chummer5a/chummer5a#342]
Life Moduls can be tricky, especially education types and bonuses can be various.

For examples: 

Natural Sciences
Academic Knowledge: [Chemistry/Physics/Biology] +5 
It's an "easier" case, modul should ask the player, he would like to choose one from the three.

Social Sciences
Academic Knowledge: [Sociology/Psychology/Archaeology/Criminology/Politics] +13 (spread out among at least three subjects, minimum three ranks per subject)
In this case the player can choose a lots of variations.So when you choose the modul, you have to choose these as well.. or have to create a lots of modul-variants in advance.

My proposal to make a "Create Own Life Modul" feature / interface. Maybe you can handle it as a "houserule".

Players of gamemasters can create the moduls in advance. Or even anyone can create unique moduls and share in the forum. 

So when a player would like to choose the "Community College - Social Sciences" he would able to create a modul for it : 

Add Karma Cost : 100
Add Attribute -> Logic -> +1
Add Attribute -> Willpower -> +1
Add Active Skill -> Computer -> +1
Add Academic Knowledge -> Psychology -> +4
Add Academic Knowledge -> Archaeology -> +3
Add Academic Knowledge -> Criminology -> +3
Add Academic Knowledge -> Politics -> +3

Then player can show it to the GM, and GM will approve it, if he likes.
Or GM create 4 - 5 variants as Social Sciences education and player have to choose.

Advantage of the feature : 
- Even Tricky moduls can be created in advance, based on the books
- Own, unique moduls can be created, in any type (ie: Nationalitiy, Formative Year, ect)
- Variants of the existing Life Moduls can be created (I feel some of them weaker or stronger than the most, GM can strengthen / weaken them)
- A huge amount of moduls can be created by the community

The interface should be containing the followings : 
- Add Attribute
- Add Active Skill
- Add Skill Group
- Add Academics Knowledge
- Add Interest Knowledge
- Add Language Knowledge (including native possibility)
- Add Professional Knowledge
- Add Street Knowledge
- Add Positive Quality
- Add Negative Quality
- Add Money (and GM can check, the player spent it to Augmentation for example in the case of "Test Subject")

Additional comments : 
- Skills : Active Skills can be max 7, Knowledge max 9. Its clear, Chummer can limit them.
- Attribute : One can be the maximum at start. Which one ? The first which achieve it ? Maybe would be the best if you have to choose among them when you finalize the character..
- Doubled Quality ? Simply ignore ? Or player get the as Quality Karma value and have to choose other Qualities before finalization.

**Comment by joha4270** [comment]
I'm unsure what issue you are actually describing, so i cannot address the major point, as i don't see it.

On the other hand, i'm able to address a lot of the minor points.  
>Academic Knowledge: [Chemistry/Physics/Biology] +5   
This is already handled in code, a "blank" knowledge skill is added, locked to [lang/int/academ...] where a few options is possible to select. You can still cheat, but there are way worse ways for a player to cheat chummer and still have it take it as an acceptable sheet.

>Academic Knowledge: [Sociology/Psychology/Archaeology/Criminology/Politics] +13 (spread out among at least three subjects, minimum three ranks per subject)   
Giving the player 3 blocks that are min 3 skills while giving the rest as +1 skills, then letting the player merge skills. Not perfect nut works as well as the above.

>Players of gamemasters can create the moduls in advance. Or even anyone can create unique moduls and share in the forum.   
This has load of issues with distribution, i do not want to support players copy pasting into xml files and i don't want to create a new storage method less user prone, don't have web resources to store them in a central location

>So when a player would like to choose the "Community College - Social Sciences" he would able to >create a modul for it :  
>  
>Add Karma Cost : 100  
>Add Attribute -> Logic -> +1  
>Add Attribute -> Willpower -> +1  
>Add Active Skill -> Computer -> +1  
>Add Academic Knowledge -> Psychology -> +4  
>Add Academic Knowledge -> Archaeology -> +3  
>Add Academic Knowledge -> Criminology -> +3  
>Add Academic Knowledge -> Politics -> +3  
But the module is already there, why do players need to create it themselves? This kinda defeats the purpose of Chummer

>Even Tricky moduls can be created in advance, based on the books   
Just about every module from official books already exist, i don't see the point (a few things don't work but this system don't magically change that)

>Own, unique moduls can be created, in any type (ie: Nationalitiy, Formative Year, ect)  
Well, they can be too, right now the only difference is i'm using notepad to do it. (and it looks quite a lot like yours, just a little more verbose and structured)

>Variants of the existing Life Moduls can be created (I feel some of them weaker or stronger than the most, GM can strengthen / weaken them)  
Again, notepad can do this rather easy, and if you want to talk balance there might be better places to start than here. 

>A huge amount of moduls can be created by the community  
While i can, just as you, provide examples on stuff not existing in life modules, are there specific stuff  not present in life module that would not be  rebranded (we don't need both Tírs...)

>The interface should be containing the followings : ...   
Ignoring that this would be a huge amount of work, i still don't see the purpose of players creating their own modules, when the entire point of chummer is to do the math and data search for the players.

>Skills : Active Skills can be max 7, Knowledge max 9. Its clear, Chummer can limit them.  
YOU WANT TO USE THE EXISTING SKILL INTERFACE FOR THIS?  
no, just no, if you spend a minute thinking about what life modules contain and what the skill interface presents, you would realize why this would not work from a interaction perspective. Additionally this is not usable other places in the application due to architectural choices.


>Attribute : One can be the maximum at start. Which one ? The first which achieve it ? Maybe would be the best if you have to choose among them when you finalize the character..  
The one valid point i found.

>Doubled Quality ? Simply ignore ? Or player get the as Quality Karma value and have to choose other Qualities before finalization  
Run Faster provides explicit rules for how to handle this.

**Comment by chummer5a** [comment]
Just to expand on this a little, what I think you're asking for is a separate form that users could use to generate their own life modules, in a similar manner to the PACKs. While this would be a neat feature, it's not something we want to devote much time to currently. However, users do already have the capability to create their own data files that won't be overwritten by our changes. If you look in the Data folder, you'll see the XML files that make up the bulk of Chummer's content. Making a file called custom_lifemodules.xml will cause that file to be loaded along with the standard lifemodules file. You can use the documentation at https://github.com/joha4270/chummer5a/blob/master/Chummer/Documentation/Lifemodule.md and compare it to existing modules to make your own. 

If you need any assistance with making your own, or find issues with the existing ones, please feel free to raise another issue or contact me at chummer5isalive@gmail.com, and we'll see what can be done to sort it out.

**Comment by joha4270** [comment]
I should point out that the documentation on Lifemodule.md is rather incomplete and looking at the existing lifemodules.xml might be a better bet.
