### ISSUE TITLE
Lifestyle Configuration - Minor Text Inconsistency- Middle Lifestyle is incorrectly called Medium

### ISSUE THREAD

**Issue by Wenlocke** [chummer5a/chummer5a#3420]
In the lifestyle configuration and settings options, the program refers to a "Medium" lifestyle level. As per the rest of the game, and the rest of chummer, this should probably be "Middle"

**Comment by chummer5a** [comment]
Far as I'm aware it should be set to Medium everywhere; that's what it's called in Run Faster at least.

**Comment by Lochabar** [comment]
Maybe it's Run Faster that's wrong, because in the Core Rulebook p369 it states

MIDDLE
The Middle lifestyle offers a nice house or condo with lots of comforts. Characters with this lifestyle sometimes eat nutrisoy as well as higher-priced natural food, but at least the autocook has a full suite of flavor faucets. This is the lifestyle of ordinary wage-earners or reasonably successful criminals.
Cost: 5,000 nuyen a month

**Comment by Wenlocke** [comment]
The quality Creature of Comfort from Run Faster also describes a Middle lifestyle option. I assume this is mostly down to CGL crap editing. I think its been middle since SR1
