### ISSUE TITLE
Allow Edit Weapon Mount in Career mode

### ISSUE THREAD

**Issue by Nedorus** [chummer5a/chummer5a#3429]
**Describe the bug**
For one character the option for editing is not displayed. Other characters work fine.
When right clicking on the weapon mount the menu item doesn't show.
This happens for standard SR5 mounts added to drones (unsure whether it also happens with other mounts)

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Vehicle tab
2. right click on any of the weapon mounts
3. see the missing menu item

**Expected behaviour**
The option to edit the weapon mount should be displayed.

**Screenshots**
n.a.

**Character File**
This is the character file with the issues:
[Gregor - Andy Tseung.zip](https://github.com/chummer5a/chummer5a/files/2850456/Gregor.-.Andy.Tseung.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.204.49 (at least since 5.204.0)

**Additional context**
n.a.

**Comment by chummer5a** [comment]
Ah, that's because I never implemented a way to edit them in career mode. I couldn't figure out a cute way to handle the expenses.

**Comment by Nedorus** [comment]
Oh ... I understand. Why would the cost handling be different in career mode?
What is it technically that needs to be done? I'd be willing to help out if it's not too difficult it would be my first time implementation for chummer ;-)

**Comment by chummer5a** [comment]
Cost handling is actually super simple. Store the total cost of the weapon mount before we modify it, compare it to the total cost of the weapon mount that's returned from the creation form, if old != new, generate an expense from the delta and +/- your nuyen. Easy peasy. Unfortuantely this falls apart in career mode because of the Expense system; ordinarily, we can choose to Undo an Expense and the thing that we did is undone. It mostly doesn't work for this circumstance since we don't have a way to know what options were removed or added to the mount. 

The core method for the issue is tsUndoNuyenExpense_Click in frmCareer.cs. If you do happen to tackle it, I'd heavily prefer that tsUndoNuyenExpense_Click be refactored to move all the logic back into Classes\clsExpense.cs.

**Comment by Nedorus** [comment]
let me try my hands on it ... first time I look at your code and class structure ... also I'm not a C# person ... rather VB.net but should be OK. I'll take a look and when I decide I can fix it, then you'll receive a pull request to do a code review...
