### ISSUE TITLE
Implement something to visually show sustaining spells (and the foci that love them)

### ISSUE THREAD

**Issue by Vereaux** [chummer5a/chummer5a#3437]
**Describe the bug**
When I add a Sustaining Focus, it doesn't give me the option of what spell it's sustaining, or anything for that matter.

**To Reproduce**
1. Create a new character and keep all defaults (must be magic user though)
2. Go to Street Gear and add "Sustaining Focus, Health" (rating doesn't seem to matter for the original problem)

**Expected behavior**
When I add the focus, I would imagine you'd be prompted with "Which spell is it sustaining?" and you'd list the information for it. For example, I was trying to have it sustain "Increase Attribute - Body", and it'd increase the Body attribute (in parenthesis of course). Instead, I get nothing. Tried bonding the foci, and I get a prompt to choose a tradition from the list. The default selection is a string of random numbers and letters.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version: 5.204.48]

**Additional context**
I admit, I could be doing something wrong here, and I'm just blind with some feature I haven't encountered yet.

**Comment by chummer5a** [comment]
Chummer doesn't currently track Sustaining spells and complex forms. It's broadly supposed to be something that you do with the Notes field for lack of a more accurate way to handle it. It doesn't prompt you for what spell to use when you purchase the item since you don't have to keep the same spell in there forever. 

As a quick-and-dirty approach, you could just put the spell you're sustaining with it into the Notes field of the gear item.
