### ISSUE TITLE
FEATURE REQUEST: More Functional Ammo

### ISSUE THREAD

**Issue by chummer5hasanerror** [chummer5a/chummer5a#3441]
Requesting: Ammo Tab (or expansion of Ammo Functionality)

Present Issues:
-When attempting to Nest ammo inside of a magazine, the program is unable to locate the Ammo for purposes of loading a weapon
-When attempting to Nest a Magazine inside a stack of ammo, the program maths 1 bullet to 1 clip, causing a massive inaccuracy in actual cost
-When attempting to create Capsule Rounds loaded with DSMO or (_______) the program charges 1 dose per 1 capsule round, leading to a massive inaccuracy in actual cost.

Possible Solution:  Ammo Tab

Concept: A pre-populated list of all in game ammo.  
Relevant ammo can have an optional 'modification' feature (akin to what is presently done to Weapons and Armor in program) summoned via right click dropdown menu, which will enable adding additional options to the ammo (e.g hand loaded) the proper cost implementation of Nested Ammo (e.g Capsule rounds) and potentially introduce functionality for Alchemical Bullets at a later time.

Execution:
Add Ammo Tab, which contains full list of all basic Ammo (Regular, Gel, SnS, etc.) by default
User will 'purchase' ammo only from this tab. 
Program will need to:
1. check for possession of 'gun' (populating a Dropdown selection if needed) and any relevant mods (increase mag, krime pack, explosive magazine) on that specific 'gun'
2. reference size of magazine specific to gun, so that program will only compute in intervals relevant to specific firearm (e.g buying ammo only in increments of 6 for a Streetline Special, only in intervals of 15 for an Ultramax 70, etc) which includes purchase of magazine and.
3. Cross reference Drugs/Toxins as possible additions to Capsule rounds.  
3a. This may require implementing  a new House Rule choice consisting of the specific amount of ammo 1 dose of DSMO can effect, with checkbox to apply this effect automatically to the proper magazine size of the indicated weapon vs a static integer.

NOTES: 
-Additional implementation can include comparable functionality for Arrows and/or Grenades.
-Offers added benefit of being able to remove the massive grenade spam that populates duplicate info when using more than one 'flavor' of gas/paint grenades.

**Comment by chummer5a** [comment]
Strictly speaking there's not much reason to have a separate tab, most of the functionality for this can be achieved with the standard Gear tab and a check for if the selected item is Ammunition. That said, mutter mutter, lemme think.

New/Changed Functionality:
* Expand the Clip class to be a full object that exists separately to it being loaded in a weapon. Shunt the Extended Clip weapon accessories into this new class. 
* Ammo class becomes an extension of the Gear class; the WeaponBonus node for gear can be shunted into this class and separated out into specific properties. 
* Weapons would need to generate their base clip on create, with exception of weapons that don't use them (m, ml, etc.). Determine the extent to which parent state needs to be preserved (magazine size, weapon name, etc. Kind of weird to be able to load the spare clip of a holdout into a shotgun)
* Overhaul grenades. Allow for weapons to have a Quantity defined, and a property that dictates they consume themselves. Note that this should be separate to the Quantity property, as it'll allow things like Throwing Knives to stack their quantity without turning into ash when they're thrown. 
* Support for Hand Loading ammunition. Ideally I'd prefer to avoid implementing them with multiple variants based on the DV/AP options and whether they're store-bought or hand-made for the reduced cost, but since that's the simplest way to implement it it's likely what I'll wind up going with. 
* Some kind of user-facing Fill Ammo method that allows the user to convert empty Capsule ammunition into filled ammunition, consuming toxins and such in the progress. Include a number spinner for dilution and such; functionality should be data-driven as much as possible so that custom content can make poison-tipped arrows a thing or whatever. 
* Purchasing ammo in non-standard sizes is doable, but RAW they're all generally purchased in boxes of ten. That said, an option to automatically set the purchased amount to the number of boxes required to fill the selected magazine might be helpful.
