### ISSUE TITLE
Blood Magic Tradition is missing (German Version)

### ISSUE THREAD

**Issue by Mudcookie** [chummer5a/chummer5a#3478]
Hey there
There some Spells lost or missing in the german Version of Chummer, also the Blood Magic Tradition. Will it come back?
What is with the playable Mantis Variant in Heart of Darkness?

**Comment by chummer5a** [comment]
Chummer's core data is based on the CGL books, as I can't read German. Always happy to take pull requests for customdata though.

**Comment by Mudcookie** [comment]
it's missing in the englisch Version too. Blood Magic is not only in the german Books. Also the playable Mantis thing. Some Translations for the german Language are wrong, so maybe you guys need help with the Translations? :)

**Comment by chummer5a** [comment]
Take the Blood Magic Art, or enable the option to ignore Art requirements. Take the Sacrifice metamagic. Bam, you're a blood mage. I haven't implemented the free insect spirit quality because it offends me and I've been dragging my feet on it; it should be implementable without too much hassle, it's basically just a quality.

**Comment by Mudcookie** [comment]
So you don't like the Idea of playable Insect Spirits? And thanks for your help.  :)
