### ISSUE TITLE
Firewall cockblock

### ISSUE THREAD

**Issue by SnowZombie** [chummer5a/chummer5a#3513]
So my anti-virus program is sayin it wont oppe Chummer 5a v5.205
the reason is the file Trojan:W32/CryptoRansomwareBehavior.B!DeepGuard

i have just update my chummer through its own update system so someone who knows why this is happening

**Comment by MachineMuse** [comment]
This heuristic is likely triggered by a program which is not certified (chummer does not have the resources to get every build certified by Microsoft) downloading code from the internet and running it (the updater behaviour). It is a good idea for security software to block this kind of behaviour since it will catch Trojans that don't include hostile code in the initial file. There isn't really a way around this aside from whitelisting the chummer application.

**Comment by SnowZombie** [comment]
thank you very much
this has helped me understand what happened so thanks and have a good day

**Comment by Zitchas** [comment]
I'm not a virusscanner expert, so I have no idea what "CryptoRansomwareBehaviour.B!DeepGuard" means, but when in doubt, you can try submitting the file to:

https://www.f-secure.com/en/web/labs_global/submit-a-sample

As MachineMuse said, there are valid reasons for Chummer5's behaviour that might appear suspicious, but on the other hand, maybe somehow your particular download got infected somehow. It is worth a scan. 

It could also be worth downloading a fresh version from GitHub. There's been a few nightlies released since .205, and there's always a chance that it was actually some bug that has been fixed since then.

**Comment by ArchonMegalon** [comment]
It's even worse, because Chummer supports plugin's now and loads some dll only on request during runtime. That is also a common way to get malicious code to run, that is not there in the first place. If some heuristic is triggered by this sometimes, I wouldn't wonder.

**Comment by chummer5a** [comment]
Code signing won't sort this, not much that can be done about it otherwise.
