### ISSUE TITLE
Life Module previews

### ISSUE THREAD

**Issue by NATURE-1** [chummer5a/chummer5a#353]
Probably an unnecessary detail, but the Life Module selection screen could list a module's benefits like the Mentor Spirit screen does.

**Comment by joha4270** [comment]
Not going to come in the near feature, due to several reasons.

Well, the biggest is time. We (the developers) only have so much time to work on chummer, and other things take priority (mostly what hits our fancy, but there are rough ideas about what to change next). Won't change unless somebody bribes us or pays us :smile: (and that have other issues).

This data don't exists. Well, that is not true, but it is in a rather "technical" format, to be read directly by the improvement system. There isn't a way with the current improvement system to get the effects of any <bonus> node without adding it. It would be possible to write a parser for this data for display, but this would not happen in the near future.

Chummer don't intent to be a book replacement. The idea has never been to replace the books but to supplement them.
