### ISSUE TITLE
System.IO.IOException The pipe has been ended

### ISSUE THREAD

**Issue by Quintilium** [chummer5a/chummer5a#3535]
So I'm getting some weird bug where whenever i try to print a sheet as a pdf I get this message

![pipe has ended](https://user-images.githubusercontent.com/43793626/55300625-4115de80-5406-11e9-92c9-dea369ac6c2c.png)

In the end the sheet won't print, and I haven't the slightest clue what is going on

I'm using windows 7 64 bit if it matters

**Comment by chummer5a** [comment]
What's your application version?

**Comment by Quintilium** [comment]
5.205.0

**Comment by Quintilium** [comment]
> What's your application version?

5.205.0

**Comment by chummer5a** [comment]
Should be resolved in current commits.

**Comment by me0262** [comment]
Error occurs at line 265 in PDFConvert.cs, where the pipe ends prematurely.

264 :: byte[] buffer = Encoding.UTF8.GetBytes(document.Html);
265 :: objStream.BaseStream.Write(buffer, 0, buffer.Length);

Perhaps byte[] buffer = new byte[...GetBytes...]; ?

**Comment by me0262** [comment]
Got a notice because I was tracking this.
Before the pandemic happened we were on Shadowrun, and I was also getting this issue up to .209. This was in a VM under a clean install of Windows 10. I tried it with Adobe Acrobat and Foxit Reader. A friend's laptop that had Windows 7 and a "seasoned" system performed this function fine.
I'm wondering what the requirements for the PDF middleware are, if there's something a clean Windows system doesn't have. Perhaps a VCRT Library?
