### ISSUE TITLE
Quality list corrupted

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#3564]
**Describe the bug**
I have an existing character last updated using 5.205.26 on April 6. At that time the character had qualities:

Cyber-Singularity Seeker
Redliner
Sense of Direction
SINner (Corporate)

I just opened the character with 5.205.32 and the character now only has Cyber-Singularity Seeker.

What happened?

**To Reproduce**
1. Open the attached character file.
2. See the problem.

**Expected behavior**
The character file opens the way it was.

**Screenshots**
PDF of the character from 5.205.26
[Krieger.pdf](https://github.com/chummer5a/chummer5a/files/3059610/Krieger.pdf)

Qualities from 5.205.32
![Qualities](https://user-images.githubusercontent.com/17562417/55810962-ff440280-5aad-11e9-8972-b253588adcd0.png)

character file
[Krieger.zip](https://github.com/chummer5a/chummer5a/files/3059615/Krieger.zip)

**Desktop (please complete the following information):**
 - OS: Windows 7 Home
 - Version: 5.205.32

**Comment by ReallyDarkMatter** [comment]
After the bug is before the bug
I habe the same Problem with .32 the char is missing 6 Qualities. 
![image](https://user-images.githubusercontent.com/12108972/55817003-d5adca00-5af3-11e9-83eb-dfcc7963ac99.png)
Messing is:
- Albinism 2
- Glamour
- Ghostwhisperer
- Friends in high Places
- Symbiosis
- Magician
- Creature of Comfort(Middle)

The qualities seem to be still present, as i an not add them

**Comment by chummer5a** [comment]
I see the problem, should be fixed in next nightly.
