### ISSUE TITLE
ghouls starting with 0 magic 

### ISSUE THREAD

**Issue by Edrial1** [chummer5a/chummer5a#3577]
Picking up the quality "infected: Ghoul (elf in this case)" on a character that started out as a mundane reduces essence by 1 but doesn't add 1 magic (you have 0 magic after picking up the quality)

**To Reproduce**
create mundane character, add "infected: ghoul" quality

**Expected behavior**
Essence reduced to 5, magic increased to 1 

Windows 10
Nightly-v5.205.7

**Comment by chummer5a** [comment]
Working per RAW. Purchasing qualities happens at step 4, purchasing items happens at step 6.  You'll find that during career mode this doesn't happen and you're given your magic rating as per normal.

**Comment by Luciferos** [comment]
> Working per RAW. Purchasing qualities happens at step 4, purchasing items happens at step 6. You'll find that during career mode this doesn't happen and you're given your magic rating as per normal.

This is wrong and has nothing to do with purchasing items (???)

A strain II/III Infected coming out of character creation should have 1 MAG, because the starting Essence and Magic for all strain II/III Infected who were mundane before is 5 ESS, 1 MAG. They both lose an essence -and- gain 1 MAG, and should have 1 MAG forever after that fact unless their ESS/MAG is further changed by something.

This is explicitly stated with absolute clarity in Run Faster, pp. 141:

![5d59b9718b3b02c5b51dce10fc2b2789 1](https://user-images.githubusercontent.com/20429868/56632653-cd43ac00-6628-11e9-8d95-42a50913500c.png)

Possibly need to set cgen Strain II/III to 5 Essence/2 MAG so they properly reflect their Magic level of 1.

**Comment by doktorJung** [comment]
I just ran across this issue as well, I don't see my character's Magic increase to 1 when I'm starting with a E priority in Magic/Resonance.
