### ISSUE TITLE
Chummer crush after opening options

### ISSUE THREAD

**Issue by ARgits** [chummer5a/chummer5a#3635]
### Environment
Crash ID: 2db0c696-1f7c-4cbe-b9df-71299eb0fc6e
Chummer Version: 5.205.65
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
options opened

### Actual behaviour
chummer crushes. Tryed several versions, still the same. Also, on windows 8.1 everything works fine (so now i just export options file from laptop with 8.1 to my laptop, if i need to do some changes)

### Steps to reproduce the behaviour
Launch chummer, try to open the options.

**Comment by DecklandMulqueen** [comment]
205.26 crashes whenever i try to save changes

**Comment by DecklandMulqueen** [comment]
205.65 ... sorry

**Comment by chummer5a** [comment]
There should be a crash log on your desktop, can you show me the contents of that file?

**Comment by DecklandMulqueen** [comment]
The problem was solved with 205.69 !!

I am able to save my character files !!

 

THX

 

Von: Chummer 5 Is Alive <notifications@github.com> 
Gesendet: Samstag, 11. Mai 2019 15:11
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Comment <comment@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Chummer crush after opening options (#3635)

 

There should be a crash log on your desktop, can you show me the contents of that file?
