### ISSUE TITLE
Lifestyle Workshop/Facility not covered by High+

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3660]
**Describe the bug**
The lifestyle quality "Workshop/Facitliy" (and Cramped version) is covered by Medium+ lifestyle.

Chummer erroneously interprets this as _only_ covered by Medium, and _not_ covered by High and Luxury lifestyle.

**Expected behavior**
Workshop/Facility cost should be covered by all lifestyles above Medium.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.205

**Comment by Luciferos** [comment]
This bug report is inaccurate. Chummer does calculate this lifestyle cost incorrectly, but the above Expected Behavior is wrong.

![image](https://user-images.githubusercontent.com/20429868/57959125-4fde2500-78d0-11e9-9f99-6cd72002ce26.png)

In actuality, because of the way Chummer budgets lifestyles, it shouldn't be covered by any lifestyle other than Commercial. Your lifestyle must "include" Commercial to cover Workshop/Facility - which in Chummer5 means you must purchase a Commercial lifestyle. Verified via the Run Faster errata that this was not an errata to make it function as OP describes.

**Current Incorrect Behavior**: NuYen cost of Cramped Workshop/Facility and Workshop/Facility are covered by Medium lifestyle and Commercial lifestyle.

**Expected Behavior**: NuYen cost should only be covered by Commercial lifestyle.
