### ISSUE TITLE
Editing the category of spells in the xml has no effect

### ISSUE THREAD

**Issue by Erkusandor** [chummer5a/chummer5a#3774]
When i edit the .xml file spells.xml and change the category of a spell (i.e. Growth) from one category to another (i.e. from Health to Manipulation) the spells still shows up in the old category.

**Comment by DelnarErsike** [comment]
I cannot seem to replicate this issue. Are you sure you are restarting the program between edits so that the new data can load?

By the way, we discourage editing of the base data and instead recommend you use custom data files instead. In the case of your Growth change, there is even already a custom data folder ready-made for that change, just look at "German Data Changes - Growth Spell Category" in Tools > Options > Optional Rules.

**Comment by Erkusandor** [comment]
Yes, i do close it between the changes (the popup is hard to miss). The custom data folder is likely the cause of this error (as i have enabled it and obviously a change in the custom will overwrite the base data). Thread can be closed, thanks!
