### ISSUE TITLE
Black Market Pipeline Categories

### ISSUE THREAD

**Issue by ChopperSniper** [chummer5a/chummer5a#3838]
**Is your feature request related to a problem? Please describe.**
It would be useful to have Black Market Pipeline have more than just the seven given categories in the program, at least allowing custom ones. Can't do custom categories which is a bit of a pain.

**Describe the solution you'd like**
Using licenses as an example, licenses have a dropdown list to choose from. But you can also just click the dropdown menu and without selecting another license, type in your own license. Something like that might work for Black Market Pipeline.

**Describe alternatives you've considered**
A blank value might work instead, but then there's also a small problem of me not knowing if that would mess with the code of Chummer and the Black Market Pipeline checkbox on items.

**Comment by chummer5a** [comment]
Custom entries for black market pipeline are supported through the custom data system, since there isn't a 1:1 mapping for RAW allowed categories. To add a custom one, you need to add a new node to options.xml and the relevant XML file you're editing. For example, adding a custom black market mapping for Food would require:
amend_options.xml
```
<chummer>
  <blackmarketpipelinecategories>
    <category amendoperation="addnode">Dumpster Diving</category>
  </blackmarketpipelinecategories>
</chummer>
```
amend_gear.xml
```
<chummer>
<category blackmarket="Dumpster Diving">Food</category>
</chummer>
```
