### ISSUE TITLE
Aspected Magician free spells/Rituals/etc

### ISSUE THREAD

**Issue by Ryu-ken** [chummer5a/chummer5a#385]
When I create an aspected magician, the rules on SR5, p. 69 state that I should get (magic rating x 2) free spells/rituals/preparations. I don't get any free spells etc. at all.
A friend of mine can reproduce this problem, he doesn't get any free spells either.

**Comment by joha4270** [comment]
• At character creation, aspected magicians who cast spells,
perform rituals, or create alchemical preparations may know
a **maximum** number of formulae from each group equal to
their Magic Rating x 2 (SR5, p. 69, emphasis mine)

Unless you can provide errata stating otherwise, this won't be changed
