### ISSUE TITLE
Issue: - Only Metasapients available for race selection

### ISSUE THREAD

**Issue by cuckooman** [chummer5a/chummer5a#3880]
### Environment
Crash ID: 34db352a-6c85-47a4-97ee-fbc2e909e830
Chummer Version: 5.208.20
Environment: Windows 10 Enterprise
Runtime: 4.0.30319.42000
Option upload logs set: Trace
Installation ID: dc6b1cdb-ef60-47ab-98a0-5ed777fdf5e3

### Expected behaviour
Ability to switch between Metasapient, Metahuman and Shapeshifter race tabs.

### Actual behaviour
Only Metasapient tab available. Attempting to set Race priority below C results in a crash.

### Steps to reproduce the behaviour
1. Open the Create Character menu in any Sum-10 or Priority gen mode
2. Click on 'Metasapient' (you should see nothing else there)
3. Attempt to change Race priority to lower than C.
4. Observe crash

**Comment by cuckooman** [comment]
Oh yeah, one other thing. Characters with a non-metasapient race that are already created seem to work fine.

**Comment by chummer5a** [comment]
This tends to be caused by conflicting customdata rules. Suggest you check that all the customdata rules are disabled and/or open your registry, navigate to HKCU\Software\Chummer5\CustomDataDirectory and either delete all the folders, or navigate through each subfolder and ensure that Enabled is set to False.

**Comment by cuckooman** [comment]
Fixed. Turns out that enabling Point Priority Chargen was a baaad idea.

**Comment by chummer5a** [comment]
Found the problem, will be fixed in the next nightly.
