### ISSUE TITLE
Program running a bit slow

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chummer5a/chummer5a#39]
```
I'm noticing that the program is taking a long time to add points and other 
changes to the character in both priority and sum to ten.


Try adding attribute points. There are a few stops and starts.

v5.157
Win8

```

Original issue reported on code.google.com by `rashidi...@gmail.com` on 7 Mar 2015 at 6:54

**Comment by chummer5a** [comment]
Issue determined to be firewall-related issue on client PC.

**Comment by BodieSullivan** [comment]
I also am encountering this slowness. I can run an older version of chummer5 and the most recent version of Chummer5a side by side and there is a significant delay in the Chummer5a version. It makes entering in stat and skill levels excruciating. I have localized the slowdown to the UpdateCharacterInfo() method in the frmCreate.cs. It is called in every instance of updating skills and stats. I have not yet had a chance to narrow down the performance sink any further, but I am confident it isn't caused because of firewall related issues. How was the issue determined to be a firewall-related issue on the client PC?

I am using Windows 8.1 with the firewall turned off.
I have a 3.5Ghz Intel i5 CPU with 16GB ram and a solid state drive. 
There shouldn't be this level of lag due to a slow system.

I have also encountered the lag on a windows 7 laptop.

**Comment by chummer5a** [comment]
According to testing from another user, the fault was caused by Windows Defender firing whenever a change occured in Chummer. Creating an exception in that application resolved the error. So not firewall, per se. Wasn't paying much attention. So far I've been unable to replicate the issue using a variety of laptops and tablets.

UpdateCharacterInfo() is a bit of a beast of a method, but breaking it apart would be time-consuming and add to re-work when altering and adding new methods. I'd be inclined to guess that there's a specific combination of character details that triggers the slowdown.

**Comment by BodieSullivan** [comment]
Hey thanks for the extra info! It was Windows Defender causing the slowdown. Creating an exception in defender for the entire Chummer5a folder fixed the issue.

**Comment by chummer5a** [comment]
Cheers, glad to hear it's working okay for you now!

**Comment by cjrt** [comment]
I feel this should be added to the main page. "If experiencing slowdowns,
add an exception to windows defender" kinda sounds shifty, oh we're not a
virus - just don't scan us! But in a FAQ could prevent this issue coming up
again?
