### ISSUE TITLE
Armor Calculation is Incorrect for Drake Build

### ISSUE THREAD

**Issue by RavenDarkblood** [chummer5a/chummer5a#3925]
When building a Drake PC (Western-Type) the armor calculation only adjusts for Hardened Armor and not the other armor modifiers. 

Choose Dracoform (Western) in Qualities
Select the following Critter Powers:
> Hardened Armor (2) [included with Drake]
> Hardened Mystic Armor (2) [included with Drake]
> Heavy Scales (optional for western Drake)
> Improved Natural Armor (optional for Drake)

Your armor, without gear, should be: Hardened Armor (3) [2+1 for INA] + Hardened Mystic Armor (3) [2+1 for INA] + Heavy Scales (2) = 8 armor. (I think)

[Robert Smith-Drake.txt](https://github.com/chummer5a/chummer5a/files/3801205/Robert.Smith-Drake.txt)

![Chummer Drake Armor Bug](https://user-images.githubusercontent.com/21364883/68080033-d973a780-fdc9-11e9-8267-bfacb58a8687.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.208.0

**Comment by chummer5a** [comment]
HMA we don't do anything with, since there's currently nothing in place for astral defence. INA and HS aren't doing anything because of an issue with how improvements are managed for critter powers. Looking into that now.

**Comment by AGulyaev12** [comment]
Could you please add some sort of "Shift" button, so nobody is confused with Armor Values. Pressing this button would result in switching to you "other side's" pagу with all the bonuses added. "The real you" page in that case can be left without bonuses of the form in brackets at all. Cause HMA only works with astral combat and doesn't affect the real world armor. HMA and HA don't stack. I'm playing as Western Drake Adept  and have the same issues as RavenDarkblood with constant calculation of my AV. As you can see the Chummer calculates both of my armors as bonuses. Moreover INA doesn't work as bonus and I still have only bonus os 2 instead of 8. 
![Безымянный](https://user-images.githubusercontent.com/58299450/69812736-ce156f80-1201-11ea-9407-fe3ff8f39851.png)

**Comment by chummer5a** [comment]
Like I said, INA doesn't work at the moment. Form-based management is something I'll need to look into at a later date, it's not in scope for the moment.

**Comment by AGulyaev12** [comment]
It's good to know that you're aware of this issue and it's in scope at all. You're doing a great job and I really relish it !
