### ISSUE TITLE
update 5.211 to 5.212 don't happen

### ISSUE THREAD

**Issue by Noraser** [chummer5a/chummer5a#4113]
**Describe the bug**
Update from 5.211.0 to 5.212.0 can be downloaded and install started. (with new start)
But with new start 5.211.0 starts again and error showing:
there can't be updated as secound instance is running. 
Seen on both Computer

**To Reproduce**
check for update
download
click install and restart
restart schows old version

**Expected behavior**
update of SW and start of new version

**Desktop (please complete the following information):**
  Windows 10

**Additional context**
Most settings to German version

**Comment by SeanPGorman** [comment]
me too.

**Comment by Lochabar** [comment]
Additionally the latest nightly email came thru referring to 5.211.0 (not 5.212.x) and the link to the release page gives a 404 error. 

  | Nightly-v5.211.0Repository: chummer5a/chummer5a · Tag: Nightly-**v5.211.0** · Commit: 89ec9cc · Released by: chummer5a—This release has 3 assets:Chummer.Nightly.zipSource code (zip)Source code (tar.gz)Visit the release page to download them.—You are receiving this because you are watching this repository.View it on GitHub or unsubscribe from all notifications for this repository.
  |

**Comment by phoff** [comment]
I actually installed 5.212 on a fresh Windows install, and I'm getting this error. It identifies itself as 5.211.0 in the title bar, so it might just be that the internal version number got screwed up.

**Comment by chummer5a** [comment]
Uploading replacement binary folder now. Assembly patching didn't work properly.
