### ISSUE TITLE
Issue: - Crash after making character complete

### ISSUE THREAD

**Issue by zcauld** [chummer5a/chummer5a#4121]
### Environment
Crash ID: 01fd1a86-d4ab-4851-bcdd-dbb8e68fb42d
Chummer Version: 5.212.8
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 6f8cc270-2a09-4d1e-850a-452dec8610ca

### Expected behaviour
don't know - I haven't been able to get this to work

### Actual behaviour
Crash

### Steps to reproduce the behaviour
click the ckeckbox and save the character
![crash_trace](https://user-images.githubusercontent.com/36544657/82944602-20410e80-9f61-11ea-868c-b7f4cd58bb6f.JPG)
[chummer_crash_132349957421826468.txt](https://github.com/chummer5a/chummer5a/files/4684716/chummer_crash_132349957421826468.txt)
[chummer_crash_132349957134212648.txt](https://github.com/chummer5a/chummer5a/files/4684717/chummer_crash_132349957134212648.txt)

**Comment by Akefal** [comment]
Same here.

**Expected behavior**
Save to career put character in career mode.

**Actual behavior**
Save to career crash chummer and corrupt character file. Trying to open that character after that crash chummer aswell.

**Step to reproduce the behavior**
Create a brand new character and try to save it in career mode.
[chummer_crash_132350684214704231.txt](https://github.com/chummer5a/chummer5a/files/4691098/chummer_crash_132350684214704231.txt)
[chummer_crash_132350687620631729.txt](https://github.com/chummer5a/chummer5a/files/4691100/chummer_crash_132350687620631729.txt)
[chummer_crash_132350691190524644.txt](https://github.com/chummer5a/chummer5a/files/4691101/chummer_crash_132350691190524644.txt)
[chummer_crash_132350692386260731.txt](https://github.com/chummer5a/chummer5a/files/4691102/chummer_crash_132350692386260731.txt)
[chummer_crash_132350699696940082.txt](https://github.com/chummer5a/chummer5a/files/4691103/chummer_crash_132350699696940082.txt)

**Comment by chummer5a** [comment]
Should be working in the latest nightly, I believe.

**Comment by Akefal** [comment]
Yep it works fine with the 5.212.10 ! Thanks a lot for your work !
