### ISSUE TITLE
After adding a Medium Livestyle, Chummer displays Error while saving Char

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#4174]
**Describe the bug**
Chummer 5.212.83
Windows 10
**To Reproduce**
1. Go to Streetgear and add Livestyle, i tested Medium and Luxury
2. Save the char
3. See this error
![image](https://user-images.githubusercontent.com/12108972/88077461-96d24500-cb7b-11ea-9b76-8fe9ca52c0d7.png)

"Save as" also don't work

After removing the Livestyle again, i can save the char again.

**Expected behavior**
 Be able to save char with a livestyle

Just got the same error after adding Mortimer of London: Berwick Dress to char

**Comment by ReallyDarkMatter** [comment]
Just got the same error after adding Mortimer of London: Berwick Dress to char

**Comment by ReallyDarkMatter** [comment]
Interesting thing can add Berwick Dress on a System with Intel CPU without error.
But on AMD Ryzen i get that error

**Comment by MrCkurab** [comment]
Had the exact same issue multiple times over the last couple of days, only started happening after I updated to version 5.213.0 of Chummer on a Windows 10 System.
Happens both with completely new Characters and older ones that were created with previous versions of Chummer.
Happens also with tons of Armor items, as soon as you add them, saving becomes impossible until they are deleted again.
Affects, among others:

- Ballistic Mask (both versions)
Armor Vest
Actioneer Buisnessoutfit
Padded Coat
Mortimer of London: Argentum Coat
several more that I dont remember

I even have one Character that can be saved without issues (because I avoided the items mentioned above) but I cannot save said Character in Career mode as I always get the above issue, "Error during saving" when I try so I cant even transfer the Character in Career mode and adjust things there.
With other Characters, the Issue pops up in Carrer mode as well, adding a Lifestyle is possible but, again, makes it impossible to save the Character until is is deleted again, which, at that point, does not refund the costs anymore.

This issue makes it nearly impossible to properly create new Characters as I cant add any Lifestyle and have to avoid many common Armor elements. 
I tried re-downloading the latest update and having a clean reinstall of Chummer, sadly that changed nothing at all.

Regarding Processor: I use an Intel Xeon 1231, not an AMD Ryzen or the like.

If any other Details are needed, please tell me ASAP and I will try to get them to you!

**Comment by CarnVanBeck** [comment]
5.213.0
I get the same error when adding a silencer to an Ares Predator oder adding armor. Tried the Nightly-v5.213.25, was able to add the armor but not the silencer.
I tried it with the english interface and it worked.

**Comment by ReallyDarkMatter** [comment]
Mostly likely the error is in the notes.
It is the ligatures, search for missing charakters "fi"

**Comment by chummer5a** [comment]
Should be resolved in current nightly builds.
