### ISSUE TITLE
Chummer nightly 5.212.X Scaling problem MDI child

### ISSUE THREAD

**Issue by OLRobert** [chummer5a/chummer5a#4211]
Dear Chummer community. 

**Describe the bug**
Whenever I open the fourth character the app closes immediately. 
"chummer_crash_132429415542227682.txt" gets created but does not show any content. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open last nightly
2. Open Character 1, 2 ,3 and 4 
3. Chummer closes. 

**Expected behavior**
The fourth character should get opened to show me all of my teammates characters. 

**Screenshots**
I am sorry, but the ap just closes. 

**Desktop (please complete the following information):**
 - OS:  Windows 10 latesd]
 - Version: 5.212.123

**Comment by DelnarErsike** [comment]
Unable to replicate. I tried opening four characters at the same time with the latest Nightly, and aside from taking a long time to load all four characters, Chummer was able to open them all up just fine.

**Comment by OLRobert** [comment]
Hi there. 

Please excuse my late reply. 

Just tried using 5.212.123 again.
It takes "a lot of time" just to open chummer. 
From top to bottom - crashed and the chummer_crash_132438683655682846.txt contains one empty line. 

After this first  crash, it came up, offering an update and I installed version 5.212.134.
Reproducing by opening top to bottom 
Manni, Secret Warrior, D and Blue. 
Manni took 12 seconds
Secret Warrior 12 Seconds and came up in a "fractured" window -> See 2.jpg
![2](https://user-images.githubusercontent.com/42408066/92325829-e5fe0780-f04d-11ea-9fa3-47fc0857d665.jpg)
I maximised this window. 
D took 12s and got opened in a fractured Window, too. -> see 3-jpg
![3](https://user-images.githubusercontent.com/42408066/92325938-b6033400-f04e-11ea-98aa-bdc37c79227e.jpg)
I maximised this window as well. 
Blue could not get opened and chummer got closed aftert 36s. 
chummer_crash_132438696340039722.txt contained a single empty line. 

Opening characters from bottom to top.. 
Blue -> 12s and opened in "full screen" -> 4.jpg
![4](https://user-images.githubusercontent.com/42408066/92326000-3164e580-f04f-11ea-8f12-b3d09b6c0892.jpg)
D -> 12s and fractured.
Secret Warrior -> 12s and fractured 
Manni -> crash after round about 35s. 
chummer_crash_132438698691437182.txt -> single empty line. 

I opened chummer again which took round about 30s.
Secret Warrior -> 12s and fine.
D -> 12s and fractured
Blue -> 12s and fractured 
Manni -> crash after round about 11s 
chummer_crash_132438702470293409.txt just one single empty line. 

These are the characters:
D: 
[D-Final.zip](https://github.com/chummer5a/chummer5a/files/5179656/D-Final.zip)
Manni:
[Bolle_Rigger_v5.zip](https://github.com/chummer5a/chummer5a/files/5179659/Bolle_Rigger_v5.zip)
Blue:
[Blue.zip](https://github.com/chummer5a/chummer5a/files/5179661/Blue.zip)
Secret Warrior:
[Secret Warrior.zip](https://github.com/chummer5a/chummer5a/files/5179665/Secret.Warrior.zip)

Logging including detailed reporting is enabled and I opened
Blue, Manni, Secret Warrior and D. 
chummer crashed and chummer_crash_132438711232865373.txt shows one empty line. 

Best regards and thanks.

**Comment by OLRobert** [comment]
Hi there. 

Just updated to 5.212.137:
Opened 
Blue    -> 12s later everything is fine.
D        -> 12s later the character is opened in a fractured window.
Mani   -> 12s later the character is opened in a fractured window.
Secret Warrior -> Chrash happens way earlier, round about 10 to 15s and 
chummer_crash_132441466137470970.txt
contains a single empty line. 

Just fyi and thank you very much.

**Comment by OLRobert** [comment]
Just deleted all chummer related content in my machine's registry and opened two characters. 
D followed by Manni -> Chummer crashed. 
There wa sno "optimization" and there were no additional rules enabled at all. 
chummer_crash_132441481445467629.txt shows an empty line.

**Comment by OLRobert** [comment]
After re-opening chummer i am facing the old situation.
It is not possible to open more than three characters.

**Comment by ArchonMegalon** [comment]
Okaaaay - this is a shitty thing for us to fix. There is a hard limit of 10.000 handles. Since we create the skills on the fly using handles, they solution would be to dispose them. 

![image](https://user-images.githubusercontent.com/11421547/92718714-7a27e180-f362-11ea-95cb-a7c2dfcbf0b9.png)

https://www.codeproject.com/Questions/891193/Error-creating-window-handle

@DelnarErsike since you added the onewaydatabinding: any ideas how to get around that hard limit. I'm pretty sure, the 4 characters don't have 10k skills, but we for sure have a lot of other controls also generating handles. 

Also this Win32Exception can't be catched. The program just crashes to desktop. 

Maybe we need to add a counter of all the handles created and start to unload controls in the background if we get to high?

**Comment by DelnarErsike** [comment]
Hmm, we could increase the GDI handle limit, but that's kind of a temporary solution, as it'll just cause the program to crash with 18 or so characters open instead of just 4:
https://docs.microsoft.com/en-us/windows/win32/sysinfo/gdi-objects

I think we need to think about how to reduce the number of handles we need overall. `DoOneWayDataBinding` isn't really the specific culprit here, as it's just a copy of `DoDatabinding`. As far as I can tell, it's also not a memory leak issue, as the unit tests that go through creation of `frmCreate` or `frmCareer` for the 30+ test characters we have doesn't run into this issue, so handles are getting disposed correctly when they're no longer necessary. The culprit AFAICT is the sheer number of controls that are being used, as every single control is a separate GDI object and therefore ends up needing its own handle. A lot of this could be due to me setting up BindingListDisplay to be able to handle controls with different vertical sizes, as well as me adding the massive amount of extra, auxiliary controls, especially to contact, active skill, and knowledge skill controls. But AFAICT, the majority of those were necessary because of WinForms formatting bugs, especially related to TableLayoutPanels with %-based width/height for certain columns/rows when you have certain items also spanning multiple columns/rows. So solving this issue is probably going to be a pain.

**Comment by OLRobert** [comment]
Dear chummer team. 
I just updated to 5.212.151, performing a clean reistall. 
Opened Blue and got asked to re-enable optional rules. 
After restart, Blue can get opened. 
D, as well. But comes up fragmented. 
So I maximized this character.
Bolle got opened fragmented. 
Jack made chummer crash. 

I had debugging enabled and you might have received something. 

chummer_crash_132453570901201838.txt 
![image](https://user-images.githubusercontent.com/42408066/94050263-50e16980-fdd6-11ea-9254-4f0cdc485de3.png)
shows one single empty line, as usual.

**Comment by DelnarErsike** [comment]
The controls not being docked properly is extremely odd and not something that I have seen before. It may have to do with the MdiClient system misbehaving, I'll have a closer look later once I've sorted out something else about Chummer.

In the meantime, some manifest program stuff was tweaked for 5.212.156 which should at least hopefully sort out the scaling issues that seem to be causing the weirder layouts that some of the screenshots show.

**Comment by OLRobert** [comment]
Just updated to latest nightly. 
Whenever I close chummer, after opening "Blue", it ends in a new crashfile. 
chummer_crash_132459660171068508.txt
Is an empty file.

**Comment by liquidmorpheme** [comment]
For what it's worth, I've been having these same issues (including the fractured window on character open) for about 2 months. I would add to it that dragging the Chummer window is weirdly slow and "floaty". Additionally the Options menu is quite buggy and often doesn't display correctly
<img width="1031" alt="Capture" src="https://user-images.githubusercontent.com/42921707/94748950-93fc8900-0350-11eb-829a-795eba6d716a.PNG">

**Comment by OLRobert** [comment]
Another update on this:
Closing "Blue" via 
File -> Close makes Chumer rash, creating an empty log as usual. 

Did my group just create shitty characters?

**Comment by ArchonMegalon** [comment]
On the contrary. Great chars for us to finally be aware of the problem! ;)

**Comment by OLRobert** [comment]
Let me add the strangest char:
Butt, an NSC
[Butt.zip](https://github.com/chummer5a/chummer5a/files/5343353/Butt.zip)

**Comment by OLRobert** [comment]
Just updated to Chummer5a 5.12.170
It takes a long time, wich is > two minutes to load the tool itself. 
![image](https://user-images.githubusercontent.com/42408066/95688769-dce3f580-0c0c-11eb-9445-824d597a6fb4.png)
Loading all stuff takes that long. 
My PC offers "sufficient" performance and I do not see a bottleneck in any of it's components. 

Loading "D" comes up showing 
![image](https://user-images.githubusercontent.com/42408066/95688822-2cc2bc80-0c0d-11eb-90f5-53309c153c35.png)
Which happens since adding all optional rules required to open "Buttt". 
Opening "Blue" takes 11s and he is not "fractured" - Thank you!
Opening "Secret Warrior" comes up 
![image](https://user-images.githubusercontent.com/42408066/95688877-73b0b200-0c0d-11eb-8f44-18ffc1dfbeb1.png)
Well, this book is activated.
This Character opens, not fractured. 
Opening "Manni" shows
![image](https://user-images.githubusercontent.com/42408066/95688895-9c38ac00-0c0d-11eb-9100-8215b4353f0c.png)
and Chummer crashes. 
chummer_crash_132469202337965138.txt
is an empty file
![image](https://user-images.githubusercontent.com/42408066/95688920-bf635b80-0c0d-11eb-8d6f-c207b4addd40.png)

**Comment by OLRobert** [comment]
Dear Chummer Team.

Just updated to 5.212.172
Starting the tool takes "forever". 
And I measured it. 
In this case, "forever" is 
![image](https://user-images.githubusercontent.com/42408066/95901407-92d94c00-0d93-11eb-927a-73708b20c595.png)
until chummer is loaded completely.
plus a very short amount of time I required moving the cursor from my chummer desktop icon to the clock. 

It remains crashing by opening fourth character, no matter in which order.

**Comment by OLRobert** [comment]
Updated to 5.212.173
Same situation chummer_crash_132471782654764052.txt
is an empty file.

**Comment by OLRobert** [comment]
Hi There. 
Just updated to 5.212.180.
Tool is up and running after less than four seconds!
What a change!

Thank you so much!

Secret Warrior is opened after round about 12s. 
Blue, and Eve are opened in the same time. 

No character is shown "fragmented".

Opening fourth character crashes Chummer and 
chummer_crash_132477830322479346.txt got created as usual. 
Empty file.

**Comment by OLRobert** [comment]
It looks like a "Crean instalL" does not replace the chommerprofile which ends in an "configured" Chummr, which is not "clean". 

I deleted the "chummerprofile" and it got replaced. 

I downloaded
Chummer5.212.0.zip,
cleaned all chummer related registy keys,
extracted the ZIP, 
copied the files into my folder and opened 
Chummer 5a 5.212.0.
Tools -> options -> "Use logging" = "upload detailed logs"
OK -> Yes / Yes 
Opened Characters:
D-Final.chum5 -> ignored all missing books 
Bolle_Rigger_v5.chum5 -> ignored all missing books 
Blue.chum5 -> "Incorrect Game Version" as it was stored using 5.212.123 -> Yes -> ignored all missing books 
Secret Warrior.chum5 -> "Incorrect Game Version" as it was stored using 5.212.123 -> Yes -> ignored all missing books 
Chummer did not crash!
Butt.chum5 -> ignored all missing books 

I am able opening five characters without using my "standard" chummer config. 
This means: There is an incompatibility in either the characters, or in my "config", or in the way Chummer 5a uses the rules. 

Tools -> Options -> enabled "Automatic Updates" & "Prefer Nightly Builds" -> Yes -> Yes
Update is available -> Yes
Ignored all missing books / error messages due to outdated chummer version 
-> chummer_crash_132477847158086788.txt got created and chummer got restarted showing up in Version 5.212.180

Chummer crashes opening the third character -> chummer_crash_132477848984890617.txt got created as empty file

Opened Chummr 5a 5.212.180 again
Opened Characters 
D, Secret Warrior, Blue 
ignoring all missing configurations / books and it crashed by opening Manni.
chummer_crash_132477850670225477.txt got created. 

Which means, even without any additional configuration, chummer crashes opening these characters. 

My rpg team has created characters making chummer crash :-) 

I really appreciate all the work you spend i chummer 5a!

Thank you for keeping this great tool alive. 
And thank you in assisting my group in using their characters via chummer. 

What can I do assisting you in solving this issue?

**Comment by DelnarErsike** [comment]
Hmm, did it crash when you had the program set to use English? And/or do you have your Window Scaling set to something other than 100%? Because I can load and have open all of your characters just fine, and I'm not generating the thousands of handles that are presumably causing your crashes, and I'm running the default config as well, so I have to assume it's one of those two things that are causing the massive amount of handles that end up causing Chummer to crash.

**Comment by ArchonMegalon** [comment]
I noticed two things in the latest nightly that may be help/be related here: 

First: Somehow the Icon of the MasterIndex and the frmCharacterRoster are in the wrong menu:

![image](https://user-images.githubusercontent.com/11421547/97070886-1c7eea00-15dc-11eb-8520-7102096d6e4c.png)

Also - scaling doesn't work. Normally I have my Laptop at a 1080p resolution with 100%. Switching to 4k with 250% looks like this:

![image](https://user-images.githubusercontent.com/11421547/97070901-4801d480-15dc-11eb-88ab-13badfb701fc.png)


On the plus side: the handels are down...

**Comment by OLRobert** [comment]
Hi there. 
Thank you very much for your support!

I am running Chummer 5a Version 5.212.187 on a 4k screen using 150% scale. 
These are my settings:
![image](https://user-images.githubusercontent.com/42408066/97481649-686fbd00-1955-11eb-87d0-88e038cc145d.png)

@DelnarErsike, I have the program set to English. 
Last weeks crash file  chummer_crash_132477847158086788.txt  was created using English but scale ot 150%.
I changed Scale to 100% and opened Chummer again. 
Well, it looks like Chummer has stored the scaling somewhere as it came up looking like:
![image](https://user-images.githubusercontent.com/42408066/97482193-22672900-1956-11eb-87f7-08cd77667fd4.png)
I closed Chummer and cleaned the registry of my PC. 
It looks like Chummer stored the scale somewhere else as it came up like this:
![image](https://user-images.githubusercontent.com/42408066/97482580-a0c3cb00-1956-11eb-8107-827152719c90.png)
Moving the tool over to an FHD screen with 100% scale made it looking like
![image](https://user-images.githubusercontent.com/42408066/97482720-ce107900-1956-11eb-8556-2b5cc15f2078.png)
Opened Eve. ignoring all errors -> 
![image](https://user-images.githubusercontent.com/42408066/97482809-eda7a180-1956-11eb-9617-82f3f277d1a3.png)
Opened Bolle, ignored all errors, which took a while, -> made it appearing in the style Eve got opened. 
Opened Blue, ignored all errors-> Opened it
Opened Secret Warrior. ignoring all errors, made Chummer crash->
chummer_crash_132483848086145712.txt got created as an empty text file. 

@ArchonMegalon, Jep, it looks like Scale is not "handled" correctly as I just realised. 
It does neither change if my 4k screen gets set to Scale 100%, nor by dragging Chummer 5a to another screen with Scale 100%. 

Best regards

Robert

**Comment by DelnarErsike** [comment]
Sigh... https://github.com/dotnet/winforms/issues/3395

**Comment by OLRobert** [comment]
Well. 
Scaling is one story, crashing another, insn't it?

**Comment by DelnarErsike** [comment]
Speaking of crashing, the current Nightly (5.212.193) has had undergone some modifications that should give a similar handle count as 5.212.0. Unfortunately, the structure of WinForms (and the core structure of Chummer itself, related to the MDI thing I mentioned) means that massive handle counts for open characters are unavoidable, and you *will* crash if you have more than a certain number of characters open. All we can really do without dramatically changing the underlying form structure is to reduce the number of handles that will be created for a single open character by optimizing the underlying structure of our UI elements. One of the previous updates in the 5.212.x Nightly line changed one of the underlying structures specifically to make it more friendly to scaling, but it also unintentionally dramatically increased handle count, which is why you started to see crashes if you opened your four characters (each one would open around 3300 handles, and there's a hard limit of 10000 above which the program not only crashes, but cannot display an error message about the crash because doing so would require a handle, which the program cannot create because it just ran out of them). 5.212.193 contains a set of changes that dials down handle counts back to where they were in 5.212.0 while still keeping the scaling-friendliness, but that number is still going to be somewhere around 1900 to 2500 handles, so opening five characters may still cause the program to crash.

**Comment by OLRobert** [comment]
Nie update. 
5.212.198 made it possible opening all characters. 
After switching to GER and enabling all "required books", perception is no longer visible on the charcater sheets, but that is something I wil take as "given."

**Comment by OLRobert** [comment]
Same situation in 5.212.206.
Perception / Wahrnehmung is not shown any longer but opening the characters is fine.
