### ISSUE TITLE
Option for Monofilament Whips to be marked as installed within a fingertip compartment (Feature request)

### ISSUE THREAD

**Issue by cuckooman** [chummer5a/chummer5a#4231]
**Is your feature request related to a problem? Please describe.**
I have a character who has the (cliche, I know) monofilament whip/fingertip compartment combo. I normally just do it through a combination of item notes and item names.

**Describe the solution you'd like**
Either a cyberware plugin for the Fingertip Compartment cyberware or an accessory for the Monofilament Whip weapon (or maybe both).

**Describe alternatives you've considered**
As mentioned earlier, item notes and item names work fairly well, but having everything in a drop down is just *nice*.

**Additional context**
No real additional context here.

**Comment by DelnarErsike** [comment]
The monofilament whip finger (from Chrome Flesh) already exists, and the description for the Fingertip Compartment very clearly states that a regular monofilament whip (Concealability -4) would not fit inside of it (maximum Concealability of contents is -6). Feel free to make your own custom data files if you wish to change things on your end, but this will not be implemented in Chummer as a whole.

**Comment by cuckooman** [comment]
So... I can't find a monofilament whip finger anywhere in CF. Am I just going mad? The closest I could get was by adding a custom cyberfinger, but you can't add gear/plugins to it at all.
Also, in the CRB entry for the Fingertip Compartment it explicitly allows installing a monofilament whip into it (if you go to the top of the next page). I assume it's just Catalyst being Catalyst with the Concealability issue.

**Comment by DelnarErsike** [comment]
Sorry, I had misremembered where the monofilament whip fingertip thing was statted, I thought it was with all the other exotic cyberweapons added in Chrome Flesh. The problem is that the CRB doesn't really explain how monofilament whip fingertips work logistically, e.g. do you have to buy the whip separately, can a monofilament whip fingertip's compartment also be used to store something other than the monofilament whip, is the whip removable once you've put it into the fingertip compartment, etc. Because of this, you'll have to handle such a setup through weapon locations instead for now and have your GM check to make sure that your way of handling the monofilament whip fingertip is accordance with the group's rules. I'll mark this issue as needing errata/clarification instead.
