### ISSUE TITLE
Hammerli Gemini pistol is missing accessories

### ISSUE THREAD

**Issue by Lwmons** [chummer5a/chummer5a#4234]
**Describe the bug**
The Hammerli Gemini is missing at least two accessories, being the concealable holster and concealable quick draw holster.

**To Reproduce**
1. Go to Weapons
2. Add Hammerli Gemini pistol
3. Go to Add Accessories

**Expected behavior**
I wanted to add a holster to my gun.

**Screenshots**
https://i.imgur.com/hD8TylN.png?1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 18362.1082

**Additional context**
Other accessories may be missing. I haven't gone through the whole list.

EDIT: The cost of spare clips should also be double to 10 nY instead of 5, per the special rules.

EDIT II: I think it's pulling rifle mods instead of pistol mods.

**Comment by DelnarErsike** [comment]
The Hammerli Gemini, IIRC, has a Concealability Modifier of +1, making it larger than a standard Heavy Pistol. The holsters that you mentioned (as well as the other accessories you talk about) were given descriptions before any such pistol existed, and so it is not clear by RAW if they should or should not be allowed for the Gemini. We have ruled in the interim that they are not allowed, which is why you don't see those accessories.

**Comment by Lwmons** [comment]
That seems... Odd but alright, I suppose I can see where that ruling is coming from. Could it maybe be added to allow them under the House Rules tab?

**Comment by davidfoerster** [comment]
You can override the data file entry yourself. See [Custom Data Files](/chummer5a/chummer5a/wiki/Custom-Data-Files).
