### ISSUE TITLE
Armor Spell buff

### ISSUE THREAD

**Issue by AndrewDawnbringer** [chummer5a/chummer5a#4252]
**Is your feature request related to a problem? Please describe.**
Maybe I'm wrong, just started to use Chummer, but I did not find any way to add the Armor Spell on a character.

**Describe the solution you'd like**
Maybe a buffs/debuffs tab, where you can add things like that?

**Describe alternatives you've considered**
I'm not sure.

**Additional context**
I don't know if it's already there I just not found it, or it's not.

**Comment by DelnarErsike** [comment]
If you're talking about adding the Armor spell to a character's list of known spells, that's in the Spells & Spirits tab. If you're talking about adding a modifier to represent when someone has an Armor spell cast on them, you can do so through the Improvements tab, which is only available in Career mode, after you've generated your character.

Closing this issue because it is not an issue.
