### ISSUE TITLE
Customdata folders should include a manifest

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#4263]
More info about what a customdata folder actually does is good. 
Add a manifest file that can be parsed as a tooltip or label when selecting the folder in options.

**Comment by JoschiGrey** [comment]
I was thinking about working on this and took a look at the code. After finally unraveling the frankly confusing data structure I came up with two possible solutions to this. I'm however unsure which one would be better. Some input and ideas would be nice.

My basic idea was to use `objNode.ToolTipText` as simple mouseover tooltips to display some text, that is read from an `manifest.txt`, that could be present in a CustomData folder.

The `CustomDataDirectoryInfo` has two properties `name` and `directory`.

**_This would be my GoTo variant:_**
One could now add the tooltip text as a new property to `CustomDataDirectoryInfo` and add the `TextReader` somewhere in the constuctor or properties. From my understanding, this would add the work to be done to the original startup of chummer, because the objects are created at that point in the `static GlobalOptions.GlobalOptions()` method.

**_Adds the workload to another place, that is't called each time a user uses Chummer_**
The other way of going about this would be to use the `directory` property, to read in the `manifest.txt` while the `treCustomDataDirectories` nodes are created and added. This would add more loading, while opening the character options.
This could also lead to the `.txt` being read multiple times per session. When a user opens and closes the `frmCharacterOptions`.

I wanted to use an additional file and not include an new `.xml node`, because one Custom Data directory often includes multiple .xml files. Reading them all and merging the strings just sounds like even more work and trouble.
