### ISSUE TITLE
"Language" knowledge skill groups are shown as "Professional"

### ISSUE THREAD

**Issue by Fersoltil** [chummer5a/chummer5a#4270]
**Describe the bug**
When selecting language skills, UI shows "Professional" and the "Native" checkbox.

**To Reproduce**
1. Go to 'Fertigkeiten'
2. Click on 'Fertigkeit hinzufügen'
3. Select 'English' or any other language
4. It shows as "Professional"

**Expected behavior**
It should show as "Sprache"

**Screenshots**
![chummer5 error, language](https://user-images.githubusercontent.com/39620010/101457683-1ba8da00-3936-11eb-958c-d68e7a0e771d.png)

**Desktop (please complete the following information):**
 - OS: Win10 v2004
 - Version 5.213.0 de-DE

**Additional context**
None of the knowledge skill groups are translated, though they show as such in the language file

**Comment by DelnarErsike** [comment]
Unable to reproduce in English. The presence of the "Native" checkbox next to the first "English" entry does indicate that the program recognizes it as a Language skill, otherwise that box wouldn't show up; it doesn't show for the second one because the program is still waiting for you to finish changing the skill's name, since if it checked after every single character change, the program would be extremely laggy.

Is it possible that this is a translation issue?

**Comment by davidfoerster** [comment]
I can confirm this issue in German and French (see screenshots below): 

 1. knowledge skill category labels are consistently replaced by different category labels,
 2. the category label mapping varies by language,
 3. category labels are in English.

In English everything appears fine.

## Screenshots
The screenshots below were taken from the same character file but with different application language settings.

### German
![knowledge skills german](https://user-images.githubusercontent.com/959587/106130612-da78bd80-6161-11eb-82a7-042802d5b7f3.png)

### French
![knowledge skills french](https://user-images.githubusercontent.com/959587/106130606-d9e02700-6161-11eb-9db1-e40819365ee0.png)

### English
![knowledge skills english](https://user-images.githubusercontent.com/959587/106130613-db115400-6161-11eb-8421-a612ff1f66f3.png)
