### ISSUE TITLE
Cyberadept Daemon still not refunding Resonance

### ISSUE THREAD

**Issue by Anonymoogle** [chummer5a/chummer5a#4275]
**Describe the bug**
This issue was supposedly fixed in the most recent update but it does not seem to be triggering for me.

**To Reproduce**
1. Create a technomancer
2. Spend 4 essence worth of cyberware
3. Purchase Resonant Stream: Cyberadept quality
4. Submerge twice

**To Reproduce**
1. Create a technomancer
2. Spend 4 essence worth of cyberware
3. Submerge twice
4. Purchase Resonant Stream: Cyberadept quality

**To Reproduce**
1. Create a technomancer
2. Submerge twice
3. Purchase Resonant Stream: Cyberadept quality
4. Spend 4 essence worth of cyberware

**To Reproduce**
1. Create a technomancer
2. Purchase Resonant Stream: Cyberadept quality
3. Submerge twice
4. Spend 4 essence worth of cyberware

**Expected behavior**
Every 2 levels of Submersion should refund 1 point of Resonance

Is it possible to have the previous Echo or Quality Daemon workarounds added back in?

**Comment by corrugated-drop** [comment]
Hi Anymoogle,
The expected behavior you describe is not rules as written.
It is right that each submersion at grade 3 and 4 gives you back 2 points of resonance, but what you might have overlooked is that the daemon gives back only resonance that was lost by essence lost due to Cyberware since your _last_ submersion. 
So in your case you are a cyberadept with submersion grade 2, get Cyberware for 4 essence and then submerge to grade 3 which gives you back 2 resonance. But the next submersion will not give you back any resonance because since your last submersion you did not lose any resonance. 
So what you see is not a bug.

I hope I could help you.

**Comment by Tene21** [comment]
> the daemon gives back only resonance that was lost by essence lost due to Cyberware since your _last_ submersion.

i don't believe this is right. i'm looking at kill code right now, and there's no reference as far as i can see to the daemon only applying when resonance has dropped _between_ submersions.

kill code p90 only mentions that it has to be RES lost due to cyberware, no mention of it having to have been since your last submersion:

> Every time the Cyberadept goes through Submersion, they align their body, spirit, and cyberware. This means that a Cyberadept who has Submerged may restore Resonance that has been lost to cyberware (and only cyberware) by an amount equal to half their Submersion Grade (rounded up). Resonance lost by other means (such as bioware or Essence Drain) is not restored.

**Comment by Anonymoogle** [comment]
Tene21's read of it is what my whole table interpreted it as, yes. If you have the Cyberadept stream and Submerge, every other grade gets you back a point of Resonance lost due to Cyberware. There was no mention of needing it to be since your last Submersion anywhere I've ever seen.

The only point of contention our table has had is that one guy thinks it should only apply to RES lost from Cyberware taken after obtaining the Cyberadept stream quality, while the rest of the table and GM read it as "if you have lost any RES due to cyberware, have the Cyberadept stream, and submerge, it works" regardless of which order they happen in.

**Comment by corrugated-drop** [comment]
In the english rules it is indeed as Tene21 is saying. 

I got my knowledge from the German Kill Code rules where the paragraph for Daemon (here called Systemdienst) has additionally clarifications. 
In the German rules it says something in the lines of:
```
Each "set" of Cyberware can profit only once from this daemon.
```
And then it adds examples and clarifications and the information that this daemon replaces the selection of an echo if chosen. 

Maybe somewhere exists an errata for that topic but I could not find the kill code errata on the fly.

**Comment by Tene21** [comment]
ah, good old EN/DE disparities, i should've guessed.
personally if i was running a game i would treat it as the english rules state, as the german rules seem overly restrictive
of course, from there, there's still the argument of "half Submersion grade, rounded up", which in _my_ mind means even at first grade you're still getting that extra point of RES, because 1/2 = 0.5, which rounds up to 1
