### ISSUE TITLE
Can't add critter powers

### ISSUE THREAD

**Issue by cy-one** [chummer5a/chummer5a#4292]
**Describe the bug**
Running 5.213, I've rebuild an older character of mine, a Banshee. After finalizing the character, I wanted to add Regeneration, but the list of critter powers is nearly empty (only "Schallschrei", which would be some kind of sonic scream, dunno the translation).
If I open the old (last change 24.6.19) original file, the list of critter powers is way, way larger (and _would_ probably include Regeneration if it wouldn't already be taken).

**To Reproduce**
Happens every time.

**Expected behavior**
See a list of available critter powers :(

**Screenshots**
<img width="1920" alt="critter" src="https://user-images.githubusercontent.com/12306560/104667172-bf27a000-56d5-11eb-90da-ad09943ec11b.png">

**Character File**
[Cat.chum5.txt](https://github.com/chummer5a/chummer5a/files/5817776/Cat.chum5.txt) (old one)
[Cat v3.chum5.txt](https://github.com/chummer5a/chummer5a/files/5817778/Cat.v3.chum5.txt) (new one)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.213.0

**Comment by chummer5a** [comment]
Newer character has the limitcritterpowers improvement, which prevents taking critter powers that are not flagged as infected. Due to conflicts with how infected are able to buy powers with karma, most of their critter powers are flagged as qualities. The ones that are only available to infected are able to be purchased directly as critter powers,which is why you can see sonic shriek.

**Comment by cy-one** [comment]
Thank you, I removed the entry in the file and now it works like I want it to.
I do prefer the critter powers in their own critter power tab.

Thank you 👍
