### ISSUE TITLE
Please put Options for Char creation back into the "New Charakter" Dialog - pretty please!

### ISSUE THREAD

**Issue by Nedorus** [chummer5a/chummer5a#4350]
I use Chummer to create all of my Opposition. this means I need to create anywhere between 6 and 10 Chars every 2 weeks. All them have different Point Costs and I regularly use Karma / Sum to 10 or Standard methods.

Having to go into the Options -> Settings section every time is VERY annoying.

It's OK to have different Setting-Files and be able to choose from them a Pre-Sets. I think that s actually a brilliant idea!

However, I'd love to be able to quickly change the Karma-Limit and stuff like that in the C"New Char" window.

**Additional context**
It's SOOOO cool that we have the "non-global" settings in a file now! I remember that I requested this a while back! Thanks for picking this back up!

**Comment by DelnarErsike** [comment]
You know you can save your options, right? That's the whole point of the "Save" and "Save As" buttons. They will then show up in your dropdown and you don't have to go into the Character Options screen anymore.

Those dials aren't being put back because they belong in the Character Options screen. They are character-based settings that people ideally would want to have synced up across all characters that use the same settings.
