### ISSUE TITLE
English Strings with Multiple, Different Translations Get Translated Randomly

### ISSUE THREAD

**Issue by wakaba-github** [chummer5a/chummer5a#4378]
**Describe the bug**
I'm Japanese. 
Sorry , I can hardly understand english.

lang/ja-JP_data.xml 
There is the same keyword in another section. ('Armorer')
sc 1)

Each time it is selected, one of them will be displayed randomly.
sc 2) , 3)

**To Reproduce**
1. Go to 'Tools' > 'Options' > 'Grobal Options' 
2. Choose 'Language:'  other than 'English(en-US)'   ex)choose '日本語(ja-JP)'
3. Click 'OK' and Restart Chummar.
4. Create or Open Charactor
5. Go to 'ストリート・ギア' (street gear)
6. Add '工具キット'　('Tool kit')
7. Skill select '武器整備'   ('Armorer')
8. Select it several times
9. See error

**Expected behavior**
Converted with the contents of 'skills.xml' 

**Screenshots**
1)
![ja-jp_data xml](https://user-images.githubusercontent.com/82311362/114482922-5e5f2380-9c42-11eb-829d-0942121ff8cd.png)

2)
![chummer](https://user-images.githubusercontent.com/82311362/114484114-94050c00-9c44-11eb-8ef5-f39dbe3a6b74.png)

3)
![chummer2](https://user-images.githubusercontent.com/82311362/114484119-96fffc80-9c44-11eb-8c34-8746e0eb56bc.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [5.214.0]

**Comment by DelnarErsike** [comment]
Side note, the Japanese translation of Chummer is incredibly outdated and is mostly from the translation of Chummer for 4th edition. I can correct this issue because it's a complicated one caused by the way "Extras" are handled internally, but if you feel comfortable updating the Japanese translation yourself, do not hesitate to do so and to submit a pull request once you are done.
