### ISSUE TITLE
Life Modules from Street Lethal can not be added. Life Modules do not work in any version past latest Stable.

### ISSUE THREAD

**Issue by RocketPowereDeer** [chummer5a/chummer5a#4386]
The Modules: Rising Star, Company Trouble Shooter, Tour of Duty(Desert Wars), In The Thick, Gone AWOL and Gone Native are removed immediately after being added. I've played around with few combinations of qualities and options but nothing fixes that. Bug occurs in current stable version and the nightly before it. Haven't tested with older.

Additionally in any version past the latest stable you can not use Life Modules at all. They can be enabled and options file created for them but the button to add the modules will not appear.

**Comment by chummer5a** [comment]
@DelnarErsike Winforms won't properly bind to a control that hasn't been created. Any control that's been set to visible=false won't do things until it's set to true. 

Gone AWOL adds a Criminal SIN, which causes a conflict with other life modules that add SINs. This is a long-standing known issue with how life modules were implemented originally. Rest fixed by 5418c3a.
