### ISSUE TITLE
Trying to Add a Weapon to a Micro Drone Weapon Mount Crashes Chummer because There Are No Eligible Weapons

### ISSUE THREAD

**Issue by JoschiGrey** [chummer5a/chummer5a#4448]
**Describe the bug**
Clicking "Add weapon" on an micro weapon mount will crash Chummer with an "invalid selected index" exception.

**To Reproduce**
- Create a character (with additional drone modification rules active)
- Buy a SHiawase Kanmushi
- Add a Micro Weapon Mount
- Right Click -> Add Weapon
- Crash

**Expected behavior**
If there aren't any valid weapons, which I'm unsure about, because it can only hold "single bullets or arrows" it should open an empty list, or the option shouldn't be present.

**Screenshots**
![image](https://user-images.githubusercontent.com/69921261/118803877-3481c800-b8a4-11eb-8b67-655f20a4c594.png)

**Desktop (please complete the following information):**
- Win 10
- 5.214.66

**Comment by DelnarErsike** [comment]
Note on the new sets of labels: the problem is indeed that there aren't any weapons listed for it to take. However, this creates a problem: it *should* have some weapons that it's allowed to take, but the two listed ("single-shot bullet" and "single-shot dart") do not have any stats listed anywhere. The Proteus Krake's Micro-Torpedo Launcher had similar issues, but at least there, the torpedos had damage and range codes listed, and only the accuracy info for the launcher was missing in a way that it could not be easily guessed. The single-shot bullet and single-shot dart are missing accuracy codes, damage codes, range codes, availability/legality codes, et al.

**Comment by JoschiGrey** [comment]
I don't think there are rules anywhere and every thread that talks about this uses a different houserule.
There are a few interesting options we could implement without just making up stats.

Mainly, treating it as an 1 bullet magazine that can hold a dart or bullet of any type and deals base damage.
This would eliminate, availability/legality, dmg and cost.

We then just have to find a solution for precision and range, for those we don't have any neat solutions imo.
Treating the range as that of the ammo type (would be hilarious with the single sniper stick and shock), seems weird. So just assuming light pistols is probably the most reasonable way. Or entering 0 and let the GM decide.

Precision could only default to the drones sensor rating. It is used as precision anyways, when firing with passive target lock and is the only reasonable stat. Again just saying 0 would be an option.

**Comment by DelnarErsike** [comment]
> and deals base damage.

What base damage? That's the thing, damage codes are determined by the weapon, not the bullet type.

**Comment by JoschiGrey** [comment]
I know, that's why it's 0 in 99% of cases.

Use cases then are Taser Darts or some kind of other round with secondary effects.
