### ISSUE TITLE
Chummer5a crashes after clicking on Custom Data folder with Manifest

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4513]
**Describe the bug**
Clicking on a Custom Ruleset containing a Manifest file results in Chummer5a crash.

**To Reproduce**
Click on Custom Ruleset with a Manifest file.

**Expected behavior**
Program displays content of Manifest file without crashing.

**Screenshots**
[chummer_crash_132714748010769928.txt](https://github.com/chummer5a/chummer5a/files/6866081/chummer_crash_132714748010769928.txt)

Screen recording of select and crash
https://user-images.githubusercontent.com/17562417/126726362-99b116e3-0e41-4371-9bfc-af7ead637f88.MP4

**Desktop (please complete the following information):**
**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 5.214.130 (also 129)

**Comment by ArchonMegalon** [comment]
Do you wanna look at this @JoschiGrey?

**Comment by JoschiGrey** [comment]
I think they should be assignable to everyone, at least that's how it was some time ago.

The problem is, that `Version.TryParse` will lead to a null if the field contains a single integer. And `TryGetField` doesn't seem to default to it's error value if that happens.

I will put a PR up to fix this.
