### ISSUE TITLE
Auto-set page offset on setting PDF

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#4519]
> Teksura — Today at 11:46 AM
> Actually, I have a weird question about the page offset function. How difficult would it be to code into chummer a way to auto-set the page offset? Say, upon setting up the PDF, scan for a known term that should first appear on a known page, and base the offset off of that?
> 
> A-r-c-h-o-n — Today at 2:20 PM
> Actually, that wouldn't be that hard. It could even be a data entry in the xmls. But i haven't touched the pdf handling, so...
> Please make a github request about that. Seems like a good idea.

Basic idea is to have the PDF page offset auto-set based off of info it can pick up in the PDF, or a data entry in an xml. I'm not sure if there are different versions that have different offsets or not.

**Comment by Stexinator** [comment]
A manual setting is still needed. For some PDFs I removed pages to reduce unnecessary clutter

**Comment by ArchonMegalon** [comment]
If we have a small sample file to identify a page of the pdf, we actually also can identify, which pdf that is. 

So... we could offer a button, that browses a directory for all pdf files in there and assigns the correct ones to the correct rulebooks (and the correct page offsets). No need for the user to select every single pdf than anymore.

**Comment by JoschiGrey** [comment]
In the progress we could also differentiate between different languages. And maybe save all offsets, that way a user doesn't need to recalc /readd offsets if he switches between languages.

**Comment by Stexinator** [comment]
I fail to see why the user should not specify the pdf you are looking at.

**Comment by ArchonMegalon** [comment]
It's not that bad. First - we do it the other way around. We have a
directory mit maybe 20(?) pdf-files. We read the first(second, third,... up
to 10th) page as a whole from the first pdf. And than we can match the
strings from the books.xml against it. Yes, that may be 50 books, but we
don't need to parse the pdf page that many times. Also, this task can be
perfectly run in parallel (with the parallels library).

I already started coding it a bit. Lets see how fast it performs. But since
this is really a one time thing, i guess we won't even have to tweak it
that much. I would be fine with it finishing in under 2 minutes.

**Comment by ArchonMegalon** [comment]
Can you guys @JoschiGrey @Teksura take a look at #4590
Now we just need someone with a LOT of PDFs and time to actually edit the books.xml with all the newly needed data (only did the english core edition book). I think it should perform reasonable, but there is still room for improvement if needed. 

Also the finetuning is still missing (translating the button, giving maybe some feedback about the result when its done...).

**Comment by chummer5a** [comment]
Functionally implemented, I think we're just missing some of the German-exclusive books to generate offsets. Anything else that needs to be completed for this?

**Comment by ArchonMegalon** [comment]
No, I think we are set. Data entries can be added later.
