### ISSUE TITLE
Liminal Torso Centaur doesn't allow plugins

### ISSUE THREAD

**Issue by Sabetwolf** [chummer5a/chummer5a#4538]
Liminal Body Centaur doesn't allow plugins, despite it's 80 capacity. Attempting to add any just produces the "You must first select a piece of cyberware to add a plugin to"

[image](https://user-images.githubusercontent.com/88571198/128588612-6d9fa7a2-71ec-404c-85c2-60cc2dd8688a.png)

**Comment by DelnarErsike** [comment]
So this is based on the way the Chummer devs have interpreted how Liminal Body Centaur works. Essentially, in Chrome Flesh, it has 80 capacity, but no indication as to how that interacts with the cyberlegs of the liminal body. However, because obvious cyberlegs have a capacity of 20 and Liminal Body Centaur would have exactly 4 of them, the Chummer dev team decided that rather than have a single Liminal Body for centaurs that has 80 capacity but no way of modifying legs, the Liminal Body itself will have no capacity, but rather thave 4 cyberlegs that have 20 capacity each for a total of 80 capacity.
