### ISSUE TITLE
Black Market Pipeline Cannot Be Toggled in Create Mode after an Item Is Already Bought

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4553]
**Describe the bug**
When adding blackmarket pipeline and selecting cyberware or bioware no 10% discount is applied during character creation.

**To Reproduce**
create character
add some cyberware or bioware
add contact
add blackmarket pipeline, select cyberware or bioware
see that no price reduction is granted for the cyberware or bioware.

**Expected behavior**
A 10% discount should be applied items bought with this quality.

**Desktop (please complete the following information):**
 - OS: window 10
 - Version 5.214.0.0

**Comment by DelnarErsike** [comment]
Black Market Pipeline is based on stuff you get through a contact, so it is not automatic. This means that if you add 'ware before adding your contact and/or Black Market Pipeline, Chummer will assume that the stuff you added before was not acquired through the contact being a Black Market Pipeline.

The issue is therefore a QoL one, where you cannot toggle Black Market Pipeline status for an item in Create mode after having already bought it.
