### ISSUE TITLE
Nightly app flagged by Norton and removed

### ISSUE THREAD

**Issue by crinoalvien** [chummer5a/chummer5a#4604]
Attempted to launch the program this morning and it was flagged as a security risk by Norton and summarily removed from my computer by Norton.

Steps to reproduce:
Unknown. App appeared to have updated overnight and when I attempted to launch Norton immediately stepped in and stopped/removed the program.

**Desktop (please complete the following information):**
Windows 10

**Additional context**
initially installed version 5.214.83 (per my GM's instructions)

**Comment by DelnarErsike** [comment]
Chummer is known to trigger antivirus software false positives because it does stuff that a virus might also do: it downloads files from the internet without prompt (this is the auto-updater), it can delete files on your computer without prompt (this is the autosave system, the auto-updater, and the character settings manager), and it can run downloaded files from the internet without prompt (this is the part of the program where it will restart itself if you tell it to).

**Comment by ArchonMegalon** [comment]
Maybe if you switch to one of the more established update frameworks, this would be less of an issue.

**Comment by DelnarErsike** [comment]
Nah, changing UI frameworks won't make antivirus programs less paranoid. What would change it would be if we signed our binaries, but I heard @chummer5a has been having some troubles with that.

**Comment by ArchonMegalon** [comment]
Well Omaha for example uses the googleupdate-service installed as a local
windows service on the computer. I guess that Antivirus should react
differently about such an approach. But it's the most cumbersome update
mechanism to set up.
