### ISSUE TITLE
Critter Vampires can be adepts

### ISSUE THREAD

**Issue by Stexinator** [chummer5a/chummer5a#4609]
Vampires can be adepts, but there is currently no option to make them adepts

**Comment by Stexinator** [comment]
Is it sufficient to add the adept tab? Or should there be different kinds of vampires in the critter select?

**Comment by JoschiGrey** [comment]
How does a Vampire become a Adept mechanically?

In Chummer you can already add the Adept quality, which activates the Adept tab.
But it  won't have any powerpoints until you initiate and add a powerpoint.
Chummer will also think it is an Mystic Adept, because both tabs are active. 

If you want to create pure adept vampires you would have to remove the magician positive quality, which is baseline for vampires at the moment.

**Comment by Stexinator** [comment]
The citter Vampires just can be.

**Comment by chummer5a** [comment]
The simplest fix for this would be to add additional critter types for Vampire (Adept), Vampire (Mystic Adept), etc.
