### ISSUE TITLE
Chummer5a crashes at start

### ISSUE THREAD

**Issue by Gashnakh** [chummer5a/chummer5a#4626]
**Describe the bug**
Chummer5a crashes at starting in all Versions above 5.214.185 and just generates a empty crash-report

**To Reproduce**
1. execute chummer5.exe
**Expected behavior**
Chummer5 starts

**Screenshots**
see chummer5crash.png.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit - For exact data see DxDiag.txt
 - ALL Versions above 5.214.185 (checked every single version...)

**Additional context**

![Chummer5crash](https://user-images.githubusercontent.com/95226285/143876425-685666d0-f020-4e2b-829a-b1da2e409bd6.png)
[DxDiag.txt](https://github.com/chummer5a/chummer5a/files/7618442/DxDiag.txt)
.

**Comment by DelnarErsike** [comment]
Does 5.214.184 crash? Does 5.214.0 crash? Does 5.216.0 crash? Does the latest Nightly crash?

**Comment by Gashnakh** [comment]
All builds before 5.214.185 are okay... all builds newer include the Milestone builds crash on my system.
I had an IT Expert to look over my system and he said i should ask the apps developer...
So i did 😉

**Comment by DelnarErsike** [comment]
The thing is that 5.214.185 only changed stuff that is used by Linux systems using Mono. There are no changes from 5.214.184 to 5.214.185 that should affect a Windows system.

**Comment by Gashnakh** [comment]
5.214.185 is working perfectly but as soon as i update on any newer version, i can't start chummer5.exe

**Comment by DelnarErsike** [comment]
Ah, OK, you didn't do a bisection test, so you don't know which version newer than 5.214.185 introduced the crash bug, just that one of them between 5.216.20 (based on your DxDiag) and 5.214.185 did. The reason I say this is that looking at every version newer than 5.214.185, the first one where a change was made that could even cause some sort of crash on startup in the first place was 5.214.194.

The exception messages in your DxDiag attachment say they're `System.IO.FileNotFoundException`. That means they're a crash caused by the program not finding a file that it should find. If you do a complete, clean reinstall of Chummer (i.e. remove all the files and download a new version manually), does it still crash? Are you sure that your antivirus program isn't deleting any Chummer files?

If that still doesn't help, the "big guns" solution would be for you to manually debug the crash yourself. Download and install Visual Studio 2022 Community Edition (choose to install the .NET Desktop Development package when prompted), download and extract Chummer's source code (it's in the attachments alongside the main zip file containing the compiled version), open up Chummer.sln inside it, unload the ChummerHub, docker-compose, and ChummerDataViewer projects in the Solution Explorer sidebar (right click -> Unload Project), then press the big green play button at the top with "Build" next to it and wait for Chummer to first build and then hopefully crash with the Visual Studio debugger attached. If that has happened, Visual Studio will have caught and froze Chummer when it crashed and show you all sorts of information about it. What we're interested in is the Call Stack (one of the tabs in the lower right part when you start debugging), the exception information, and where in the source code the exception triggered.

**Comment by Gashnakh** [comment]
Today i tried the newest nightly version and at least i now have an crash-report which is not empty..
[chummer_crash_132831020646303360.txt](https://github.com/chummer5a/chummer5a/files/7654095/chummer_crash_132831020646303360.txt)
