### ISSUE TITLE
Create Chummerfile from export

### ISSUE THREAD

**Issue by Stexinator** [chummer5a/chummer5a#4637]
Sometimes chummer nightly build destroy the content of save files. To restore the save file it would be helpful if you can create a character from an export

**Comment by DelnarErsike** [comment]
That's... not really doable. Exports and save files go through almost identical procedures, the only difference is that exports are set up to save fields that are actually shown and that people actually care about, whereas saves are set up to save fields that are used internally by Chummer's code to set up the former. If you want to save all the information necessary to properly reconstruct a character in Chummer into an exported set of text, then the export text is going to be identical to (and as cumbersome as) the character's save file.

Chummer does autosave every 5 minutes in case you mess up something somewhere and can't get it back, but otherwise the onus is on the end user to keep backups of their important characters, especially if they're using the Nightlies.
