### ISSUE TITLE
Sound Link (gear) indicates incorrect Source book/page

### ISSUE THREAD

**Issue by pda6ne** [chummer5a/chummer5a#4696]
**Describe the bug**
Sound Link (gear, enhancement for audio devices) indicates incorrect Source book/page.

**To Reproduce**
1. Go to Street Gear tab.
2. Click on 'Add Gear'.
3. Search/Scroll for 'Earbuds' and add to character.
4. Right-click on 'Earbuds' and select 'Add as Plugin'.
5. Search/Scroll for 'Sound Link'.
6. See that it indicates Source as RF 229.

**Expected behavior**
Correct source for this item is SR5 454.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1

**Comment by DelnarErsike** [comment]
So the source is incorrect, but not in the way you think. SR5 454 lists Sound Link the cyberware plugin. Sound Link the Audio Enhancement is not listed in the core rulebook at all, only on RF 229 and RF 247. The actual price of Sound Link the Audio Enhancement is listed on RF 247, so the source will be corrected to RF 247 instead of RF 229.
