### ISSUE TITLE
Display Bug, Dropdowns, Windows 11

### ISSUE THREAD

**Issue by MarcusRiedner** [chummer5a/chummer5a#4700]
**Describe the bug**
There is a display issue in windows 11 where buttons overlap. See screenshot.

**To Reproduce**
1. Open Chummer on Win11

**Expected behavior**
I expect the buttons not to overlap

![Screenshot_8](https://user-images.githubusercontent.com/1050954/154398656-4f48ac05-472f-4989-b614-275315d78ec0.png)

**Comment by DelnarErsike** [comment]
This honestly looks a lot more like a Windows 11 WinForms bug than a Chummer bug.

**Comment by MarcusRiedner** [comment]
Shrug Emoji

I haven't had any other applications with a display bug like this in Win11. So whether it is a WinForms issue or a Chummer issue I can not say. But Chummer's dropdown menus are all broken in this manner.

**Comment by DelnarErsike** [comment]
WinForms is a very old platform, I would also be surprised if you used any other program that also relied on WinForms.

The reason I say it looks more like a Windows 11 bug is because of the specific way thing that would have to go wrong for this bug to show up. While the content of the buttons and what happens when you click on them is controlled by code that we write, the actual look and layout of the buttons is controlled by WinForms, i.e. code that was written by Microsoft a long time ago, not by us. Because it's specifically the drawn layout itself that's the issue, and because this is something that I have not seen in any older version of Windows, and because WinForms is old enough and Windows 11 is new enough to where these sorts of bugs could still be in Win11, that's why I said it looks more like a bug that we can't really do anything about.

**Comment by ArchonMegalon** [comment]
Well I do have the same bug on my Windows 11 installation. Just sayin. I just have zero time atm to look at it. :(

**Comment by o8livion** [comment]
Hello!
I appreciate the work done, but I have  the letter-overlapping issue too inside the button for adding cyberware, streetware, ...
no matter if german or english setting.

**Comment by DelnarErsike** [comment]
> PPS: since i have no clue about programming in that matter, what steps are there to do to port it into something newer (i guess xml would be the modern choice, right?) and how complicated is that? i guess its not a simple matter of ctrl+c, ctrl+v, ctrl+h, but can someone without actually having practice in real programing apart from excel-vba help in some way?

Unfortunately, not really. The work that'd need to be done would be to disentangle as much of the UI code from backend code as possible, which requires C#, no question. And that code needs to be disentangled to successfully move Chummer to any newer UI platform.

However, sticking with WinForms, this really is a Windows 11 bug with double buffering that should be fixed by the developers of Windows 11.

**Comment by DelnarErsike** [comment]
I've been using Windows 11 for a while now, and I think this issue has been fixed on Microsoft's end since, as I haven't observed it at all in my own use and testing of the Nightly builds. I'm therefore closing this issue.
