### ISSUE TITLE
Essence Cost for Used Cyber is Incorrect with Biocompatibility

### ISSUE THREAD

**Issue by Reqmartyr** [chummer5a/chummer5a#4761]
I've tested this issue in 5.221 and 5.222.52 and it persists between versions. As well, other people in my discord community have had the same issue.

It was noticed first by the change in essence costs for a full limb.
A full cyberarm or leg should cost 1.00 base, 0.9 with biocompatibility, or 1.25 with used grade.
When combining Used grade with Biocompatibility, the essence cost should be 1.10, but chummer reports it at 1.15.

I remember that in previous versions (I'm not sure which, but as early as 5.214 ish) this was not an issue.

Thank you kindly!

**Comment by DelnarErsike** [comment]
This is based on the unclear way in which stacking is defined for Biocompatibility, grade Essence modifiers, Adapsin, and Sensitive System. Wakshaani's post in the Shadowrun forums does not really help in this regard, because it is still unclear which of these stack additively and which stack multiplicatively and in what order.

So the call Chummer has made is for Grade modifiers to be applied first after combining them with any modifiers that stack additively, then multiply the result by all Essence modifiers that stack multiplicatively. In data files, there are nodes for retroactive, additively stacking Cyberware essence modifiers, retroactive, multiplicatively stacking Cyberware essence modifiers, non-retroactive versions of the previous two, and Bioware versions of all of the aforementioned. There is also a specially handled case for Adapsin because Adapsin is the only entry that still does not strictly work via additive or multiplicative stack, as well as custom data files that come with Chummer that turn that special treatment off and make Adapsin work through a non-retroactive, additively stacking Cyberware essence modifier.

In the base files, both types of Biocompatibility are set to stack additively, Adapsin is set to its own thing, and Sensitive System is set to stack multiplicatively. If you do not like this, you can always change the exact stacking mechanism for your own games through your own [Custom Data files](https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files).
