### ISSUE TITLE
Nanohives not accounting for wireless bonus

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4800]
Having wireless enabled for hard/soft nanohives doesn't boost the effective rating of their nanites by 1 when calculating limits.
Can be tested by adding a R1 neural amp neocortical and a soft hive. Toggle one of both of them wireless on and the bonus listed in the limits tab stays 1.

**Comment by DelnarErsike** [comment]
Tricky one to fix because nanohives are not defined in terms of the nanoware they support. This means that we can't use the existing `wirelessbonus` system for nanohives because Chummer doesn't know which nanoware a given nanohive is meant to support. It seems like this is also what's inteded by Chrome Flesh because nanohives can dynamically change which nanoware they support (otherwise reprogramming hard nanites wouldn't work as intended at all). This means it's kind of a weird situation where the RAW wireless bonus for nanohives is not clear about which nanoware it's supposed to apply to, especially in edge cases like there being two nanohives with one wireless on and the other wireless off.

**Comment by bulldogc** [comment]
Maybe manage it by allowing the nanite itself to flag wireless on and when done consider itself 1r higher or something similar.

**Comment by DelnarErsike** [comment]
Here's an example case to demonstrate my point:

Sam the Street Samurai has a single nanohive that is Rating 2. He gets two nanoware infusions: R2 markers and R2 nanotattoos. The nanohive can support one of the systems at a time, but the rules don't say anything about when this decision is made, whether or not it can be switched after it is made once, and how it is switched if it can be switched. If Sam turns his nanohive wireless on, is it his Markers or his Nanotattoos that get the +1 Rating? And if/how can it be switched to the other one if Sam decides he'd rather want the other one to be supported before he gets to the end of the week (at which point one of them will have its rating decay and so Sam has to choose then)?
