### ISSUE TITLE
Commanding voice power wrong.

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4839]
Chummer Ver 5.222.140

Commanding voice is listed as SS pg 191 cost 0.25/level

Commanding voice in SS should be 1 PP cost 1 rank
there is an alternate commanding voice in SG P170 which is .25 per level max 3 ranks.  This one has been errataed to Authoritative Tone, 0.5PP / rank max 3 ranks. If you include the erata as a book, the Auth Tone power is pointed wrong, showing up at .25 per instead of .5

**Comment by chummer5a** [comment]
German data changes enabled? That alters the authoritative tone pwoer to be 0.25.

**Comment by bulldogc** [comment]
Yes, that piece snuck past me. Commanding voice 1pp-.25 seems also tied to it. Assuming that part is also correct the only "bug" here might be the missing street grim version of Commanding voice if you don't have the erata enabled.

**Comment by DelnarErsike** [comment]
For clarity about the label: the missing functionality here is for some way of enabling the pre-errata Commanding Voice power if you are not using the Street Grimoire Errata book (or custom dataset, depending on how it's to be implemented).

**Comment by Teksura** [comment]
> For clarity about the label: the missing functionality here is for some way of enabling the pre-errata Commanding Voice power if you are not using the Street Grimoire Errata book (or custom dataset, depending on how it's to be implemented).

This sounds like it could be done with just an amends. The question then becomes the best way to go about it. Should this amends:

- Disable Authoritative Tone, replacing it with Commanding Voice as written in Street Grimoire?
- Disable the version of Commanding Voice found in Stolen Souls and replace it with Commanding Voice as written in Street Grimoire?
- Keep both Authoritative Tone and Commanding Voice (Stolen Souls) and simply add a new version of Commanding Voice (Street Grimoire) allowing all three powers to be used?

Personally, I'm leaning towards the most direct option of "Do not use that errata" which would consequently remove Authoritative Tone but keep both versions of Commanding Voice. This will somehow end up being both the simplest and the most complicated implementation. Simplest because it's one single thing we change, just, the amends drops that one part of the errata. Most complicated because it now leaves us with 2 powers of the same name which both do very different things and this is prolly why they did the errata in the first place.

Adding this as an amends is easy. It's just a matter of clarifying what we want to see and what we don't want to see.

**Comment by Teksura** [comment]
This issue should be marked as closed as it was resolved by #4967
