### ISSUE TITLE
I would like the ability to create own Shapeshifters with Chummer as characters. So i can do, Cat, oder Rat oder whatever as an Shapeshifter.

### ISSUE THREAD

**Issue by Chanilnu** [chummer5a/chummer5a#4864]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chummer5a** [comment]
Creating custom metatypes requires making additions to the metatypes.xml file, which can be done through the [customdata system](https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files). Note that in order to support priority build methods you'd need to make an amend file for priorities.xml as well.
