### ISSUE TITLE
Unable to add Modular Connectors to Cyberlimbs

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#4874]
Not sure when this started but you are no longer able to instal modular connectors (Elbow/Knee or Wrist/Ankle) to existing cyberlimbs using capacity.

**Comment by ArchonMegalon** [comment]
I think you can only add a modular connector if the essence cost for a
modular limb is paid. You can't mount a modular connector on a standard
cyberarm, can you?

**Comment by Minnakht** [comment]
It might be an expected feature that an arm permanently attached to a shoulder should still be able to split at the elbow or wrist by taking the appropriate modular connector for [10] or [5]. I know that this worked back in 5.214. days, as a character I know of had a wrist connector on a non-modular full arm.

**Comment by chummer5a** [comment]
Issue is on line 1256-1263 of selectCyberware.cs. The problem is that the modular connector is checking if it's allowed to be added to the limb by checking whether the parent limb's blockmounts entry contains the connector's consumed mount. Full arm blocks wrist, shoulder and elbow, so none of them are available. Will have to do some archeology to determine when/why that was changed versus how it used to be, can't recall offhand. In theory we can just check whether the Parent is the object blocking the mounts and bypass it?

**Comment by chummer5a** [comment]
Eh, actually can't reproduce this in current nightlies now.

**Comment by Teksura** [comment]
> Eh, actually can't reproduce this in current nightlies now.

Hmm. Strange. I just tested in 5.222.195 and couldn't add a Modular Connector, Elbow to an Obvious Full Arm.

**Comment by Teksura** [comment]
Okay, EXTRA strange. I tested a second time and when doing it in an existing character I have it's not showing up, but when making a NEW character it works. 

Weird.

**Comment by chummer5a** [comment]
I think the best way to resolve this would be to set up an addmounts or addchildmounts property, so full arm blocks shoulder elbow wrist as normal, but it has its own addmounts for wrist and elbow. Attaching a lower arm then consumes the wrist and elbow, but lower arm then has its own addmounts, etc etc. Cute benefit to that is it would enabling dynamic limb changes, so you could arguably make a lower arm that gives two wrist mounts or something and have a freaky robot clapper hand. Not sure there's another suitable option that doesn't just expose attaching things you shouldn't be able to to any given mount location.
