### ISSUE TITLE
Option for not having to pay lifestyle on character creation

### ISSUE THREAD

**Issue by SuperMarauderGirl** [chummer5a/chummer5a#4901]
Lots of groups apply a houserule that allows you not having to pay the first month of rent on character creation as lower ressource characters can't pay them without spending some of their creation karma.

Setting the minimum value of the NumericUpDown control in the lifestyle tab to 0 should solve the problem. Right now minimum is 1, which forces everyone to pay at least one month of rent.

**Comment by DelnarErsike** [comment]
I can't find this optional rule in any of the sourcebooks and it's not how HeroLab (which is RAW absent anything in the sourcebooks) works, so I'll tag this as a feature.

**Comment by o8livion** [comment]
we use this houserule and we realize it by setting 0% to pay. so no karma for newly created chars is spent on lifestyle.
we are still in the first ingame month but for next month we take new lifestyle. since its a fix group we want to stay together in one household and each pay 25%.

that's what u meant i guess, or isnt it?

**Comment by DelnarErsike** [comment]
I meant in terms of a coding project, this isn't some missing optional rule, it's a custom house rule. Which means I marked it with the `feature` tag instead of the `bug: missing functionality` tag.

There are explicit rules for sharing a lifestyle, BTW. You designate a primary tenant for the place, and they have to pay the full cost of the lifestyle plus 10% for each extra person beyond the first. The other tenants can, of course, chip in and send money to the primary tenant to cover their share, but if something bad happens to the lifestyle or if payment is late, the primary tenant is the one responsible.

**Comment by SuperMarauderGirl** [comment]
> that's what u meant i guess, or isnt it?

Not exactly. Ditch the part of sharing a lifestyle and you're right. What i mean is: Treat the first month after character creation as already paid so the runner doesn't have to waste money or karma on it when creating the character.

> I can't find this optional rule in any of the sourcebooks

And I can't find anything about having to pay the lifestyle right at character creation, so both assumptions might be valid.
