### ISSUE TITLE
Thread issue with objects that add multiple bonuses

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#4904]
**Describe the bug**
When adding an object that contains two or more bonuses that call the same selection form (ie Dead SIN quality), the second spawned window will be unresponsive.

**To Reproduce**
1. Add the Dead SIN Quality.
2. Enter any text for the Select Text Window. 
3. Select anything for the first license.
4. Attempt to select something for the second added license. Observe that the window is non-responsive.

**Comment by ReallyDarkMatter** [comment]
The same thing happens with Spirit Mentor: Luna

**Comment by DelnarErsike** [comment]
From the other issue that I made before I realized it was a duplicate entry:

The lock-up is caused by an unfortunate interaction between how `SynchronizationContext`, `TaskCompletionSource`, and `Application.DoEvents` interacts when they're all being processed on the main thread. AFAICT, an `Application.DoEvents` call can potentially enter into a `SafeWait()` situation that never actually frees a semaphore, and while the `SafeWait()`'s `Application.DoEvents` call will process UI events like that of pressing a button in a dialog box, the actual function that is supposed to process what happens after the UI event is resolved actually gets called because they're all stuck far up in the main thread's callstack from the time they were forced to run on it via `SynchronizationContext`.

**Comment by DelnarErsike** [comment]
So, basically, the issue is that code that's supposed to process what happens after a UI event gets “stuck” because it's not handled as a part of `Applications.DoEvents`, so code that is handled as part of `Application.DoEvents` that contains some kind of lock or semaphore will prevent the previously mentioned code from ever being able to execute.
