### ISSUE TITLE
[FeatureRequest/Bug] Customize/Load Spirit initiative

### ISSUE THREAD

**Issue by Stexinator** [chummer5a/chummer5a#4982]
Some spirits have a special initative formula, currently it is always 2d6

**Comment by DelnarErsike** [comment]
I do not understand the request or the bug. If you're talking about the initiative fields in the data files, those are deprecated and the program doesn't use those.

**Comment by Stexinator** [comment]
How do I add a custom initiative formula? As far as I know there currently is no way

**Comment by SRgithub5** [comment]
How do we decide? I've not seen errata about how or why spirits have the listed initiatives they have listed.

I'd expect when dual space they would use REA+INT+ some number of d6.

And when Astral to use INT+INT plus probably maybe one more initiative dice. But that only seems to make like maybe 60% of the spirits and they rest are just weird.

Seems like we should have house rule files for the different initaitve systems for spirits. Since many of not most GMs will consider the rulebook to contain typos.

**Comment by DelnarErsike** [comment]
All physical initiative is calculated as `REA + INT + [Extra initiative, including penalties, through bonus node] + (1 + [Extra Initiative passes through bonus node])d6`. If you want to adjust flat initiative and/or the number of initiative dice that a spirit has, then it's all supported through entries you can add in bonus nodes. This is done the same way that stuff like trolls' lifestyle cost adjustment and bonus reach are done. So I do not understand the request in terms of custom initiative formulas for spirits.

**Comment by Stexinator** [comment]
Thanks, that was what I was looking for
