### ISSUE TITLE
When adding a specialization to Pistols on a created character, pistols are listed individually.

### ISSUE THREAD

**Issue by Jigurd** [chummer5a/chummer5a#5043]
**Describe the bug**
![image](https://github.com/chummer5a/chummer5a/assets/33100756/2e45c4ef-a77d-491f-a852-85d60bfee25f)

**To Reproduce**
1. Download a fresh 225 instance
2. Create a new character, open it up in Created mode (or open an existing one, both work)
3. Add some karma to pay for a rank of pistols
4. Take a rank in pistols, try to add a spec
5. Observe incorrect entries

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**
Pistols available for a spec seem to reflect enabled books. Longarms works as expected. Automatics has exactly one gun that shoulddn't be there, the Onotari Arms SIG-6

**Comment by DelnarErsike** [comment]
This has been a feature in Chummer5a from the very beginning. As in, if I go back in the history files for the code that's responsible for this, it has been there from the very first version of that file.

It's not strictly "wrong" because specializations are left open by RAW, similar to knowledge skills. You'll notice that that's why the dropdown box lets you type your own thing inside of it, it doesn't force you to only pick from the dropdown. That said, there's probably some amount of clean-up we could do, e.g., by sorting items alphabetically or alphabetically with the CGL-recommended entries before all the individual guns. I'm closing this issue, but I'll do some of that clean up later.
