### ISSUE TITLE
Allow limb replacement cyberware to take up multiple limb slots simultaneously and have customizable initial stats

### ISSUE THREAD

**Issue by EmmjayXII** [chummer5a/chummer5a#5047]
I would like the starting STR/AGI of cyberlimbs to no longer be hardcoded, and for the cyberware [limbslot] parameter to allow a single piece of cyberware to cover multiple different limb slots (e.g. a full body replacement which covers both arms, both legs, the torso, and the skull).

I am currently attempting to help my GM backport 6e cyborgs to 5e, and this feature would significantly reduce the necessary workarounds and manual bookkeeping necessary to do so.

**Comment by chummer5a** [comment]
This should be doable now. Try
<minagility>1</minagility>
<minstrength>1</minstrength>
<blocksmounts>wrist,elbow,shoulder,ankle,knee,hip,torso</blocksmounts>

**Comment by EmmjayXII** [comment]
As you mentioned on the Discord, it does not yet support having one cyberware item count as more than 1 cyberlimb for averaging.

**Comment by DelnarErsike** [comment]
![image](https://github.com/chummer5a/chummer5a/assets/727731/4ac48fe1-3d94-4190-9e33-a64847561d97)
Does the way liminal body works not already cover this case?

**Comment by JoschiZ** [comment]
`Attribute.Core::CalculateTotalValueCore()` takes this into account for the full on calculation.
However it won't work with `Cyberware.InheritAttributes`, because `Cyberware::GetAttributeTotalValue()` will assume that every child takes exactly one slot.
Also `InheritAttributes` won't cause the parent ware to also inherit the total count of limbs occupied by itself and it's child wares.
I will add that to my current PR regarding cybersuites.
