### ISSUE TITLE
Chummer hangs when Nuyen Rewards or Expenditures are manually added to a character sheet

### ISSUE THREAD

**Issue by EmmjayXII** [chummer5a/chummer5a#5070]
If you try to add nuyen rewards or expenditures to a character sheet manually, Chummer v5.225.327 and v5.225.321 do not update your character's current nuyen figure with the addition or expenditure and seem to process the change for a long period of time with no actual changes.

If you attempt to save the character sheet in this state, the nuyen figure is saved incorrectly, as even though the expenditure or reward entry is saved, the expenditure or reward is not subtracted from or added to the character's available nuyen.

**Comment by Raitzo** [comment]
I noticed that you can edit the expenses and the changes you do there do affect the total nuyen

**Comment by DelnarErsike** [comment]
I believe this has been fixed in the latest Nightly, if the bug is referring to behavior present in a semi-recent Nightly version. I'll close this issue pre-emptively (because I have ended up testing behaviors that should have triggered this hang, and they didn't), but please re-open it if the issue remains in the latest Nightly.
