### ISSUE TITLE
Issue: - crash when clicking on REA enhancers

### ISSUE THREAD

**Issue by KeeperM** [chummer5a/chummer5a#5088]
### Environment
Crash ID: bc7240a9-3bd0-4739-8b2e-a1f39723e935
Chummer Version: 5.208.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: OnlyMetric
Installation ID: b37d2081-15b3-4741-adb5-315b4914e97e

### Expected behaviour
I want to see details of my reaction enhancers.
[chummer_crash_133464561377798959.txt](https://github.com/chummer5a/chummer5a/files/13605238/chummer_crash_133464561377798959.txt)

### Actual behaviour
Chummer crashed... [chummer_crash_133464561377798959.txt](https://github.com/chummer5a/chummer5a/files/13605238/chummer_crash_133464561377798959.txt)

### Steps to reproduce the behaviour
Have reaction enhancers in CM and click them.

**Comment by DelnarErsike** [comment]
Win10 and Win11 internally have the same Windows version (10.x).

**Comment by DelnarErsike** [comment]
That said, 5.208 is an extremely old version. We have since updated the specific code that would have allowed this crash to happen in the first place. I'm closing this issue for now, but please re-open it if you experience the same crash with the latest milestone version (5.225.0) or one of the newer nightlies.
