### ISSUE TITLE
.net 4.5.2 issue Windos10 64bit

### ISSUE THREAD

**Issue by Ideoges** [chummer5a/chummer5a#593]
Hi, when I download the file from Microsoft (https://support.microsoft.com/de-de/kb/2901907), I get the error, that this or a newer version is already installed on my system. 

Unfortunally, the last working Version is 1.0.0563, newer wont start. Also I get no error message or pop-up, only the "waiting-circle-icon" from Windos10.

**Comment by holgerschlegel** [comment]
I had a similar effect on two of my Windows 7 installation. It worked on (at least) two other machines with Windows 7.
Starting Chummer caused the "parent" application (cmd.exe, Explorer, ...) to freeze and only show that "waiting-circle-icon". The task manager listed three running Chummer instances, which could not be killed thru the task manager. These instances using only ~130 kByte of memory, not the usual multiple mega bytes...

In the end, the Avast anti virus was the reason. Updating Avast solved it. The first start took some seconds due to Avast deep scanning the application. After that, all starts are as fast as expected.

**Comment by Ideoges** [comment]
thank you, that solved it - Avast was the problem!
