### ISSUE TITLE
Can't Add Unslotted Weapon Mods

### ISSUE THREAD

**Issue by IamAlphaGeek** [chummer5a/chummer5a#600]
Once again having the issue in which weapon mods with no specific slot cannot be added to weapons. (i.e.: Internal Smartgun System, Ammo Skip, Sling, etc)
Last build when this happened, it just needed to be updating, but my updater says there are no new updates.

**Comment by McRipolo** [comment]
And the Problem from issue  #566 is back, think same problem.

**Comment by chummer5a** [comment]
Given that 5.179 isn't a release candidate yet and it's fixed in the nightlies, I wouldn't exactly say it's 'back', it's just not fixed in the version he's using. 

Anyway, you can either use the current nightly builds ( https://github.com/chummer5a/chummer5a/releases) or wait until we've decided that 5.179 is ready. Hopefully within the next few days, maybe a week or two.

**Comment by IamAlphaGeek** [comment]
Sorry, meant to post the build on the original: 5.177
Which would probably explain the problem.

**Comment by chummer5a** [comment]
Ha, that'd do it. Well, closed pending something else exploding related to this.
