### ISSUE TITLE
Ongoing issue with metamagic

### ISSUE THREAD

**Issue by Godfrid** [chummer5a/chummer5a#614]
Many metamagics aren't allowed to be bought for mages, only for adepts and mystical adepts. It is I guess only caused by a few missing lines at these metamagics. For example: Flexible signature, Flux.
If at the optional rules I choose the art requirements to be ignored, this problem still present.

Somewhat other thing: Would it be possible to include blood magic metamagics in the program? (sacrifice etc....)

**Comment by chummer5a** [comment]
Blood magic metamagics are one of those things that I can't really be bothered to do personally; if you want to do the scut work of creating them (Just open metamagics.xml, copy a metamagic node and make the necessary alterations then send it to me, I'll add it in. Otherwise it can sit in the backlog pile for a while.

**Comment by drakir75** [comment]
Masking and Flexible Signature still can't be choosen. Says do not meet requirement but do not list any criteria.

**Comment by chummer5a** [comment]
That would be because you haven't taken the appropriate Art to unlock the
Metamagic, or don't have the Houserule enabled that disables the Art
requirement.

**Comment by abbybrodie** [comment]
Hey man, I took a look at metamagics.xml and for the most part I think I can sort it out so that blood magic works. 

Have a few questions though! Here's my mockup, wondering if you could check it and make sure i"m not gonna break chummer by doing it!

<metamagic>
      <id>1234noideawhattoputhere4321</id>
      <name>Sacrifice</name>
      <adept>no</adept>
      <magician>yes</magician>
      <required>
        <oneof>
          <art>I don't think there's a required art?</art>
          <quality>Don't think there's a required quality? Not sure what you meant by quality here!</quality>
        </oneof>
      </required>
      <source>SG</source>
      <page>90</page>
    </metamagic>

As you can see, i'm no expert here. Near as I can tell, I don't need anything special to get the Sacrifice Metamagic, unless i'm missing something?

**Comment by abbybrodie** [comment]
of course it didn't leave any of the markings in fml

**Comment by chummer5a** [comment]
There's an Insert Code formatting option on the top right of the comment form, the two arrows. Select your text and click that button.
![image](https://cloud.githubusercontent.com/assets/11448441/13271054/7be4d828-dae6-11e5-9685-6957d3c43bbb.png)

Don't worry about the IDs, just leave them as `<id></id>`. I'd prefer that you set the Required Art as Blood Magic or something similar, just to keep it in line with the others.

**Comment by abbybrodie** [comment]
Gotcha, I'll fiddle with them a bit then. Thanks for the heads up on the ID... that was honestly the only thing that made me really furrow my brow.
