### ISSUE TITLE
Mentor Spirit (Dragonslayer) causing unhandled exception on delete

### ISSUE THREAD

**Issue by sphassan** [chummer5a/chummer5a#652]
Deleting Mentor Spirit (Dragonslayer) in chargen creates a reproducible and consistent error report. Attempting twice results in a successful delete. This only occurs with Adepts.

http://pastebin.com/PwAqCPDK

**Comment by chummer5a** [comment]
Issue seems to be caused by creating multiple adept powers through the mentor spirit dialog. The improvement removal code tries to use the Notes field to decide which powers to remove, but the Notes field is only populated for the most recently added power/improvement. It's an... interesting segment of code. Don't have an ETA for a fix as yet.
