### ISSUE TITLE
Shapeshifters

### ISSUE THREAD

**Issue by animusv0x** [chummer5a/chummer5a#653]
cant set my metatype as shapeshifter

**Comment by chummer5a** [comment]
Chummer currently doesn't support shapeshifters, because of the annoying requirement that they buy up their stats separately in career mode. There's a rather annoying amount of work that would have to go into supporting that, so they won't get put in until then. If you'd like to make one in spite of that, you could make a custom_metatypes file; the back-end data's there for them to work in Priority mode and such.

**Comment by chummer5a** [comment]
Exists as #272. Closing duplicate ticket.
