### ISSUE TITLE
Metavariants not available when using german sourcebook "Schattenläufer"

### ISSUE THREAD

**Issue by GhostWhoWalksInside** [chummer5a/chummer5a#666]
It's just a small inconvinience, but in general the metavariants would be included in this sourcebook.
As the metavariants are included in english sourcebook "running faster", there is a workaround, but in general it would be more convinient to select only the sourcebooks you own. Maybe it's possible to add a language filter to the sourcebook list, and select the english variant also, if you select the german aquivalent ?

**Comment by chummer5a** [comment]
As far as I'm aware there are only minor differences between the two; is there something I've missed?

**Comment by GhostWhoWalksInside** [comment]
Just checked it again, using the last nightly build. Selected Schattenläufer and Sr5 as source, this should give me access to metavariants. But the metavariant selection combobox does not show any metavariants.Problem is, in metatypes.xml for source there is only "rf" for all the metavariants.

**Comment by chummer5a** [comment]
Ohhh, I get what you're after. Since that book's a compilation you want to
be able to just use that and have the book open to the right page. It's...
doable, I guess. It's a pretty large divergence from the current code
though and we have a block of larger priorities, so I don't see it getting
done by the main dev team any time soon.
