### ISSUE TITLE
Clothing listed in armor

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#739]
The clothing table listed in Run Faster, page 253, has been added to the Armor table.
Should this actually be in the Gear file?

**Comment by chummer5a** [comment]
Hrm, hard to say. The general idea behind that decision was that things you wear == outfits == armour, from memory. There were already other bits of clothing in there originally, so it made an equal amount of sense for it to be in there. If you wanted, you could copy the data out into a custom file I guess?

**Comment by Lochabar** [comment]
Armor is a specific category of gear. And is not an obvious place to look for clothing. I spent time trying to figure out why it did not show under gear, and why an override file with the clothing did not display properly (which was a conflict between existing and custom entries). Eventually I removed the entries from Armor and added them to a custom gear file.

Gear would seem to be a more intuitive location for clothing, especially now that there is a table of miscellaneous gear from the next page of Run Faster.

The only items of clothing listed in SR5 (page 437) are Electrochromic, Feedback, and Leather jacket/duster and are listed as Mods in the armor file. Only Electrochromic is listed as an option for armor. And synth-leather says "Just don’t expect it to stop bullets."

**Comment by HaikenEdge** [comment]
I originally entered clothing under armor during the data entry phase because it fit in my head, as the armor section was the only place in Chummer where users could equip and unequip items worn. In my head, it worked better because it simply allowed the user to keep track of what they had put on without having to do paperwork outside of Chummer.

**Comment by rmmonster** [comment]
I agree with @HaikenEdge; armour and cloth are part of the same inventory category, but I would vote for renaming the tab to _outfits_, as @chummer5a described the category.

This would allow to create outfits composed from cloth and armour, as I usually do when creating a character.

On the downside, new users might not expect armour in the _outfits_ tab.

**Comment by joha4270** [comment]
We could always move the UI a little so we can call it _Clothing and
Armor_, same as the core rulebook calls it.

Not sure i want to start playing with the UI, but whatever the name i think
it should keep a name including armor, partly as you say new users, partly
because SR5 gives an armor rating to some pieces of clothing.
