### ISSUE TITLE
Dissonant Echoes

### ISSUE THREAD

**Issue by Gamingharry** [chummer5a/chummer5a#750]
Are Dissonant Echoes able to buy? I cannot find them under the Submersion tab. I cant find the page reference saying PC's cannot be Dissonant, but adding them for GM NPC benefit would be great.

**Comment by chummer5a** [comment]
Data content doesn't exist, and it's not in any of the books I own. If you'd like to contribute, you can open up the Data\Echoes.xml file (I recommend using Notepad++ or SublimeText), copy the nodes for a couple of existing echoes, and dumping them into a custom_echoes.xml file. Otherwise point me to the relevant pages in the relevant books and I'll do my best to get to it at some point.

**Comment by HiddenBoss** [comment]
It hidden all the way on page 165 of Data trails, CONTAMINATE, PRYON, SIPHON,  with PRYON adding 2 biotech virus.

**Comment by Gamingharry** [comment]
Finally made them. Don't know if there is a way to make them only usable when ignoring char gen rules for GM's only but either way, here they are!
[Custom_Dissonant_echoes.zip](https://github.com/chummer5a/chummer5a/files/517170/Custom_Dissonant_echoes.zip)

**Comment by StarWeaver** [comment]
Not sure if commenting here is best approach, but I'm curious why dissonant echoes is presented as a separate sourcebook in the list? I had to come here to figure out what book I wasn't missing o.o

**Comment by chummer5a** [comment]
They're an NPC-only option, so I didn't see any reason to make them available for PCs by default.
