### ISSUE TITLE
Chummer5a Issues

### ISSUE THREAD

**Issue by victorypuppet** [chummer5a/chummer5a#779]
### Expected behaviour:
* Oni do not have Fangs quality.
* Oni should have 29 karma for all Priorities, not just Priority C. 
* Hobgoblin should have 30 karma for all Priorities, not just Priority C. 
* I should be able to give my character qualities such as Bad Rep and Code of Honor.
* Chrome Flesh cyberware/bioware prices for augmentations that can be bought in pairs should reflect a price increase when the rating is raised. Example: Rating 1 Claws/Retractable Claws cost 500/1000 nuyen per limb (CF page 120-121). Notes in Chummer5 state that Rating for Claws/Retractable Claws indicate number of claws. So Rating 1 Claws/Retractable Claws should cost 500/1000 nuyen and Rating 2 Claws/Retractable Claws should cost 1000/2000 nuyen.
* Cost adjustments are made for metatype lifestyles. Lifestyle example: Troll metatype Low Lifestyle costs 4000 nuyen.
* Smokebomb from Hard Targets (page 187).

### Actual behaviour
* Oni have Fangs quality.
* Oni at Priorities A & B start with 21 Karma. Striking Skin Pigmentation is a Negative Quality that gives a bonus 4 karma according to Run Faster (RF page 122). Extended Priority Charts A and B (RF page 106) are obvious typos as Extended Priority Chart C (RF page 107) lists the bonus karma for Oni as +4.
* Hobgoblin at Priorities A & B start with 20 Karma. Poor Self Control (Vindictive) is a Negative Quality that gives a bonus 5 karma according to Run Faster (RF page 158). Logically one can deduce that the Fangs and the unlisted Extravagant Eyes quality cost 4 karma and refund 4 karma to balance out. Extended Priority Charts A and B (RF page 106) are obvious typos as Extended Priority Chart C (RF page 107) lists the bonus karma for Hobgoblin as +5.
* Certain Qualities such as Bad Rep & Code of Honor are missing.
* Chrome Flesh cyberware/bioware prices for augmentations that can be bought in pairs do not reflect a price increase when the rating is raised (CF page 120-121). Example: Claws/Retractable Claws cost 500/1000 nuyen regardless of rating.
* No cost adjustments are being made for metatype lifestyles. Lifestyle example: Troll metatype Low Lifestyle costs 2000 nuyen.
* Smokebomb (HT page 187) doesn't show up in Gear.

**Comment by chummer5a** [comment]
- Fangs were removed from the Oni in one of the nightly patches. 

- As for Oni and Hobgoblin karma costs, absent of any official errata, I have to make the assumption that what's written in the books is correct. If you can cite something on the official forums from an official source then I'll happily change it. As is, you can use an [override file](http://www.chummergen.com/chummer/wiki/Print.aspx?Page=Custom%20Data%20Files) to change it without having your changes overwritten by later patches.

- This is generally due to the Hide Qualities Prohibited By Missions flag being set on your options file. 

- Nuts, thought I'd gotten all of those. Will be fixed in the next nightly build.

- Should be fixed in the latest nightly builds.

- Added in the latest nightly build.
