### ISSUE TITLE
Feature Idea: Shapeshifters and the Critter Tab

### ISSUE THREAD

**Issue by Velocikitty** [chummer5a/chummer5a#826]
I know from their Reddit posts, that Shapeshifters are an issue due to the double stats that ends up coming into play, and how best to represent them.

Why not just toss the secondary stats in the critter tab? (Like there was in Chummer 4?)

Honestly, you could even just skip the extra shapeshifter stats, simply because of how uncommon it is to use the form, much less want to level it up. (I normally play Shapeshifters, and in 4th, I think I've used my form once for combat (Since a plan was to put me into play as a gift, and I lacked my weapons), and twice for misc infiltration.)

**Comment by skarsol** [comment]
What do you mean by double stats? You only get +1 to one stat per hit.

**Comment by chummer5a** [comment]
The question of where to put it isn't really a problem; it would be easy enough to make a tabsplit container on the main window to hold the attribute panels. The problem is there's a lot of technical debt associated with the assumption of how attributes work. A lot of the improvement/attribute system uses the naming conventions for the numericupdowns, Limits and dicepools would need to be adjusted to handle it, etc. 

It's not insurmountable, but it's a big enough mess that I'm not willing to start tackling it until we've cleared out a bunch of the other bugs first. As is if you want to be a proxy shapeshifter you can use the custom XML files that the Reddit guys made.
