### ISSUE TITLE
Drone weapon Mount options

### ISSUE THREAD

**Issue by Tracersmith** [chummer5a/chummer5a#830]
## Required Fields

Drone weapon mount using Rigger 5 on page 124 have an option to add pop out mounts and 2 different types of expanded Ammo bay.
### Chummer Version

5.179.833
### Expected behaviour

the ability to modify drone weapon mounts
## Helpful Fields

These may not be relevant in most cases. If they are, please fill them out. Otherwise, feel free to remove them.

**Comment by chummer5a** [comment]
They should show up as mods for the vehicle, ie Weapon Mount Type (Standard), Weapon Mount Visibility (External). I'm not particularly happy with the implementation, but it is what it is for now.

**Comment by skarsol** [comment]
All the weapon mount stuff is super ugly currently.

**Comment by skarsol** [comment]
@chummer5a Take a look at the WeaponMounts branch and tell me what you think of implementing the weapon mount mods that way. It needs cleanup, but if you add a vehicle mount (not drone) you can add a mod to it and it calcs the availity correctly. Uses tags in the vehicle mods xml instead of breaking the mounts into their own xml/category. Let me know if you want me to continue on this road or if you'd like to see something different.

**Comment by chummer5a** [comment]
Hrm, only major change I'd suggest is that we probably don't need vehiclemountmod, it would probably be a bit simpler to upgrade the vehiclemod form to accept limitation based on a forced category. Concept's solid aside from that, sure.

**Comment by skarsol** [comment]
Yeah, I thought about that but wasn't sure how much relied on that form being unchanged, so tacking on a new form was the easy solution to that. I'll see about adding a restriction to vehiclemod.

**Comment by Zaraka** [comment]
In latest stable 5.195 pop out mounts are missing from list of vehicle modifications
