### ISSUE TITLE
Purchasing a skill point with Karma prevents getting a Specialization with Points at Chargen.

### ISSUE THREAD

**Issue by rtngtom** [chummer5a/chummer5a#877]
### Expected behaviour:
Specs can be purchased with Points even if karma has been spent on the skill.

### Actual behaviour
Specs are switched to buy with karma upon purchasing a point through karma.

### Steps to reproduce the behaviour
Purchase a skill and spec with points at chargen, then purchase a skill point with karma.

**Comment by joha4270** [comment]
Except you cannot. 

Step 5 of chargen is purchase skill
Step 7 is leftover karma.

You cannot go back in time

**Comment by rtngtom** [comment]
Yes, if you only buy the skill with karma. What about putting up a skill with points, getting a spec, then at step 7, upgrading it further with karma?

**Comment by OLStefan** [comment]
I think that should be possible.

**Comment by nw2372** [comment]
If you do the point-buy-system, once you place a single point into the corresponding skillgroup, you cannot buy any specializations any more..
This is really the same, just confirming and "extending" to the Karma-Build.

**Comment by joha4270** [comment]
Fixed the original issue. I'm not believing the issue reported by @nw2372 actually is an issue.

Breaking a skill group with skill points is not allowed by the rules. I don't see any other scenario where you first add skill group, then get a specialization with points. If you believe your issue is something else or that this is allowed, create a new issue where you cite the books or catalyst as evidence for your opinion.

**Comment by nw2372** [comment]
I don't actually agree.
I think it was a legitimate issue, but it seems the issue has been fixed in 5.181.60, so:

Thank you!
