### ISSUE TITLE
Feature request: Better system for modular limbs

### ISSUE THREAD

**Issue by AssaultBunny** [chummer5a/chummer5a#900]
The way things currently are, the modular limb system is extremely fiddly. If you have more than one set of limbs (which is kind of the point of the modular system), you need to deal with essence antiholes and temporary buff/debuffs if your limb sets have different attribute scores. I would like if it was as simple as the armor tab; being able to check a box to indicate to the program which limb is attached, letting it ignore any others. It would also need to change the modular limb accessory to a check box during limb purchasing.

It's a pretty decent sized job, and I admit it's for a fairly niche part, but I feel it would still be worthwhile.

**Comment by OLStefan** [comment]
How about having the modular limbs in the Cyberlimbs category and adding them as plugins to the modular connectors?

That way would be only minor data changes, solve the essence issue.

For the stat increasement all modular limbs added in this way would be ignored, but honestly i don't even know how the stats are supposed to be calculated if you are not replacing the whole limb but only parts of it.

**Comment by AssaultBunny** [comment]
That would be a good way to do it; have modular limbs as a separate item instead of a plug-in for existing limbs. Unfortunately you run into the problem of connectors themselves having a separate essence cost, in addition to whatever limb is plugged into them. This gets complicated when connectors and limbs of different grades are mixed, which I _think_ is allowed.

I've been told that attributes flow down a limb, so if a full arm has customised/enhanced attributes and also a lower arm/wrist connector, whatever is attached would share the attributes of the limb it is connected to. This doesn't work in reverse though, so a cyber lower arm would still need to be customised/enhanced if attached to a meat upper arm, and any differences averaged.

**Comment by OLStefan** [comment]
After some looking into it, I won't remake the  because my initial idea was indeed easier, but doesn't work and the changes that are required would result in the system in place at the moment.

The only thing i changed is that now Cyberlimb are selectable (and only them) as plugins for modular connectors.

The way to do it without messing up essence cost:

- Buy a Modular Connector of your choice
- Add the right kind of limb to it (Hand, Partial or Full Arm or Foot, Partial or Full Leg in Synthetic or Obvious)
- Add the Modular Component to that Limb to account for the reduced Capacity and the increased Availability and Cost of Modular Limbs

It is also possible to first buy a limb and add a connector to it and then add another limb to the connector.

That way you only pay the essence cost of the Modular Connector or the Limb in which the Connector is build in.

**Comment by AssaultBunny** [comment]
That still has the problem of different limbs with different stats and/or bonuses. There needs to be some way of indicating the "active" limb.

For example, I have a character with two sets of arms. One has enhanced agility 3, armor 2, and optimisation (pistols). The other has enhanced agility 1, no armor, and improved synthskin. At best, the current described system would average those stats, and at worse stack them.

Essence cost was just the most obvious problem, but there are several more to deal with.

**Comment by chummer5a** [comment]
Honestly the simplest fix here is to add an Installed tag for the limb. Same functionality as Equipped for Armour, just need some sanity checks for Essence and such.

**Comment by AssaultBunny** [comment]
Giving this a bump, as it's still a major issue for anyone trying a modular build.

**Comment by chummer5a** [comment]
This has been implemented in current nightly builds. Any modular limbs that are not children of a modular connector will have zero Essence cost, and otherwise have no impact on the user. There are some minor double-ups of the tooltip text to show how modified agility and strength are calculated, but the raw functionality's there. Big thanks to @DelnarErsike for implementing all that.
