### ISSUE TITLE
5.180 Crashhandler close cummer instead of character

### ISSUE THREAD

**Issue by Lexanius** [chummer5a/chummer5a#905]
### Chummer Version
5.180

### Expected behaviour
crash handler close only the caracter in chummer better nothing, but it close all.

### Actual behaviour
crash handler close Chummer
When windows block the crashhandler cummer can run, after crashing

### Steps to reproduce the behaviour
Crash Chummer e.g. with remove specializations

**Comment by joha4270** [comment]
There isn't any character level confinement in chummer. The crash handler starts when chummer has an error it is unable to handle gracefully and shuts down instead of possibly corrupting the character file. 

Adding character level confinement _is_ possible, but nobody on the team considers it worth the time investment (i wouldn't be surprised if it took 500 hours of work). Feel free to do it yourself.
