### ISSUE TITLE
Extra karma cost for adding cyber/bio to new magician

### ISSUE THREAD

**Issue by KCKitsune** [chummer5a/chummer5a#912]
### Chummer Version
5.180.36.0

### Expected behaviour
Adding cyber or bioware to a magician (any type) does not cost 5 karma

### Actual behaviour
Whenever a magician's Essence drops, it costs an extra 5 karma.

### Steps to reproduce the behaviour
Make a new character, add in any magician positive quality, and then add in a piece of cyber or bioware.

**Comment by OLStefan** [comment]
This behaviour is caused in creation to raise your magic attribute. The calculation for that is somewhat buggy atm.

**Comment by OLStefan** [comment]
Essence Loss now reduces the Maximum of RES/MAG, but you have to buy the lost point with Karma/Special Attribute Points regarding which build mode you are using.

**Comment by bodison** [comment]
I've tried it with the Karma build. Version 5.180.44

mystic adept with 1 Magic costs 35Karma
after 1 point of essence loss

EXPECTED:
mystic adept with 1 Magic costs 35Karma

ACTUAL:
mystic adept with 1 Magic costs 45Karma



If you say that you have to buy back 1 point in magic because it was lost (the buy-back should not happen automatically!!), the Karma cost would be 35(mystic adept) + 5(1 Magic)

Also: please apply the same fix to Resonance!

In Point buy this is a question of chronology. If you activate the house rule "Essence loss only reduces MAG/RES maximum" everything works as expected. Should this be default during Point buy?

**Comment by OLStefan** [comment]
Now you habve to buy the most expensive point multiple times. 

So if you are Magician with 4 Magic plus 2 lost to Essence Loss you pay:

MAG 2 (10) + MAG 3 (15) + MAG 4 (20) + MAG 4 (20) + MAG 4 (20) = 85 Karma.

If you don't want to pay the additional Karma, there is a House Rule so that only the Maximum is reduced through Essence Loss.
