### ISSUE TITLE
Crash when creating Xenosapient AI

### ISSUE THREAD

**Issue by eshangray** [chummer5a/chummer5a#926]
[exception.txt](https://github.com/chummer5a/chummer5a/files/315008/exception.txt)

### Chummer Version
5.181.00

### Expected behaviour
Create Xeno AI

### Actual behaviour
Crash when creating

### Steps to reproduce the behaviour
File->New Character->Karma(Standard)->Metasapient->AI->Xenosapient->Ok

### Link to affected character file
Unable to create
Exception file generated by crash attached, will upload more info if required

**Comment by chummer5a** [comment]
Unable to replicate in the current nightlies, I believe I fixed this with a quality rename in an earlier commit. If you're comfortable using the nightly builds (There's no practical difference between them, save that the nightlies have had less testing for bugs) then try that, otherwise we should have the new version released in a couple of days.
