### ISSUE TITLE
program is crashing

### ISSUE THREAD

**Issue by moneypenni67** [chummer5a/chummer5a#961]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
(Enter text here)
5.181.0
### Expected behaviour
(Enter text here)
print screen does not reflect imputted data. and now will not even load print screen. noticed that new char gen for prioity build sets karma at 400 and nuyen at 0 so tracking is impossible
### Actual behaviour
(Enter text here)
before this last upgrade program was working fine
### Steps to reproduce the behaviour
(Enter text here)
open new chara gen and was able to create behaviour multiple times
### Link to affected character file
(Enter text here)

**Comment by joha4270** [comment]
So I'm not actually sure what your issue is. 

You seen to be describing 3 different issues, your program is crashing, your print is looking wrong? and you have 400bp. 

Your reproduction instructions seems to be open the program. 

This is about as useful as a wet tissue for stopping bullets. 

I'm going to suggests you reinstall from scratch. If that does not fix your issue(s?) create a new issue for each issue where you describe **in details** how to reproduce your issue. One bullet point per mouseclick. After that you make a screenshot, circle the part that is wrong explain why it is wrong. 

Thank you.
